`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:57 CST (May 26 2023 07:18:57 UTC)

module dut_entirecomputation_alt4_1(in1, in2, in3, out1);
  input in1, in2;
  input [2:0] in3;
  output [3:0] out1;
  wire in1, in2;
  wire [2:0] in3;
  wire [3:0] out1;
  wire asc002_0_, asc002_1_, asc002_2_, asc002_3_, inc_add_26_2_1_n_0,
       inc_add_26_2_1_n_1, inc_add_26_2_1_n_2, inc_add_26_2_1_n_3;
  wire inc_add_26_2_1_n_4, n_16, n_17, n_18;
  NOR2BX1 g33(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g34(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g35(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g36(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  MXI2XL inc_add_26_2_1_g30(.A (in3[2]), .B (inc_add_26_2_1_n_2), .S0
       (inc_add_26_2_1_n_0), .Y (asc002_2_));
  NOR3BX1 inc_add_26_2_1_g31(.AN (in3[1]), .B (inc_add_26_2_1_n_2), .C
       (n_16), .Y (asc002_3_));
  MXI2XL inc_add_26_2_1_g32(.A (in3[1]), .B (inc_add_26_2_1_n_1), .S0
       (n_17), .Y (asc002_1_));
  MXI2XL inc_add_26_2_1_g35(.A (inc_add_26_2_1_n_3), .B (in3[0]), .S0
       (in2), .Y (asc002_0_));
  NAND2X8 inc_add_26_2_1_g36(.A (in3[0]), .B (in2), .Y
       (inc_add_26_2_1_n_4));
  INVX1 inc_add_26_2_1_g37(.A (in3[0]), .Y (inc_add_26_2_1_n_3));
  INVX1 inc_add_26_2_1_g38(.A (in3[2]), .Y (inc_add_26_2_1_n_2));
  INVX1 inc_add_26_2_1_g39(.A (in3[1]), .Y (inc_add_26_2_1_n_1));
  NAND2BX1 inc_add_26_2_1_g2(.AN (inc_add_26_2_1_n_4), .B (in3[1]), .Y
       (inc_add_26_2_1_n_0));
  INVXL fopt(.A (n_18), .Y (n_16));
  INVXL fopt41(.A (n_18), .Y (n_17));
  INVXL fopt42(.A (inc_add_26_2_1_n_4), .Y (n_18));
endmodule

