`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:49 CST (May 26 2023 07:18:49 UTC)

module dut_entirecomputation_alt18_1(in1, in2, in3, out1);
  input in1;
  input [11:0] in2, in3;
  output [12:0] out1;
  wire in1;
  wire [11:0] in2, in3;
  wire [12:0] out1;
  wire add_26_2_n_1, add_26_2_n_2, add_26_2_n_3, add_26_2_n_5,
       add_26_2_n_6, add_26_2_n_7, add_26_2_n_8, add_26_2_n_9;
  wire add_26_2_n_10, add_26_2_n_11, add_26_2_n_12, add_26_2_n_13,
       add_26_2_n_14, add_26_2_n_15, add_26_2_n_16, add_26_2_n_17;
  wire add_26_2_n_18, add_26_2_n_19, add_26_2_n_20, add_26_2_n_21,
       add_26_2_n_22, add_26_2_n_23, add_26_2_n_24, add_26_2_n_25;
  wire add_26_2_n_26, add_26_2_n_27, add_26_2_n_28, add_26_2_n_29,
       add_26_2_n_30, add_26_2_n_31, add_26_2_n_32, add_26_2_n_33;
  wire add_26_2_n_34, add_26_2_n_35, add_26_2_n_36, add_26_2_n_37,
       add_26_2_n_38, add_26_2_n_39, add_26_2_n_40, add_26_2_n_41;
  wire add_26_2_n_42, add_26_2_n_43, add_26_2_n_44, add_26_2_n_46,
       add_26_2_n_47, add_26_2_n_48, add_26_2_n_49, add_26_2_n_50;
  wire add_26_2_n_51, add_26_2_n_52, add_26_2_n_53, add_26_2_n_54,
       add_26_2_n_55, add_26_2_n_56, add_26_2_n_57, add_26_2_n_58;
  wire add_26_2_n_59, add_26_2_n_60, add_26_2_n_61, add_26_2_n_62,
       add_26_2_n_63, add_26_2_n_64, add_26_2_n_65, add_26_2_n_66;
  wire add_26_2_n_68, add_26_2_n_70, add_26_2_n_71, add_26_2_n_72,
       add_26_2_n_73, add_26_2_n_74, add_26_2_n_75, add_26_2_n_76;
  wire add_26_2_n_77, add_26_2_n_78, add_26_2_n_79, add_26_2_n_80,
       add_26_2_n_81, add_26_2_n_84, add_26_2_n_85, add_26_2_n_86;
  wire add_26_2_n_91, add_26_2_n_92, add_26_2_n_93, asc002_0_,
       asc002_2_, asc002_3_, asc002_4_, asc002_5_;
  wire asc002_6_, asc002_7_, asc002_8_, asc002_9_, asc002_10_,
       asc002_11_, asc002_12_, n_0;
  wire n_1, n_122, n_123, n_127, n_128, n_129, n_131, n_132;
  wire n_133, n_135, n_137, n_140, n_142, n_143, n_144, n_147;
  NOR2BX1 g105(.AN (n_0), .B (n_1), .Y (out1[12]));
  NOR2BX1 g106(.AN (asc002_11_), .B (in1), .Y (out1[11]));
  NOR2BX1 g107(.AN (asc002_9_), .B (in1), .Y (out1[9]));
  NOR2BX1 g108(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g109(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g110(.AN (asc002_8_), .B (in1), .Y (out1[8]));
  NOR2BX1 g111(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g112(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g113(.AN (asc002_10_), .B (in1), .Y (out1[10]));
  NOR2BX1 g114(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g115(.AN (n_123), .B (in1), .Y (out1[1]));
  NOR2BX1 g116(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g117(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  INVX1 g118(.A (asc002_12_), .Y (n_1));
  INVXL g119(.A (in1), .Y (n_0));
  MXI2XL add_26_2_g270(.A (add_26_2_n_56), .B (add_26_2_n_57), .S0
       (add_26_2_n_91), .Y (asc002_11_));
  MXI2XL add_26_2_g271(.A (add_26_2_n_52), .B (add_26_2_n_51), .S0
       (add_26_2_n_93), .Y (asc002_10_));
  MXI2XL add_26_2_g272(.A (add_26_2_n_49), .B (add_26_2_n_50), .S0
       (add_26_2_n_92), .Y (asc002_9_));
  OAI21X1 add_26_2_g273(.A0 (add_26_2_n_65), .A1 (n_142), .B0
       (add_26_2_n_72), .Y (asc002_12_));
  AOI2BB1XL add_26_2_g274(.A0N (add_26_2_n_32), .A1N (add_26_2_n_85),
       .B0 (add_26_2_n_59), .Y (add_26_2_n_93));
  AOI2BB1XL add_26_2_g275(.A0N (add_26_2_n_26), .A1N (add_26_2_n_85),
       .B0 (add_26_2_n_24), .Y (add_26_2_n_92));
  NOR2X1 add_26_2_g276(.A (add_26_2_n_74), .B (add_26_2_n_86), .Y
       (add_26_2_n_91));
  MXI2XL add_26_2_g277(.A (add_26_2_n_39), .B (add_26_2_n_40), .S0
       (n_143), .Y (asc002_8_));
  MXI2XL add_26_2_g278(.A (add_26_2_n_41), .B (add_26_2_n_42), .S0
       (add_26_2_n_81), .Y (asc002_7_));
  MXI2XL add_26_2_g279(.A (add_26_2_n_38), .B (add_26_2_n_37), .S0
       (add_26_2_n_5), .Y (asc002_6_));
  MXI2XL add_26_2_g280(.A (add_26_2_n_43), .B (add_26_2_n_44), .S0
       (add_26_2_n_84), .Y (asc002_5_));
  NOR2X1 add_26_2_g281(.A (add_26_2_n_66), .B (add_26_2_n_85), .Y
       (add_26_2_n_86));
  NOR2X4 add_26_2_g282(.A (add_26_2_n_71), .B (add_26_2_n_80), .Y
       (add_26_2_n_85));
  AOI2BB1XL add_26_2_g284(.A0N (add_26_2_n_8), .A1N (n_137), .B0
       (add_26_2_n_11), .Y (add_26_2_n_84));
  MXI2XL add_26_2_g285(.A (add_26_2_n_34), .B (add_26_2_n_35), .S0
       (n_137), .Y (asc002_4_));
  MXI2XL add_26_2_g286(.A (add_26_2_n_47), .B (add_26_2_n_48), .S0
       (add_26_2_n_78), .Y (asc002_3_));
  NOR2X1 add_26_2_g287(.A (add_26_2_n_73), .B (add_26_2_n_79), .Y
       (add_26_2_n_81));
  NOR2X4 add_26_2_g289(.A (add_26_2_n_64), .B (add_26_2_n_77), .Y
       (add_26_2_n_80));
  NOR2X1 add_26_2_g290(.A (add_26_2_n_63), .B (n_137), .Y
       (add_26_2_n_79));
  NOR2BX1 add_26_2_g291(.AN (add_26_2_n_12), .B (add_26_2_n_76), .Y
       (add_26_2_n_78));
  NOR2X2 add_26_2_g293(.A (add_26_2_n_60), .B (add_26_2_n_75), .Y
       (add_26_2_n_77));
  NOR2X1 add_26_2_g294(.A (add_26_2_n_25), .B (n_132), .Y
       (add_26_2_n_76));
  NOR2X2 add_26_2_g295(.A (add_26_2_n_2), .B (add_26_2_n_70), .Y
       (add_26_2_n_75));
  OAI2BB1X1 add_26_2_g296(.A0N (add_26_2_n_20), .A1N (add_26_2_n_59),
       .B0 (add_26_2_n_9), .Y (add_26_2_n_74));
  OAI21X1 add_26_2_g297(.A0 (add_26_2_n_21), .A1 (n_128), .B0
       (add_26_2_n_28), .Y (add_26_2_n_73));
  AOI21X1 add_26_2_g298(.A0 (add_26_2_n_36), .A1 (add_26_2_n_59), .B0
       (add_26_2_n_61), .Y (add_26_2_n_72));
  OAI21X2 add_26_2_g299(.A0 (add_26_2_n_55), .A1 (add_26_2_n_62), .B0
       (add_26_2_n_58), .Y (add_26_2_n_71));
  NOR2X4 add_26_2_g300(.A (add_26_2_n_1), .B (add_26_2_n_68), .Y
       (add_26_2_n_70));
  NOR2X2 add_26_2_g302(.A (add_26_2_n_7), .B (add_26_2_n_18), .Y
       (add_26_2_n_68));
  NAND2X1 add_26_2_g304(.A (add_26_2_n_20), .B (add_26_2_n_31), .Y
       (add_26_2_n_66));
  NAND2X1 add_26_2_g305(.A (add_26_2_n_36), .B (add_26_2_n_31), .Y
       (add_26_2_n_65));
  NAND2X1 add_26_2_g306(.A (add_26_2_n_54), .B (add_26_2_n_33), .Y
       (add_26_2_n_64));
  NAND2BX1 add_26_2_g307(.AN (add_26_2_n_21), .B (add_26_2_n_33), .Y
       (add_26_2_n_63));
  NOR2X2 add_26_2_g309(.A (add_26_2_n_15), .B (add_26_2_n_46), .Y
       (add_26_2_n_62));
  OAI21X1 add_26_2_g310(.A0 (add_26_2_n_9), .A1 (add_26_2_n_22), .B0
       (add_26_2_n_30), .Y (add_26_2_n_61));
  OAI21X1 add_26_2_g311(.A0 (add_26_2_n_12), .A1 (add_26_2_n_14), .B0
       (add_26_2_n_16), .Y (add_26_2_n_60));
  OAI21X1 add_26_2_g312(.A0 (add_26_2_n_23), .A1 (add_26_2_n_13), .B0
       (add_26_2_n_29), .Y (add_26_2_n_59));
  AOI2BB1X1 add_26_2_g313(.A0N (add_26_2_n_28), .A1N (add_26_2_n_27),
       .B0 (add_26_2_n_17), .Y (add_26_2_n_58));
  INVX1 add_26_2_g314(.A (add_26_2_n_56), .Y (add_26_2_n_57));
  INVX1 add_26_2_g315(.A (add_26_2_n_54), .Y (add_26_2_n_55));
  INVX1 add_26_2_g317(.A (add_26_2_n_51), .Y (add_26_2_n_52));
  INVX1 add_26_2_g318(.A (add_26_2_n_49), .Y (add_26_2_n_50));
  INVX1 add_26_2_g319(.A (add_26_2_n_47), .Y (add_26_2_n_48));
  NOR2X1 add_26_2_g321(.A (add_26_2_n_10), .B (add_26_2_n_6), .Y
       (add_26_2_n_46));
  NOR2BX1 add_26_2_g322(.AN (add_26_2_n_30), .B (add_26_2_n_22), .Y
       (add_26_2_n_56));
  NOR2X1 add_26_2_g323(.A (add_26_2_n_27), .B (add_26_2_n_21), .Y
       (add_26_2_n_54));
  NAND2BX1 add_26_2_g324(.AN (add_26_2_n_25), .B (add_26_2_n_12), .Y
       (add_26_2_n_53));
  NAND2X1 add_26_2_g325(.A (add_26_2_n_9), .B (add_26_2_n_20), .Y
       (add_26_2_n_51));
  NOR2BX1 add_26_2_g326(.AN (add_26_2_n_29), .B (add_26_2_n_13), .Y
       (add_26_2_n_49));
  NOR2BX1 add_26_2_g328(.AN (add_26_2_n_16), .B (n_140), .Y
       (add_26_2_n_47));
  INVX1 add_26_2_g329(.A (add_26_2_n_43), .Y (add_26_2_n_44));
  INVX1 add_26_2_g330(.A (add_26_2_n_41), .Y (add_26_2_n_42));
  INVX1 add_26_2_g331(.A (add_26_2_n_39), .Y (add_26_2_n_40));
  INVX1 add_26_2_g332(.A (add_26_2_n_37), .Y (add_26_2_n_38));
  INVX1 add_26_2_g333(.A (add_26_2_n_34), .Y (add_26_2_n_35));
  INVX1 add_26_2_g335(.A (add_26_2_n_31), .Y (add_26_2_n_32));
  NOR2X1 add_26_2_g337(.A (add_26_2_n_15), .B (n_135), .Y
       (add_26_2_n_43));
  NOR2X1 add_26_2_g338(.A (add_26_2_n_17), .B (add_26_2_n_27), .Y
       (add_26_2_n_41));
  NOR2X1 add_26_2_g339(.A (add_26_2_n_24), .B (add_26_2_n_26), .Y
       (add_26_2_n_39));
  NAND2BX1 add_26_2_g340(.AN (add_26_2_n_21), .B (add_26_2_n_28), .Y
       (add_26_2_n_37));
  NOR2X1 add_26_2_g341(.A (add_26_2_n_22), .B (add_26_2_n_19), .Y
       (add_26_2_n_36));
  NOR2X1 add_26_2_g342(.A (add_26_2_n_11), .B (add_26_2_n_8), .Y
       (add_26_2_n_34));
  NOR2X1 add_26_2_g343(.A (add_26_2_n_6), .B (add_26_2_n_8), .Y
       (add_26_2_n_33));
  NOR2X1 add_26_2_g344(.A (add_26_2_n_13), .B (add_26_2_n_26), .Y
       (add_26_2_n_31));
  INVX1 add_26_2_g346(.A (add_26_2_n_23), .Y (add_26_2_n_24));
  INVX1 add_26_2_g347(.A (add_26_2_n_19), .Y (add_26_2_n_20));
  NAND2X1 add_26_2_g348(.A (in2[11]), .B (in3[11]), .Y (add_26_2_n_30));
  NAND2X1 add_26_2_g349(.A (in2[9]), .B (in3[9]), .Y (add_26_2_n_29));
  NAND2X1 add_26_2_g351(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_28));
  NOR2X2 add_26_2_g352(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_27));
  NOR2X1 add_26_2_g353(.A (in2[8]), .B (in3[8]), .Y (add_26_2_n_26));
  NOR2X2 add_26_2_g354(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_25));
  NAND2X1 add_26_2_g355(.A (in2[8]), .B (in3[8]), .Y (add_26_2_n_23));
  NOR2X1 add_26_2_g356(.A (in2[11]), .B (in3[11]), .Y (add_26_2_n_22));
  NOR2X2 add_26_2_g357(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_21));
  NOR2X1 add_26_2_g358(.A (in2[10]), .B (in3[10]), .Y (add_26_2_n_19));
  INVX1 add_26_2_g360(.A (add_26_2_n_10), .Y (add_26_2_n_11));
  NOR2X2 add_26_2_g361(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_18));
  AND2X1 add_26_2_g362(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_17));
  NAND2X1 add_26_2_g363(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_16));
  AND2X1 add_26_2_g364(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_15));
  NOR2X6 add_26_2_g365(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_14));
  NOR2X1 add_26_2_g366(.A (in2[9]), .B (in3[9]), .Y (add_26_2_n_13));
  NAND2X1 add_26_2_g367(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_12));
  NAND2X1 add_26_2_g368(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_10));
  NAND2X1 add_26_2_g369(.A (in2[10]), .B (in3[10]), .Y (add_26_2_n_9));
  NOR2X1 add_26_2_g370(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_8));
  NAND2X8 add_26_2_g371(.A (in2[0]), .B (in3[0]), .Y (add_26_2_n_7));
  NOR2X2 add_26_2_g372(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_6));
  NOR2BX1 add_26_2_g2(.AN (n_127), .B (add_26_2_n_3), .Y
       (add_26_2_n_5));
  XOR2XL add_26_2_g376(.A (add_26_2_n_53), .B (n_131), .Y (asc002_2_));
  NOR2BX1 add_26_2_g377(.AN (add_26_2_n_33), .B (n_137), .Y
       (add_26_2_n_3));
  OR2XL add_26_2_g378(.A (add_26_2_n_14), .B (add_26_2_n_25), .Y
       (add_26_2_n_2));
  CLKAND2X3 add_26_2_g379(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_1));
  XOR2XL add_26_2_g380(.A (in2[0]), .B (in3[0]), .Y (asc002_0_));
  XOR2XL g2(.A (n_122), .B (n_147), .Y (n_123));
  OR2XL g3(.A (add_26_2_n_1), .B (add_26_2_n_18), .Y (n_122));
  INVXL fopt382(.A (n_129), .Y (n_127));
  INVXL fopt383(.A (n_129), .Y (n_128));
  INVXL fopt384(.A (add_26_2_n_62), .Y (n_129));
  INVXL fopt385(.A (n_133), .Y (n_131));
  INVXL fopt386(.A (n_133), .Y (n_132));
  INVXL fopt387(.A (add_26_2_n_70), .Y (n_133));
  BUFX2 fopt388(.A (add_26_2_n_6), .Y (n_135));
  BUFX3 fopt389(.A (add_26_2_n_77), .Y (n_137));
  BUFX2 fopt(.A (add_26_2_n_14), .Y (n_140));
  INVXL fopt390(.A (n_144), .Y (n_142));
  INVXL fopt391(.A (n_144), .Y (n_143));
  INVXL fopt392(.A (add_26_2_n_85), .Y (n_144));
  BUFX2 fopt393(.A (add_26_2_n_7), .Y (n_147));
endmodule

