`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:56 CST (May 26 2023 07:18:56 UTC)

module dut_entirecomputation_alt5_1(in1, in2, in3, out1);
  input in1, in2;
  input [3:0] in3;
  output [4:0] out1;
  wire in1, in2;
  wire [3:0] in3;
  wire [4:0] out1;
  wire asc002_0_, asc002_1_, asc002_2_, asc002_3_, asc002_4_,
       inc_add_26_2_1_n_2, inc_add_26_2_1_n_3, inc_add_26_2_1_n_4;
  wire inc_add_26_2_1_n_5, inc_add_26_2_1_n_6, inc_add_26_2_1_n_8,
       inc_add_26_2_1_n_10, n_0, n_1, n_20;
  NOR2BX1 g41(.AN (n_0), .B (n_1), .Y (out1[4]));
  NOR2BX1 g42(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g43(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g44(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g45(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  INVX1 g46(.A (asc002_4_), .Y (n_1));
  INVXL g47(.A (in1), .Y (n_0));
  MXI2XL inc_add_26_2_1_g41(.A (in3[3]), .B (inc_add_26_2_1_n_2), .S0
       (inc_add_26_2_1_n_10), .Y (asc002_3_));
  NAND2X2 inc_add_26_2_1_g43(.A (in3[2]), .B (inc_add_26_2_1_n_8), .Y
       (inc_add_26_2_1_n_10));
  MXI2XL inc_add_26_2_1_g46(.A (in3[1]), .B (inc_add_26_2_1_n_4), .S0
       (n_20), .Y (asc002_1_));
  NOR2X6 inc_add_26_2_1_g47(.A (inc_add_26_2_1_n_4), .B
       (inc_add_26_2_1_n_5), .Y (inc_add_26_2_1_n_8));
  MXI2XL inc_add_26_2_1_g48(.A (inc_add_26_2_1_n_3), .B (in3[0]), .S0
       (in2), .Y (asc002_0_));
  NAND2X1 inc_add_26_2_1_g49(.A (in3[3]), .B (in3[2]), .Y
       (inc_add_26_2_1_n_6));
  NAND2X8 inc_add_26_2_1_g50(.A (in3[0]), .B (in2), .Y
       (inc_add_26_2_1_n_5));
  CLKINVX2 inc_add_26_2_1_g52(.A (in3[1]), .Y (inc_add_26_2_1_n_4));
  INVX1 inc_add_26_2_1_g53(.A (in3[0]), .Y (inc_add_26_2_1_n_3));
  INVX1 inc_add_26_2_1_g54(.A (in3[3]), .Y (inc_add_26_2_1_n_2));
  NOR2BX1 inc_add_26_2_1_g2(.AN (inc_add_26_2_1_n_8), .B
       (inc_add_26_2_1_n_6), .Y (asc002_4_));
  XOR2XL inc_add_26_2_1_g55(.A (in3[2]), .B (inc_add_26_2_1_n_8), .Y
       (asc002_2_));
  BUFX2 fopt(.A (inc_add_26_2_1_n_5), .Y (n_20));
endmodule

