`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:41 CST (May 26 2023 07:18:41 UTC)

module dut_entirecomputation_alt14_4(in1, in2, in3, out1);
  input in1;
  input [7:0] in2, in3;
  output [8:0] out1;
  wire in1;
  wire [7:0] in2, in3;
  wire [8:0] out1;
  wire add_26_2_n_0, add_26_2_n_1, add_26_2_n_2, add_26_2_n_3,
       add_26_2_n_4, add_26_2_n_5, add_26_2_n_6, add_26_2_n_7;
  wire add_26_2_n_8, add_26_2_n_9, add_26_2_n_10, add_26_2_n_11,
       add_26_2_n_12, add_26_2_n_13, add_26_2_n_14, add_26_2_n_15;
  wire add_26_2_n_16, add_26_2_n_17, add_26_2_n_18, add_26_2_n_19,
       add_26_2_n_20, add_26_2_n_21, add_26_2_n_23, add_26_2_n_24;
  wire add_26_2_n_26, add_26_2_n_27, add_26_2_n_28, add_26_2_n_29,
       add_26_2_n_31, add_26_2_n_34, add_26_2_n_35, add_26_2_n_36;
  wire add_26_2_n_40, asc002_0_, asc002_1_, asc002_2_, asc002_3_,
       asc002_4_, asc002_5_, asc002_6_;
  wire asc002_7_, asc002_8_;
  NOR2BX1 g73(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g74(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g75(.AN (asc002_8_), .B (in1), .Y (out1[8]));
  NOR2BX1 g76(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g77(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g78(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g79(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g80(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g81(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  XNOR2X1 add_26_2_g156(.A (add_26_2_n_14), .B (add_26_2_n_40), .Y
       (asc002_7_));
  OAI21X1 add_26_2_g157(.A0 (add_26_2_n_4), .A1 (add_26_2_n_34), .B0
       (add_26_2_n_1), .Y (add_26_2_n_40));
  XNOR2X1 add_26_2_g158(.A (add_26_2_n_13), .B (add_26_2_n_34), .Y
       (asc002_6_));
  XNOR2X1 add_26_2_g159(.A (add_26_2_n_19), .B (add_26_2_n_35), .Y
       (asc002_5_));
  INVXL add_26_2_g160(.A (add_26_2_n_36), .Y (asc002_8_));
  AOI31X1 add_26_2_g161(.A0 (add_26_2_n_29), .A1 (add_26_2_n_15), .A2
       (add_26_2_n_16), .B0 (add_26_2_n_24), .Y (add_26_2_n_36));
  OAI21X1 add_26_2_g162(.A0 (add_26_2_n_8), .A1 (add_26_2_n_28), .B0
       (add_26_2_n_2), .Y (add_26_2_n_35));
  AOI21X1 add_26_2_g163(.A0 (add_26_2_n_16), .A1 (add_26_2_n_29), .B0
       (add_26_2_n_20), .Y (add_26_2_n_34));
  MXI2XL add_26_2_g164(.A (add_26_2_n_29), .B (add_26_2_n_28), .S0
       (add_26_2_n_18), .Y (asc002_4_));
  XNOR2X1 add_26_2_g165(.A (add_26_2_n_17), .B (add_26_2_n_31), .Y
       (asc002_3_));
  OAI2BB1X1 add_26_2_g166(.A0N (add_26_2_n_7), .A1N (add_26_2_n_26),
       .B0 (add_26_2_n_6), .Y (add_26_2_n_31));
  XNOR2X1 add_26_2_g167(.A (add_26_2_n_12), .B (add_26_2_n_26), .Y
       (asc002_2_));
  INVX1 add_26_2_g168(.A (add_26_2_n_29), .Y (add_26_2_n_28));
  OAI211X1 add_26_2_g169(.A0 (add_26_2_n_6), .A1 (add_26_2_n_9), .B0
       (add_26_2_n_27), .C0 (add_26_2_n_5), .Y (add_26_2_n_29));
  NAND3BXL add_26_2_g170(.AN (add_26_2_n_9), .B (add_26_2_n_26), .C
       (add_26_2_n_7), .Y (add_26_2_n_27));
  ADDFX1 add_26_2_g171(.A (add_26_2_n_21), .B (in3[1]), .CI (in2[1]),
       .CO (add_26_2_n_26), .S (asc002_1_));
  OAI211X1 add_26_2_g172(.A0 (add_26_2_n_1), .A1 (add_26_2_n_0), .B0
       (add_26_2_n_23), .C0 (add_26_2_n_11), .Y (add_26_2_n_24));
  NAND2XL add_26_2_g173(.A (add_26_2_n_15), .B (add_26_2_n_20), .Y
       (add_26_2_n_23));
  ADDHX1 add_26_2_g174(.A (in2[0]), .B (in3[0]), .CO (add_26_2_n_21),
       .S (asc002_0_));
  OAI21X1 add_26_2_g175(.A0 (add_26_2_n_2), .A1 (add_26_2_n_3), .B0
       (add_26_2_n_10), .Y (add_26_2_n_20));
  NAND2BX1 add_26_2_g176(.AN (add_26_2_n_3), .B (add_26_2_n_10), .Y
       (add_26_2_n_19));
  NAND2BX1 add_26_2_g177(.AN (add_26_2_n_8), .B (add_26_2_n_2), .Y
       (add_26_2_n_18));
  NAND2BX1 add_26_2_g178(.AN (add_26_2_n_9), .B (add_26_2_n_5), .Y
       (add_26_2_n_17));
  NOR2X1 add_26_2_g179(.A (add_26_2_n_3), .B (add_26_2_n_8), .Y
       (add_26_2_n_16));
  NOR2X1 add_26_2_g180(.A (add_26_2_n_0), .B (add_26_2_n_4), .Y
       (add_26_2_n_15));
  NAND2BX1 add_26_2_g181(.AN (add_26_2_n_0), .B (add_26_2_n_11), .Y
       (add_26_2_n_14));
  NOR2BX1 add_26_2_g182(.AN (add_26_2_n_1), .B (add_26_2_n_4), .Y
       (add_26_2_n_13));
  NAND2X1 add_26_2_g183(.A (add_26_2_n_6), .B (add_26_2_n_7), .Y
       (add_26_2_n_12));
  NAND2X1 add_26_2_g184(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_11));
  NAND2X1 add_26_2_g185(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_10));
  NOR2X1 add_26_2_g186(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_9));
  NOR2X1 add_26_2_g187(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_8));
  OR2XL add_26_2_g188(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_7));
  NAND2X1 add_26_2_g189(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_6));
  NAND2X1 add_26_2_g190(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_5));
  NOR2X1 add_26_2_g191(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_4));
  NOR2X1 add_26_2_g192(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_3));
  NAND2X1 add_26_2_g193(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_2));
  NAND2X1 add_26_2_g194(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_1));
  NOR2X1 add_26_2_g195(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_0));
endmodule

