`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:40 CST (May 26 2023 07:18:40 UTC)

module dut_entirecomputation_alt15_4(in1, in2, in3, out1);
  input in1;
  input [8:0] in2, in3;
  output [9:0] out1;
  wire in1;
  wire [8:0] in2, in3;
  wire [9:0] out1;
  wire add_26_2_n_0, add_26_2_n_1, add_26_2_n_2, add_26_2_n_3,
       add_26_2_n_4, add_26_2_n_5, add_26_2_n_6, add_26_2_n_7;
  wire add_26_2_n_8, add_26_2_n_9, add_26_2_n_10, add_26_2_n_11,
       add_26_2_n_12, add_26_2_n_13, add_26_2_n_14, add_26_2_n_15;
  wire add_26_2_n_16, add_26_2_n_17, add_26_2_n_18, add_26_2_n_19,
       add_26_2_n_20, add_26_2_n_21, add_26_2_n_23, add_26_2_n_24;
  wire add_26_2_n_26, add_26_2_n_27, add_26_2_n_28, add_26_2_n_29,
       add_26_2_n_31, add_26_2_n_32, add_26_2_n_35, add_26_2_n_36;
  wire add_26_2_n_37, add_26_2_n_40, asc002_0_, asc002_1_, asc002_2_,
       asc002_3_, asc002_4_, asc002_5_;
  wire asc002_6_, asc002_7_, asc002_8_, asc002_9_;
  NOR2BX1 g81(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g82(.AN (asc002_8_), .B (in1), .Y (out1[8]));
  NOR2BX1 g83(.AN (asc002_9_), .B (in1), .Y (out1[9]));
  NOR2BX1 g84(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g85(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g86(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g87(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g88(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g89(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g90(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  XNOR2X1 add_26_2_g171(.A (add_26_2_n_12), .B (add_26_2_n_40), .Y
       (asc002_7_));
  ADDFX1 add_26_2_g172(.A (add_26_2_n_37), .B (in3[8]), .CI (in2[8]),
       .CO (asc002_9_), .S (asc002_8_));
  OAI21X1 add_26_2_g173(.A0 (add_26_2_n_6), .A1 (add_26_2_n_36), .B0
       (add_26_2_n_7), .Y (add_26_2_n_40));
  XNOR2X1 add_26_2_g174(.A (add_26_2_n_18), .B (add_26_2_n_36), .Y
       (asc002_6_));
  XNOR2X1 add_26_2_g175(.A (add_26_2_n_16), .B (add_26_2_n_35), .Y
       (asc002_5_));
  NAND2BX1 add_26_2_g176(.AN (add_26_2_n_24), .B (add_26_2_n_32), .Y
       (add_26_2_n_37));
  AOI21X1 add_26_2_g177(.A0 (add_26_2_n_17), .A1 (add_26_2_n_29), .B0
       (add_26_2_n_20), .Y (add_26_2_n_36));
  OAI21X1 add_26_2_g178(.A0 (add_26_2_n_9), .A1 (add_26_2_n_28), .B0
       (add_26_2_n_2), .Y (add_26_2_n_35));
  MXI2XL add_26_2_g179(.A (add_26_2_n_29), .B (add_26_2_n_28), .S0
       (add_26_2_n_14), .Y (asc002_4_));
  XNOR2X1 add_26_2_g180(.A (add_26_2_n_13), .B (add_26_2_n_31), .Y
       (asc002_3_));
  NAND3X1 add_26_2_g181(.A (add_26_2_n_29), .B (add_26_2_n_15), .C
       (add_26_2_n_17), .Y (add_26_2_n_32));
  OAI2BB1X1 add_26_2_g182(.A0N (add_26_2_n_8), .A1N (add_26_2_n_26),
       .B0 (add_26_2_n_3), .Y (add_26_2_n_31));
  XNOR2X1 add_26_2_g183(.A (add_26_2_n_19), .B (add_26_2_n_26), .Y
       (asc002_2_));
  INVX1 add_26_2_g184(.A (add_26_2_n_29), .Y (add_26_2_n_28));
  OAI211X1 add_26_2_g185(.A0 (add_26_2_n_3), .A1 (add_26_2_n_0), .B0
       (add_26_2_n_27), .C0 (add_26_2_n_4), .Y (add_26_2_n_29));
  NAND3BXL add_26_2_g186(.AN (add_26_2_n_0), .B (add_26_2_n_26), .C
       (add_26_2_n_8), .Y (add_26_2_n_27));
  ADDFX1 add_26_2_g187(.A (add_26_2_n_21), .B (in3[1]), .CI (in2[1]),
       .CO (add_26_2_n_26), .S (asc002_1_));
  OAI211X1 add_26_2_g188(.A0 (add_26_2_n_7), .A1 (add_26_2_n_10), .B0
       (add_26_2_n_23), .C0 (add_26_2_n_5), .Y (add_26_2_n_24));
  NAND2XL add_26_2_g189(.A (add_26_2_n_15), .B (add_26_2_n_20), .Y
       (add_26_2_n_23));
  ADDHX1 add_26_2_g190(.A (in2[0]), .B (in3[0]), .CO (add_26_2_n_21),
       .S (asc002_0_));
  OAI21X1 add_26_2_g191(.A0 (add_26_2_n_2), .A1 (add_26_2_n_1), .B0
       (add_26_2_n_11), .Y (add_26_2_n_20));
  NAND2X1 add_26_2_g192(.A (add_26_2_n_3), .B (add_26_2_n_8), .Y
       (add_26_2_n_19));
  NOR2BX1 add_26_2_g193(.AN (add_26_2_n_7), .B (add_26_2_n_6), .Y
       (add_26_2_n_18));
  NOR2X1 add_26_2_g194(.A (add_26_2_n_1), .B (add_26_2_n_9), .Y
       (add_26_2_n_17));
  NAND2BX1 add_26_2_g195(.AN (add_26_2_n_1), .B (add_26_2_n_11), .Y
       (add_26_2_n_16));
  NOR2X1 add_26_2_g196(.A (add_26_2_n_10), .B (add_26_2_n_6), .Y
       (add_26_2_n_15));
  NAND2BX1 add_26_2_g197(.AN (add_26_2_n_9), .B (add_26_2_n_2), .Y
       (add_26_2_n_14));
  NAND2BX1 add_26_2_g198(.AN (add_26_2_n_0), .B (add_26_2_n_4), .Y
       (add_26_2_n_13));
  NAND2BX1 add_26_2_g199(.AN (add_26_2_n_10), .B (add_26_2_n_5), .Y
       (add_26_2_n_12));
  NAND2X1 add_26_2_g200(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_11));
  NOR2X1 add_26_2_g201(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_10));
  NOR2X1 add_26_2_g202(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_9));
  OR2XL add_26_2_g203(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_8));
  NAND2X1 add_26_2_g204(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_7));
  NOR2X1 add_26_2_g205(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_6));
  NAND2X1 add_26_2_g206(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_5));
  NAND2X1 add_26_2_g207(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_4));
  NAND2X1 add_26_2_g208(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_3));
  NAND2X1 add_26_2_g209(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_2));
  NOR2X1 add_26_2_g210(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_1));
  NOR2X1 add_26_2_g211(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_0));
endmodule

