`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:50 CST (May 26 2023 07:18:50 UTC)

module dut_entirecomputation_alt8_1(in1, in2, in3, out1);
  input in1, in2;
  input [6:0] in3;
  output [7:0] out1;
  wire in1, in2;
  wire [6:0] in3;
  wire [7:0] out1;
  wire asc002_0_, asc002_1_, asc002_2_, asc002_3_, asc002_4_,
       asc002_5_, asc002_6_, asc002_7_;
  wire inc_add_26_2_1_n_0, inc_add_26_2_1_n_1, inc_add_26_2_1_n_2,
       inc_add_26_2_1_n_3, inc_add_26_2_1_n_4, inc_add_26_2_1_n_5,
       inc_add_26_2_1_n_6, inc_add_26_2_1_n_7;
  wire inc_add_26_2_1_n_8, inc_add_26_2_1_n_9, inc_add_26_2_1_n_11,
       inc_add_26_2_1_n_12, inc_add_26_2_1_n_15, inc_add_26_2_1_n_16,
       inc_add_26_2_1_n_19, inc_add_26_2_1_n_20;
  wire n_33, n_34, n_38, n_40, n_41, n_42;
  NOR2BX1 g65(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g66(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g67(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g68(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g69(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g70(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g71(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g72(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  MXI2XL inc_add_26_2_1_g68(.A (in3[5]), .B (inc_add_26_2_1_n_3), .S0
       (inc_add_26_2_1_n_19), .Y (asc002_5_));
  MXI2XL inc_add_26_2_1_g69(.A (in3[3]), .B (inc_add_26_2_1_n_1), .S0
       (inc_add_26_2_1_n_16), .Y (asc002_3_));
  MXI2XL inc_add_26_2_1_g70(.A (in3[6]), .B (inc_add_26_2_1_n_4), .S0
       (inc_add_26_2_1_n_20), .Y (asc002_6_));
  MXI2XL inc_add_26_2_1_g71(.A (in3[4]), .B (inc_add_26_2_1_n_0), .S0
       (n_33), .Y (asc002_4_));
  NAND2X1 inc_add_26_2_1_g72(.A (inc_add_26_2_1_n_9), .B (n_34), .Y
       (inc_add_26_2_1_n_20));
  NAND2X1 inc_add_26_2_1_g73(.A (in3[4]), .B (n_34), .Y
       (inc_add_26_2_1_n_19));
  NOR2XL inc_add_26_2_1_g74(.A (inc_add_26_2_1_n_11), .B (n_33), .Y
       (asc002_7_));
  MXI2XL inc_add_26_2_1_g75(.A (inc_add_26_2_1_n_6), .B (in3[2]), .S0
       (n_41), .Y (asc002_2_));
  NAND2X1 inc_add_26_2_1_g76(.A (in3[2]), .B (n_40), .Y
       (inc_add_26_2_1_n_16));
  NAND2X2 inc_add_26_2_1_g78(.A (inc_add_26_2_1_n_8), .B
       (inc_add_26_2_1_n_12), .Y (inc_add_26_2_1_n_15));
  MXI2XL inc_add_26_2_1_g79(.A (in3[1]), .B (inc_add_26_2_1_n_5), .S0
       (n_38), .Y (asc002_1_));
  NOR2X6 inc_add_26_2_1_g80(.A (inc_add_26_2_1_n_5), .B
       (inc_add_26_2_1_n_7), .Y (inc_add_26_2_1_n_12));
  NAND2X1 inc_add_26_2_1_g81(.A (in3[6]), .B (inc_add_26_2_1_n_9), .Y
       (inc_add_26_2_1_n_11));
  MXI2XL inc_add_26_2_1_g82(.A (inc_add_26_2_1_n_2), .B (in3[0]), .S0
       (in2), .Y (asc002_0_));
  NOR2X1 inc_add_26_2_1_g83(.A (inc_add_26_2_1_n_3), .B
       (inc_add_26_2_1_n_0), .Y (inc_add_26_2_1_n_9));
  NOR2X2 inc_add_26_2_1_g84(.A (inc_add_26_2_1_n_1), .B
       (inc_add_26_2_1_n_6), .Y (inc_add_26_2_1_n_8));
  NAND2X8 inc_add_26_2_1_g85(.A (in3[0]), .B (in2), .Y
       (inc_add_26_2_1_n_7));
  INVX1 inc_add_26_2_1_g86(.A (in3[2]), .Y (inc_add_26_2_1_n_6));
  CLKINVX2 inc_add_26_2_1_g87(.A (in3[1]), .Y (inc_add_26_2_1_n_5));
  INVX1 inc_add_26_2_1_g88(.A (in3[6]), .Y (inc_add_26_2_1_n_4));
  INVX1 inc_add_26_2_1_g89(.A (in3[5]), .Y (inc_add_26_2_1_n_3));
  INVX1 inc_add_26_2_1_g90(.A (in3[0]), .Y (inc_add_26_2_1_n_2));
  CLKINVX2 inc_add_26_2_1_g91(.A (in3[3]), .Y (inc_add_26_2_1_n_1));
  INVX1 inc_add_26_2_1_g92(.A (in3[4]), .Y (inc_add_26_2_1_n_0));
  CLKINVX1 fopt(.A (n_34), .Y (n_33));
  CLKINVX2 fopt93(.A (inc_add_26_2_1_n_15), .Y (n_34));
  BUFX2 fopt96(.A (inc_add_26_2_1_n_7), .Y (n_38));
  INVXL fopt97(.A (n_42), .Y (n_40));
  INVXL fopt98(.A (n_42), .Y (n_41));
  INVXL fopt99(.A (inc_add_26_2_1_n_12), .Y (n_42));
endmodule

