`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:45 CST (May 26 2023 07:18:45 UTC)

module dut_entirecomputation_alt2_4(in1, in2, in3, out1);
  input in1, in2, in3;
  output [1:0] out1;
  wire in1, in2, in3;
  wire [1:0] out1;
  wire asc002_0_, asc002_1_;
  NOR2BX1 g17(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g18(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  ADDHX1 inc_add_26_2_1_g14(.A (in3), .B (in2), .CO (asc002_1_), .S
       (asc002_0_));
endmodule

