`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:44 CST (May 26 2023 07:18:44 UTC)

module dut_entirecomputation_alt6_4(in1, in2, in3, out1);
  input in1, in2;
  input [4:0] in3;
  output [5:0] out1;
  wire in1, in2;
  wire [4:0] in3;
  wire [5:0] out1;
  wire asc002_0_, asc002_1_, asc002_2_, asc002_3_, asc002_4_,
       asc002_5_, inc_add_26_2_1_n_0, inc_add_26_2_1_n_2;
  wire inc_add_26_2_1_n_4, inc_add_26_2_1_n_5;
  NOR2BX1 g49(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g50(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g51(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g52(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g53(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g54(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  XNOR2X1 inc_add_26_2_1_g49(.A (in3[3]), .B (inc_add_26_2_1_n_5), .Y
       (asc002_3_));
  XNOR2X1 inc_add_26_2_1_g50(.A (in3[4]), .B (inc_add_26_2_1_n_4), .Y
       (asc002_4_));
  NOR2BX1 inc_add_26_2_1_g51(.AN (in3[4]), .B (inc_add_26_2_1_n_4), .Y
       (asc002_5_));
  XNOR2X1 inc_add_26_2_1_g52(.A (in3[2]), .B (inc_add_26_2_1_n_2), .Y
       (asc002_2_));
  NAND2BX1 inc_add_26_2_1_g53(.AN (inc_add_26_2_1_n_2), .B (in3[2]), .Y
       (inc_add_26_2_1_n_5));
  NAND3BXL inc_add_26_2_1_g54(.AN (inc_add_26_2_1_n_2), .B (in3[3]), .C
       (in3[2]), .Y (inc_add_26_2_1_n_4));
  XNOR2X1 inc_add_26_2_1_g55(.A (in3[1]), .B (inc_add_26_2_1_n_0), .Y
       (asc002_1_));
  NAND2BX1 inc_add_26_2_1_g56(.AN (inc_add_26_2_1_n_0), .B (in3[1]), .Y
       (inc_add_26_2_1_n_2));
  XOR2XL inc_add_26_2_1_g57(.A (in3[0]), .B (in2), .Y (asc002_0_));
  NAND2X1 inc_add_26_2_1_g58(.A (in3[0]), .B (in2), .Y
       (inc_add_26_2_1_n_0));
endmodule

