`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:53:21 CST (May 16 2023 12:53:21 UTC)

module dut_Equal_1U_63_1(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  NOR3X2 g50(.A (n_3), .B (n_5), .C (n_4), .Y (out1));
  NAND2X6 g53(.A (in1[0]), .B (n_1), .Y (n_5));
  NAND2X2 g51(.A (n_0), .B (n_2), .Y (n_4));
  NAND2X4 g52(.A (in1[5]), .B (in1[4]), .Y (n_3));
  CLKINVX2 g55(.A (in1[2]), .Y (n_2));
  CLKINVX12 g54(.A (in1[1]), .Y (n_1));
  INVX2 g56(.A (in1[3]), .Y (n_0));
endmodule


