`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:42:05 CST (May 24 2023 11:42:05 UTC)

module dut_Add_6Ux1U_7U_1(in2, in1, out1);
  input [5:0] in2;
  input in1;
  output [6:0] out1;
  wire [5:0] in2;
  wire in1;
  wire [6:0] out1;
  wire inc_add_23_2_1_n_0, inc_add_23_2_1_n_2, inc_add_23_2_1_n_3,
       inc_add_23_2_1_n_4, inc_add_23_2_1_n_5, inc_add_23_2_1_n_6,
       inc_add_23_2_1_n_7, inc_add_23_2_1_n_8;
  wire inc_add_23_2_1_n_9, inc_add_23_2_1_n_10, inc_add_23_2_1_n_12,
       inc_add_23_2_1_n_14, inc_add_23_2_1_n_17, n_30, n_32, n_37;
  MXI2X1 inc_add_23_2_1_g56(.A (inc_add_23_2_1_n_2), .B (in2[5]), .S0
       (inc_add_23_2_1_n_17), .Y (out1[5]));
  MXI2XL inc_add_23_2_1_g57(.A (inc_add_23_2_1_n_5), .B (in2[3]), .S0
       (inc_add_23_2_1_n_0), .Y (out1[3]));
  NOR2X2 inc_add_23_2_1_g59(.A (inc_add_23_2_1_n_6), .B
       (inc_add_23_2_1_n_14), .Y (inc_add_23_2_1_n_17));
  NOR2X1 inc_add_23_2_1_g60(.A (inc_add_23_2_1_n_9), .B (n_37), .Y
       (out1[6]));
  MXI2XL inc_add_23_2_1_g61(.A (inc_add_23_2_1_n_3), .B (in2[2]), .S0
       (n_32), .Y (out1[2]));
  NAND2X4 inc_add_23_2_1_g64(.A (inc_add_23_2_1_n_10), .B
       (inc_add_23_2_1_n_12), .Y (inc_add_23_2_1_n_14));
  MXI2XL inc_add_23_2_1_g66(.A (in2[1]), .B (inc_add_23_2_1_n_7), .S0
       (n_30), .Y (out1[1]));
  NOR2X6 inc_add_23_2_1_g67(.A (inc_add_23_2_1_n_7), .B
       (inc_add_23_2_1_n_8), .Y (inc_add_23_2_1_n_12));
  MXI2XL inc_add_23_2_1_g68(.A (inc_add_23_2_1_n_4), .B (in2[0]), .S0
       (in1), .Y (out1[0]));
  NOR2X4 inc_add_23_2_1_g69(.A (inc_add_23_2_1_n_5), .B
       (inc_add_23_2_1_n_3), .Y (inc_add_23_2_1_n_10));
  NAND2X1 inc_add_23_2_1_g70(.A (in2[5]), .B (in2[4]), .Y
       (inc_add_23_2_1_n_9));
  NAND2X8 inc_add_23_2_1_g71(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_8));
  CLKINVX2 inc_add_23_2_1_g72(.A (in2[1]), .Y (inc_add_23_2_1_n_7));
  INVX1 inc_add_23_2_1_g73(.A (in2[4]), .Y (inc_add_23_2_1_n_6));
  CLKINVX2 inc_add_23_2_1_g74(.A (in2[3]), .Y (inc_add_23_2_1_n_5));
  INVX1 inc_add_23_2_1_g75(.A (in2[0]), .Y (inc_add_23_2_1_n_4));
  CLKINVX2 inc_add_23_2_1_g76(.A (in2[2]), .Y (inc_add_23_2_1_n_3));
  INVXL inc_add_23_2_1_g77(.A (in2[5]), .Y (inc_add_23_2_1_n_2));
  MXI2XL inc_add_23_2_1_g2(.A (in2[4]), .B (inc_add_23_2_1_n_6), .S0
       (inc_add_23_2_1_n_14), .Y (out1[4]));
  NOR2BX1 inc_add_23_2_1_g78(.AN (inc_add_23_2_1_n_12), .B
       (inc_add_23_2_1_n_3), .Y (inc_add_23_2_1_n_0));
  BUFX2 fopt(.A (inc_add_23_2_1_n_8), .Y (n_30));
  BUFX2 fopt80(.A (inc_add_23_2_1_n_12), .Y (n_32));
  BUFX2 fopt83(.A (inc_add_23_2_1_n_14), .Y (n_37));
endmodule


