`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:23 CST (May 24 2023 09:40:23 UTC)

module dut_GreaterThan_5Sx2S_1U_1(in2, in1, out1);
  input [4:0] in2;
  input [1:0] in1;
  output out1;
  wire [4:0] in2;
  wire [1:0] in1;
  wire out1;
  wire gt_21_55_n_0, gt_21_55_n_1, gt_21_55_n_2, gt_21_55_n_3,
       gt_21_55_n_4, gt_21_55_n_5, gt_21_55_n_6, gt_21_55_n_7;
  wire gt_21_55_n_8, gt_21_55_n_9, gt_21_55_n_10, gt_21_55_n_11,
       gt_21_55_n_12, gt_21_55_n_13, gt_21_55_n_14, gt_21_55_n_16;
  wire gt_21_55_n_17, gt_21_55_n_18, gt_21_55_n_19, gt_21_55_n_20;
  AOI21X2 gt_21_55_g164(.A0 (gt_21_55_n_13), .A1 (gt_21_55_n_20), .B0
       (gt_21_55_n_10), .Y (out1));
  NAND2X1 gt_21_55_g165(.A (gt_21_55_n_18), .B (gt_21_55_n_19), .Y
       (gt_21_55_n_20));
  OAI21X1 gt_21_55_g166(.A0 (gt_21_55_n_14), .A1 (gt_21_55_n_17), .B0
       (gt_21_55_n_9), .Y (gt_21_55_n_19));
  NOR2X1 gt_21_55_g168(.A (gt_21_55_n_2), .B (gt_21_55_n_16), .Y
       (gt_21_55_n_17));
  AOI21X1 gt_21_55_g169(.A0 (gt_21_55_n_0), .A1 (gt_21_55_n_8), .B0
       (gt_21_55_n_6), .Y (gt_21_55_n_16));
  OAI21X1 gt_21_55_g171(.A0 (gt_21_55_n_11), .A1 (gt_21_55_n_1), .B0
       (gt_21_55_n_12), .Y (gt_21_55_n_14));
  NOR2BX1 gt_21_55_g172(.AN (gt_21_55_n_7), .B (gt_21_55_n_10), .Y
       (gt_21_55_n_13));
  NAND2BX1 gt_21_55_g174(.AN (in2[3]), .B (in1[1]), .Y (gt_21_55_n_12));
  NOR2X1 gt_21_55_g176(.A (in1[1]), .B (gt_21_55_n_3), .Y
       (gt_21_55_n_11));
  INVX1 gt_21_55_g177(.A (gt_21_55_n_10), .Y (gt_21_55_n_9));
  NOR2X2 gt_21_55_g178(.A (gt_21_55_n_4), .B (in1[1]), .Y
       (gt_21_55_n_10));
  NAND2X1 gt_21_55_g181(.A (in2[1]), .B (gt_21_55_n_5), .Y
       (gt_21_55_n_8));
  NAND2X1 gt_21_55_g182(.A (in1[1]), .B (gt_21_55_n_4), .Y
       (gt_21_55_n_7));
  NOR2X1 gt_21_55_g183(.A (gt_21_55_n_5), .B (in2[1]), .Y
       (gt_21_55_n_6));
  INVX1 gt_21_55_g185(.A (in1[1]), .Y (gt_21_55_n_5));
  INVX2 gt_21_55_g186(.A (in2[4]), .Y (gt_21_55_n_4));
  CLKINVX2 gt_21_55_g187(.A (in2[3]), .Y (gt_21_55_n_3));
  AO21XL gt_21_55_g2(.A0 (in2[2]), .A1 (gt_21_55_n_5), .B0
       (gt_21_55_n_11), .Y (gt_21_55_n_2));
  NAND2BX1 gt_21_55_g189(.AN (in2[2]), .B (in1[1]), .Y (gt_21_55_n_1));
  NAND2BX1 gt_21_55_g190(.AN (in1[0]), .B (in2[0]), .Y (gt_21_55_n_0));
  CLKBUFX2 g192(.A (gt_21_55_n_7), .Y (gt_21_55_n_18));
endmodule


