`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 21:03:41 CST (May 16 2023 13:03:41 UTC)

module dut_Equal_1U_14_4(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  NOR3BX1 g16(.AN (in1[2]), .B (in1[0]), .C (in1[1]), .Y (out1));
endmodule


