`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:33 CST (May 24 2023 11:41:33 UTC)

module dut_Add_10Ux10U_11U_4(in2, in1, out1);
  input [9:0] in2, in1;
  output [10:0] out1;
  wire [9:0] in2, in1;
  wire [10:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27,
       add_23_2_n_28, add_23_2_n_30, add_23_2_n_31, add_23_2_n_33;
  wire add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_38,
       add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_47;
  wire add_23_2_n_48;
  XNOR2X1 add_23_2_g195(.A (add_23_2_n_23), .B (add_23_2_n_48), .Y
       (out1[9]));
  XNOR2X1 add_23_2_g196(.A (add_23_2_n_25), .B (add_23_2_n_47), .Y
       (out1[7]));
  OAI221X1 add_23_2_g197(.A0 (add_23_2_n_20), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_1), .B1 (add_23_2_n_10), .C0 (add_23_2_n_5), .Y
       (out1[10]));
  OAI21X1 add_23_2_g198(.A0 (add_23_2_n_0), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_1), .Y (add_23_2_n_48));
  OAI21X1 add_23_2_g199(.A0 (add_23_2_n_14), .A1 (add_23_2_n_42), .B0
       (add_23_2_n_13), .Y (add_23_2_n_47));
  XNOR2X1 add_23_2_g200(.A (add_23_2_n_24), .B (add_23_2_n_43), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g201(.A (add_23_2_n_22), .B (add_23_2_n_42), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g202(.A (add_23_2_n_19), .B (add_23_2_n_41), .Y
       (out1[5]));
  AOI31X1 add_23_2_g203(.A0 (add_23_2_n_35), .A1 (add_23_2_n_21), .A2
       (add_23_2_n_26), .B0 (add_23_2_n_31), .Y (add_23_2_n_43));
  AOI21X1 add_23_2_g204(.A0 (add_23_2_n_26), .A1 (add_23_2_n_35), .B0
       (add_23_2_n_27), .Y (add_23_2_n_42));
  OAI21X1 add_23_2_g205(.A0 (add_23_2_n_3), .A1 (add_23_2_n_36), .B0
       (add_23_2_n_11), .Y (add_23_2_n_41));
  XNOR2X1 add_23_2_g206(.A (add_23_2_n_18), .B (add_23_2_n_36), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g207(.A (add_23_2_n_16), .B (add_23_2_n_38), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g208(.A0N (add_23_2_n_2), .A1N (add_23_2_n_33),
       .B0 (add_23_2_n_9), .Y (add_23_2_n_38));
  XNOR2X1 add_23_2_g209(.A (add_23_2_n_17), .B (add_23_2_n_33), .Y
       (out1[2]));
  INVX1 add_23_2_g210(.A (add_23_2_n_35), .Y (add_23_2_n_36));
  OAI211X1 add_23_2_g211(.A0 (add_23_2_n_9), .A1 (add_23_2_n_12), .B0
       (add_23_2_n_34), .C0 (add_23_2_n_6), .Y (add_23_2_n_35));
  NAND3BXL add_23_2_g212(.AN (add_23_2_n_12), .B (add_23_2_n_33), .C
       (add_23_2_n_2), .Y (add_23_2_n_34));
  ADDFX1 add_23_2_g213(.A (add_23_2_n_28), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_33), .S (out1[1]));
  OAI211X1 add_23_2_g214(.A0 (add_23_2_n_13), .A1 (add_23_2_n_8), .B0
       (add_23_2_n_30), .C0 (add_23_2_n_15), .Y (add_23_2_n_31));
  NAND2XL add_23_2_g215(.A (add_23_2_n_21), .B (add_23_2_n_27), .Y
       (add_23_2_n_30));
  ADDHX1 add_23_2_g216(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_28),
       .S (out1[0]));
  OAI21X1 add_23_2_g217(.A0 (add_23_2_n_11), .A1 (add_23_2_n_4), .B0
       (add_23_2_n_7), .Y (add_23_2_n_27));
  NAND2BX1 add_23_2_g218(.AN (add_23_2_n_8), .B (add_23_2_n_15), .Y
       (add_23_2_n_25));
  NOR2BX1 add_23_2_g219(.AN (add_23_2_n_1), .B (add_23_2_n_0), .Y
       (add_23_2_n_24));
  NAND2BX1 add_23_2_g220(.AN (add_23_2_n_10), .B (add_23_2_n_5), .Y
       (add_23_2_n_23));
  NOR2X1 add_23_2_g221(.A (add_23_2_n_4), .B (add_23_2_n_3), .Y
       (add_23_2_n_26));
  NOR2BX1 add_23_2_g222(.AN (add_23_2_n_13), .B (add_23_2_n_14), .Y
       (add_23_2_n_22));
  OR2XL add_23_2_g223(.A (add_23_2_n_10), .B (add_23_2_n_0), .Y
       (add_23_2_n_20));
  NAND2BX1 add_23_2_g224(.AN (add_23_2_n_4), .B (add_23_2_n_7), .Y
       (add_23_2_n_19));
  NOR2BX1 add_23_2_g225(.AN (add_23_2_n_11), .B (add_23_2_n_3), .Y
       (add_23_2_n_18));
  NAND2X1 add_23_2_g226(.A (add_23_2_n_9), .B (add_23_2_n_2), .Y
       (add_23_2_n_17));
  NAND2BX1 add_23_2_g227(.AN (add_23_2_n_12), .B (add_23_2_n_6), .Y
       (add_23_2_n_16));
  NOR2X1 add_23_2_g228(.A (add_23_2_n_8), .B (add_23_2_n_14), .Y
       (add_23_2_n_21));
  NAND2X1 add_23_2_g229(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_15));
  NOR2X1 add_23_2_g230(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g231(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_13));
  NOR2X1 add_23_2_g232(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_12));
  NAND2X1 add_23_2_g233(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_11));
  NOR2X1 add_23_2_g234(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g235(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_9));
  NOR2X1 add_23_2_g236(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g237(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g238(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g239(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g240(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g241(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_3));
  OR2XL add_23_2_g242(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  NAND2X1 add_23_2_g243(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g244(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_0));
endmodule


