`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:15:50 CST (May 16 2023 12:15:50 UTC)

module dut_Equal_14Ux11U_1U_4(in2, in1, out1);
  input [13:0] in2;
  input [10:0] in1;
  output out1;
  wire [13:0] in2;
  wire [10:0] in1;
  wire out1;
  wire eq_21_21_n_0, eq_21_21_n_1, eq_21_21_n_2, eq_21_21_n_3,
       eq_21_21_n_4, eq_21_21_n_5, eq_21_21_n_6, eq_21_21_n_7;
  wire eq_21_21_n_8, eq_21_21_n_9, eq_21_21_n_10, eq_21_21_n_11,
       eq_21_21_n_12, eq_21_21_n_13, eq_21_21_n_14;
  NOR3X1 eq_21_21_g89(.A (eq_21_21_n_14), .B (eq_21_21_n_13), .C
       (eq_21_21_n_12), .Y (out1));
  NAND4XL eq_21_21_g90(.A (eq_21_21_n_11), .B (eq_21_21_n_8), .C
       (eq_21_21_n_1), .D (eq_21_21_n_6), .Y (eq_21_21_n_14));
  NAND4XL eq_21_21_g91(.A (eq_21_21_n_3), .B (eq_21_21_n_10), .C
       (eq_21_21_n_7), .D (eq_21_21_n_5), .Y (eq_21_21_n_13));
  NAND4XL eq_21_21_g92(.A (eq_21_21_n_4), .B (eq_21_21_n_2), .C
       (eq_21_21_n_0), .D (eq_21_21_n_9), .Y (eq_21_21_n_12));
  NOR3X1 eq_21_21_g93(.A (in2[11]), .B (in2[13]), .C (in2[12]), .Y
       (eq_21_21_n_11));
  XNOR2X1 eq_21_21_g94(.A (in1[6]), .B (in2[6]), .Y (eq_21_21_n_10));
  XNOR2X1 eq_21_21_g95(.A (in1[0]), .B (in2[0]), .Y (eq_21_21_n_9));
  XNOR2X1 eq_21_21_g96(.A (in1[10]), .B (in2[10]), .Y (eq_21_21_n_8));
  XNOR2X1 eq_21_21_g97(.A (in1[5]), .B (in2[5]), .Y (eq_21_21_n_7));
  XNOR2X1 eq_21_21_g98(.A (in1[8]), .B (in2[8]), .Y (eq_21_21_n_6));
  XNOR2X1 eq_21_21_g99(.A (in1[4]), .B (in2[4]), .Y (eq_21_21_n_5));
  XNOR2X1 eq_21_21_g100(.A (in1[3]), .B (in2[3]), .Y (eq_21_21_n_4));
  XNOR2X1 eq_21_21_g101(.A (in1[7]), .B (in2[7]), .Y (eq_21_21_n_3));
  XNOR2X1 eq_21_21_g102(.A (in1[2]), .B (in2[2]), .Y (eq_21_21_n_2));
  XNOR2X1 eq_21_21_g103(.A (in1[9]), .B (in2[9]), .Y (eq_21_21_n_1));
  XNOR2X1 eq_21_21_g104(.A (in1[1]), .B (in2[1]), .Y (eq_21_21_n_0));
endmodule


