`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 21:03:38 CST (May 16 2023 13:03:38 UTC)

module dut_N_Mux_1_2_89_4(in2, ctrl1, out1);
  input in2, ctrl1;
  output out1;
  wire in2, ctrl1;
  wire out1;
  NAND2BX1 g4(.AN (in2), .B (ctrl1), .Y (out1));
endmodule


