`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:39 CST (May 24 2023 11:41:39 UTC)

module dut_Add_4Ux3U_5U_4(in2, in1, out1);
  input [3:0] in2;
  input [2:0] in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire [2:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_8, add_23_2_n_9;
  wire add_23_2_n_12;
  XOR2XL add_23_2_g67(.A (in2[3]), .B (add_23_2_n_12), .Y (out1[3]));
  OAI2BB1X1 add_23_2_g68(.A0N (add_23_2_n_1), .A1N (add_23_2_n_8), .B0
       (add_23_2_n_3), .Y (add_23_2_n_12));
  OAI32X1 add_23_2_g69(.A0 (add_23_2_n_9), .A1 (add_23_2_n_0), .A2
       (add_23_2_n_2), .B0 (add_23_2_n_0), .B1 (add_23_2_n_3), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g70(.A (add_23_2_n_4), .B (add_23_2_n_9), .Y
       (out1[2]));
  INVX1 add_23_2_g71(.A (add_23_2_n_8), .Y (add_23_2_n_9));
  ADDFX1 add_23_2_g72(.A (add_23_2_n_5), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_8), .S (out1[1]));
  ADDHX1 add_23_2_g73(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_5), .S
       (out1[0]));
  NOR2BX1 add_23_2_g74(.AN (add_23_2_n_3), .B (add_23_2_n_2), .Y
       (add_23_2_n_4));
  NAND2X1 add_23_2_g75(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_3));
  INVXL add_23_2_g76(.A (add_23_2_n_2), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g77(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  INVX1 add_23_2_g78(.A (in2[3]), .Y (add_23_2_n_0));
endmodule


