`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:00 CST (May 16 2023 12:52:00 UTC)

module dut_Add_16Ux16U_16U_4(in2, in1, out1);
  input [15:0] in2, in1;
  output [15:0] out1;
  wire [15:0] in2, in1;
  wire [15:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27,
       add_23_2_n_28, add_23_2_n_29, add_23_2_n_30, add_23_2_n_31;
  wire add_23_2_n_32, add_23_2_n_33, add_23_2_n_34, add_23_2_n_35,
       add_23_2_n_36, add_23_2_n_37, add_23_2_n_38, add_23_2_n_39;
  wire add_23_2_n_40, add_23_2_n_41, add_23_2_n_42, add_23_2_n_43,
       add_23_2_n_44, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53,
       add_23_2_n_54, add_23_2_n_56, add_23_2_n_59, add_23_2_n_60;
  wire add_23_2_n_61, add_23_2_n_62, add_23_2_n_66, add_23_2_n_67,
       add_23_2_n_68, add_23_2_n_69, add_23_2_n_74, add_23_2_n_75;
  wire add_23_2_n_76, add_23_2_n_79;
  XNOR2X1 add_23_2_g326(.A (add_23_2_n_24), .B (add_23_2_n_79), .Y
       (out1[15]));
  ADDFX1 add_23_2_g327(.A (add_23_2_n_76), .B (in1[14]), .CI (in2[14]),
       .CO (add_23_2_n_79), .S (out1[14]));
  XNOR2X1 add_23_2_g328(.A (add_23_2_n_28), .B (add_23_2_n_75), .Y
       (out1[13]));
  XNOR2X1 add_23_2_g329(.A (add_23_2_n_26), .B (add_23_2_n_74), .Y
       (out1[11]));
  OAI221X1 add_23_2_g330(.A0 (add_23_2_n_31), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_2), .B1 (add_23_2_n_0), .C0 (add_23_2_n_9), .Y
       (add_23_2_n_76));
  OAI21X1 add_23_2_g331(.A0 (add_23_2_n_4), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_2), .Y (add_23_2_n_75));
  OAI21X1 add_23_2_g332(.A0 (add_23_2_n_12), .A1 (add_23_2_n_66), .B0
       (add_23_2_n_20), .Y (add_23_2_n_74));
  XNOR2X1 add_23_2_g333(.A (add_23_2_n_29), .B (add_23_2_n_68), .Y
       (out1[9]));
  XNOR2X1 add_23_2_g334(.A (add_23_2_n_35), .B (add_23_2_n_67), .Y
       (out1[7]));
  XNOR2X1 add_23_2_g335(.A (add_23_2_n_27), .B (add_23_2_n_69), .Y
       (out1[12]));
  XNOR2X1 add_23_2_g336(.A (add_23_2_n_33), .B (add_23_2_n_66), .Y
       (out1[10]));
  AOI31X1 add_23_2_g337(.A0 (add_23_2_n_61), .A1 (add_23_2_n_39), .A2
       (add_23_2_n_32), .B0 (add_23_2_n_48), .Y (add_23_2_n_69));
  OAI21X1 add_23_2_g338(.A0 (add_23_2_n_3), .A1 (add_23_2_n_62), .B0
       (add_23_2_n_7), .Y (add_23_2_n_68));
  OAI21X1 add_23_2_g339(.A0 (add_23_2_n_15), .A1 (add_23_2_n_60), .B0
       (add_23_2_n_13), .Y (add_23_2_n_67));
  AOI21X1 add_23_2_g340(.A0 (add_23_2_n_32), .A1 (add_23_2_n_61), .B0
       (add_23_2_n_42), .Y (add_23_2_n_66));
  XNOR2X1 add_23_2_g341(.A (add_23_2_n_36), .B (add_23_2_n_62), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g342(.A (add_23_2_n_25), .B (add_23_2_n_60), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g343(.A (add_23_2_n_37), .B (add_23_2_n_59), .Y
       (out1[5]));
  INVX1 add_23_2_g344(.A (add_23_2_n_62), .Y (add_23_2_n_61));
  AOI31X1 add_23_2_g345(.A0 (add_23_2_n_53), .A1 (add_23_2_n_41), .A2
       (add_23_2_n_40), .B0 (add_23_2_n_49), .Y (add_23_2_n_62));
  AOI21X1 add_23_2_g346(.A0 (add_23_2_n_40), .A1 (add_23_2_n_53), .B0
       (add_23_2_n_43), .Y (add_23_2_n_60));
  OAI21X1 add_23_2_g347(.A0 (add_23_2_n_5), .A1 (add_23_2_n_54), .B0
       (add_23_2_n_16), .Y (add_23_2_n_59));
  XNOR2X1 add_23_2_g348(.A (add_23_2_n_34), .B (add_23_2_n_54), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g349(.A (add_23_2_n_38), .B (add_23_2_n_56), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g350(.A0N (add_23_2_n_19), .A1N (add_23_2_n_51),
       .B0 (add_23_2_n_18), .Y (add_23_2_n_56));
  XNOR2X1 add_23_2_g351(.A (add_23_2_n_30), .B (add_23_2_n_51), .Y
       (out1[2]));
  INVX1 add_23_2_g352(.A (add_23_2_n_53), .Y (add_23_2_n_54));
  OAI211X1 add_23_2_g353(.A0 (add_23_2_n_18), .A1 (add_23_2_n_21), .B0
       (add_23_2_n_52), .C0 (add_23_2_n_23), .Y (add_23_2_n_53));
  NAND3BXL add_23_2_g354(.AN (add_23_2_n_21), .B (add_23_2_n_51), .C
       (add_23_2_n_19), .Y (add_23_2_n_52));
  ADDFX1 add_23_2_g355(.A (add_23_2_n_44), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_51), .S (out1[1]));
  OAI211X1 add_23_2_g356(.A0 (add_23_2_n_13), .A1 (add_23_2_n_17), .B0
       (add_23_2_n_47), .C0 (add_23_2_n_8), .Y (add_23_2_n_49));
  OAI211X1 add_23_2_g357(.A0 (add_23_2_n_20), .A1 (add_23_2_n_14), .B0
       (add_23_2_n_46), .C0 (add_23_2_n_22), .Y (add_23_2_n_48));
  NAND2XL add_23_2_g358(.A (add_23_2_n_41), .B (add_23_2_n_43), .Y
       (add_23_2_n_47));
  NAND2XL add_23_2_g359(.A (add_23_2_n_39), .B (add_23_2_n_42), .Y
       (add_23_2_n_46));
  ADDHX1 add_23_2_g360(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_44),
       .S (out1[0]));
  OAI21X1 add_23_2_g361(.A0 (add_23_2_n_16), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_10), .Y (add_23_2_n_43));
  OAI21X1 add_23_2_g362(.A0 (add_23_2_n_7), .A1 (add_23_2_n_6), .B0
       (add_23_2_n_11), .Y (add_23_2_n_42));
  NAND2BX1 add_23_2_g363(.AN (add_23_2_n_21), .B (add_23_2_n_23), .Y
       (add_23_2_n_38));
  NOR2X1 add_23_2_g364(.A (add_23_2_n_17), .B (add_23_2_n_15), .Y
       (add_23_2_n_41));
  NOR2X1 add_23_2_g365(.A (add_23_2_n_1), .B (add_23_2_n_5), .Y
       (add_23_2_n_40));
  NAND2BX1 add_23_2_g366(.AN (add_23_2_n_1), .B (add_23_2_n_10), .Y
       (add_23_2_n_37));
  NOR2BX1 add_23_2_g367(.AN (add_23_2_n_7), .B (add_23_2_n_3), .Y
       (add_23_2_n_36));
  NOR2X1 add_23_2_g368(.A (add_23_2_n_14), .B (add_23_2_n_12), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g369(.AN (add_23_2_n_17), .B (add_23_2_n_8), .Y
       (add_23_2_n_35));
  NOR2BX1 add_23_2_g370(.AN (add_23_2_n_16), .B (add_23_2_n_5), .Y
       (add_23_2_n_34));
  NOR2BX1 add_23_2_g371(.AN (add_23_2_n_20), .B (add_23_2_n_12), .Y
       (add_23_2_n_33));
  OR2XL add_23_2_g372(.A (add_23_2_n_0), .B (add_23_2_n_4), .Y
       (add_23_2_n_31));
  NAND2X1 add_23_2_g373(.A (add_23_2_n_18), .B (add_23_2_n_19), .Y
       (add_23_2_n_30));
  NOR2X1 add_23_2_g374(.A (add_23_2_n_6), .B (add_23_2_n_3), .Y
       (add_23_2_n_32));
  NAND2BX1 add_23_2_g375(.AN (add_23_2_n_6), .B (add_23_2_n_11), .Y
       (add_23_2_n_29));
  NAND2BX1 add_23_2_g376(.AN (add_23_2_n_0), .B (add_23_2_n_9), .Y
       (add_23_2_n_28));
  NOR2BX1 add_23_2_g377(.AN (add_23_2_n_2), .B (add_23_2_n_4), .Y
       (add_23_2_n_27));
  NAND2BX1 add_23_2_g378(.AN (add_23_2_n_14), .B (add_23_2_n_22), .Y
       (add_23_2_n_26));
  NOR2BX1 add_23_2_g379(.AN (add_23_2_n_13), .B (add_23_2_n_15), .Y
       (add_23_2_n_25));
  XNOR2X1 add_23_2_g380(.A (in2[15]), .B (in1[15]), .Y (add_23_2_n_24));
  NAND2X1 add_23_2_g381(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_23));
  NAND2X1 add_23_2_g382(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_22));
  NOR2X1 add_23_2_g383(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g384(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_20));
  OR2X1 add_23_2_g385(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_19));
  NAND2X1 add_23_2_g386(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_18));
  NOR2X1 add_23_2_g387(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_17));
  NAND2X1 add_23_2_g388(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_16));
  NOR2X1 add_23_2_g389(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_15));
  NOR2X1 add_23_2_g390(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g391(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_13));
  NOR2X1 add_23_2_g392(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_12));
  NAND2X1 add_23_2_g393(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g394(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g395(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_9));
  NAND2X1 add_23_2_g396(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g397(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g398(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_6));
  NOR2X1 add_23_2_g399(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g400(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g401(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g402(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g403(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g404(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_0));
endmodule


