`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:15:48 CST (May 16 2023 12:15:48 UTC)

module dut_Equal_14Ux6U_1U_4(in2, in1, out1);
  input [13:0] in2;
  input [5:0] in1;
  output out1;
  wire [13:0] in2;
  wire [5:0] in1;
  wire out1;
  wire eq_21_21_n_0, eq_21_21_n_1, eq_21_21_n_2, eq_21_21_n_3,
       eq_21_21_n_4, eq_21_21_n_5, eq_21_21_n_6, eq_21_21_n_7;
  wire eq_21_21_n_8, eq_21_21_n_9;
  NOR2X1 eq_21_21_g45(.A (eq_21_21_n_9), .B (eq_21_21_n_8), .Y (out1));
  NAND4XL eq_21_21_g46(.A (eq_21_21_n_6), .B (eq_21_21_n_5), .C
       (eq_21_21_n_2), .D (eq_21_21_n_4), .Y (eq_21_21_n_9));
  NAND4XL eq_21_21_g47(.A (eq_21_21_n_3), .B (eq_21_21_n_7), .C
       (eq_21_21_n_1), .D (eq_21_21_n_0), .Y (eq_21_21_n_8));
  XNOR2X1 eq_21_21_g48(.A (in1[4]), .B (in2[4]), .Y (eq_21_21_n_7));
  XNOR2X1 eq_21_21_g49(.A (in1[3]), .B (in2[3]), .Y (eq_21_21_n_6));
  XNOR2X1 eq_21_21_g50(.A (in1[2]), .B (in2[2]), .Y (eq_21_21_n_5));
  XNOR2X1 eq_21_21_g51(.A (in1[0]), .B (in2[0]), .Y (eq_21_21_n_4));
  XNOR2X1 eq_21_21_g52(.A (in1[5]), .B (in2[5]), .Y (eq_21_21_n_3));
  XNOR2X1 eq_21_21_g53(.A (in1[1]), .B (in2[1]), .Y (eq_21_21_n_2));
  NOR4X1 eq_21_21_g54(.A (in2[13]), .B (in2[12]), .C (in2[11]), .D
       (in2[10]), .Y (eq_21_21_n_1));
  NOR4X1 eq_21_21_g55(.A (in2[9]), .B (in2[8]), .C (in2[7]), .D
       (in2[6]), .Y (eq_21_21_n_0));
endmodule


