`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:53:12 CST (May 16 2023 12:53:12 UTC)

module dut_Sub_3S_35_1(in1, out1);
  input [2:0] in1;
  output [2:0] out1;
  wire [2:0] in1;
  wire [2:0] out1;
  wire dec_sub_21_2_1_n_0, dec_sub_21_2_1_n_1, dec_sub_21_2_1_n_2;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  MXI2X1 dec_sub_21_2_1_g22(.A (dec_sub_21_2_1_n_1), .B (in1[2]), .S0
       (dec_sub_21_2_1_n_2), .Y (out1[2]));
  MXI2XL dec_sub_21_2_1_g23(.A (in1[0]), .B (dec_sub_21_2_1_n_0), .S0
       (in1[1]), .Y (out1[1]));
  NOR2X8 dec_sub_21_2_1_g24(.A (in1[1]), .B (in1[0]), .Y
       (dec_sub_21_2_1_n_2));
  INVX1 dec_sub_21_2_1_g25(.A (in1[2]), .Y (dec_sub_21_2_1_n_1));
  INVX1 dec_sub_21_2_1_g26(.A (in1[0]), .Y (dec_sub_21_2_1_n_0));
endmodule


