`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:53:02 CST (May 16 2023 12:53:02 UTC)

module dut_Add_6Ux6U_6U_1(in2, in1, out1);
  input [5:0] in2, in1;
  output [5:0] out1;
  wire [5:0] in2, in1;
  wire [5:0] out1;
  wire add_23_2_n_1, add_23_2_n_6, add_23_2_n_7, add_23_2_n_8,
       add_23_2_n_9, add_23_2_n_10, add_23_2_n_11, add_23_2_n_12;
  wire add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16,
       add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20;
  wire add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_25,
       add_23_2_n_27, add_23_2_n_29, n_42, n_43;
  wire n_44, n_45;
  OAI21X2 add_23_2_g100(.A0 (add_23_2_n_13), .A1 (n_43), .B0
       (add_23_2_n_8), .Y (add_23_2_n_29));
  MXI2XL add_23_2_g101(.A (add_23_2_n_21), .B (add_23_2_n_20), .S0
       (n_42), .Y (out1[4]));
  OAI21X1 add_23_2_g102(.A0 (add_23_2_n_12), .A1 (n_45), .B0
       (add_23_2_n_10), .Y (add_23_2_n_27));
  OAI2BB1X1 add_23_2_g105(.A0N (add_23_2_n_18), .A1N (add_23_2_n_23),
       .B0 (add_23_2_n_22), .Y (add_23_2_n_25));
  OAI21X4 add_23_2_g107(.A0 (add_23_2_n_6), .A1 (add_23_2_n_14), .B0
       (add_23_2_n_7), .Y (add_23_2_n_23));
  AOI2BB1X1 add_23_2_g110(.A0N (add_23_2_n_10), .A1N (add_23_2_n_9),
       .B0 (add_23_2_n_15), .Y (add_23_2_n_22));
  INVX1 add_23_2_g111(.A (add_23_2_n_20), .Y (add_23_2_n_21));
  NOR2BX1 add_23_2_g112(.AN (add_23_2_n_8), .B (add_23_2_n_13), .Y
       (add_23_2_n_20));
  NOR2X1 add_23_2_g115(.A (add_23_2_n_15), .B (add_23_2_n_9), .Y
       (add_23_2_n_19));
  NOR2X1 add_23_2_g116(.A (add_23_2_n_9), .B (add_23_2_n_12), .Y
       (add_23_2_n_18));
  NAND2X1 add_23_2_g118(.A (add_23_2_n_10), .B (add_23_2_n_11), .Y
       (add_23_2_n_17));
  XNOR2X1 add_23_2_g120(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_16));
  AND2X1 add_23_2_g122(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_15));
  NOR2X8 add_23_2_g123(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_14));
  NOR2X1 add_23_2_g124(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_13));
  INVX2 add_23_2_g125(.A (add_23_2_n_12), .Y (add_23_2_n_11));
  NOR2X4 add_23_2_g126(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_12));
  NAND2X2 add_23_2_g127(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_10));
  NOR2X4 add_23_2_g128(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_9));
  NAND2X1 add_23_2_g129(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_8));
  NAND2X2 add_23_2_g131(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_7));
  NAND2X6 add_23_2_g132(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_6));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_6), .B (add_23_2_n_1), .Y
       (out1[1]));
  XOR2XL add_23_2_g134(.A (add_23_2_n_19), .B (add_23_2_n_27), .Y
       (out1[3]));
  XNOR2X1 add_23_2_g135(.A (add_23_2_n_17), .B (n_44), .Y (out1[2]));
  XNOR2X1 add_23_2_g136(.A (add_23_2_n_16), .B (add_23_2_n_29), .Y
       (out1[5]));
  NOR2BX1 add_23_2_g137(.AN (add_23_2_n_7), .B (add_23_2_n_14), .Y
       (add_23_2_n_1));
  XOR2XL add_23_2_g138(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_43), .Y (n_42));
  CLKINVX1 fopt139(.A (add_23_2_n_25), .Y (n_43));
  INVXL fopt140(.A (n_45), .Y (n_44));
  CLKINVX1 fopt141(.A (add_23_2_n_23), .Y (n_45));
endmodule


