`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:40 CST (May 24 2023 11:41:40 UTC)

module dut_N_Mux_7_2_51_4(in2, ctrl1, out1);
  input [6:0] in2;
  input ctrl1;
  output [6:0] out1;
  wire [6:0] in2;
  wire ctrl1;
  wire [6:0] out1;
  NOR2BX1 g64(.AN (in2[6]), .B (ctrl1), .Y (out1[6]));
  NOR2BX1 g65(.AN (in2[5]), .B (ctrl1), .Y (out1[5]));
  NOR2BX1 g68(.AN (in2[4]), .B (ctrl1), .Y (out1[4]));
  NOR2BX1 g67(.AN (in2[1]), .B (ctrl1), .Y (out1[1]));
  NOR2BX1 g69(.AN (in2[2]), .B (ctrl1), .Y (out1[2]));
  NOR2BX1 g66(.AN (in2[3]), .B (ctrl1), .Y (out1[3]));
  NOR2BX1 g70(.AN (in2[0]), .B (ctrl1), .Y (out1[0]));
endmodule


