`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:12 CST (May 24 2023 09:40:12 UTC)

module dut_GreaterThan_5Sx2S_1U_4(in2, in1, out1);
  input [4:0] in2;
  input [1:0] in1;
  output out1;
  wire [4:0] in2;
  wire [1:0] in1;
  wire out1;
  wire gt_21_55_n_0, gt_21_55_n_1, gt_21_55_n_2, gt_21_55_n_3,
       gt_21_55_n_4, gt_21_55_n_5, gt_21_55_n_6, gt_21_55_n_7;
  wire gt_21_55_n_8, gt_21_55_n_9, gt_21_55_n_10, gt_21_55_n_11,
       gt_21_55_n_12, gt_21_55_n_13, gt_21_55_n_14;
  NOR2X1 gt_21_55_g159(.A (gt_21_55_n_5), .B (gt_21_55_n_14), .Y
       (out1));
  NOR3X1 gt_21_55_g160(.A (gt_21_55_n_13), .B (gt_21_55_n_3), .C
       (gt_21_55_n_5), .Y (gt_21_55_n_14));
  AOI221X1 gt_21_55_g161(.A0 (gt_21_55_n_6), .A1 (gt_21_55_n_10), .B0
       (gt_21_55_n_6), .B1 (gt_21_55_n_12), .C0 (gt_21_55_n_10), .Y
       (gt_21_55_n_13));
  OAI211X1 gt_21_55_g162(.A0 (gt_21_55_n_1), .A1 (in2[3]), .B0
       (gt_21_55_n_11), .C0 (gt_21_55_n_9), .Y (gt_21_55_n_12));
  OAI211X1 gt_21_55_g163(.A0 (gt_21_55_n_2), .A1 (gt_21_55_n_8), .B0
       (gt_21_55_n_7), .C0 (gt_21_55_n_4), .Y (gt_21_55_n_11));
  AO21XL gt_21_55_g164(.A0 (gt_21_55_n_6), .A1 (gt_21_55_n_3), .B0
       (gt_21_55_n_3), .Y (gt_21_55_n_10));
  NAND3BXL gt_21_55_g165(.AN (in2[2]), .B (gt_21_55_n_7), .C (in1[1]),
       .Y (gt_21_55_n_9));
  AOI22X1 gt_21_55_g166(.A0 (in2[0]), .A1 (gt_21_55_n_0), .B0 (in2[1]),
       .B1 (gt_21_55_n_1), .Y (gt_21_55_n_8));
  NAND2X1 gt_21_55_g167(.A (in2[3]), .B (gt_21_55_n_1), .Y
       (gt_21_55_n_7));
  INVX1 gt_21_55_g168(.A (gt_21_55_n_6), .Y (gt_21_55_n_5));
  NAND2X1 gt_21_55_g169(.A (in2[4]), .B (gt_21_55_n_1), .Y
       (gt_21_55_n_6));
  NAND2X1 gt_21_55_g170(.A (in2[2]), .B (gt_21_55_n_1), .Y
       (gt_21_55_n_4));
  NOR2X1 gt_21_55_g171(.A (gt_21_55_n_1), .B (in2[4]), .Y
       (gt_21_55_n_3));
  NOR2X1 gt_21_55_g172(.A (gt_21_55_n_1), .B (in2[1]), .Y
       (gt_21_55_n_2));
  INVX1 gt_21_55_g173(.A (in1[1]), .Y (gt_21_55_n_1));
  INVX1 gt_21_55_g174(.A (in1[0]), .Y (gt_21_55_n_0));
endmodule


