`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:29 CST (May 24 2023 11:41:29 UTC)

module dut_Add_7Ux5U_8U_4(in2, in1, out1);
  input [6:0] in2;
  input [4:0] in1;
  output [7:0] out1;
  wire [6:0] in2;
  wire [4:0] in1;
  wire [7:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_13,
       add_23_2_n_14, add_23_2_n_15, add_23_2_n_17, add_23_2_n_20;
  wire add_23_2_n_21;
  XNOR2X1 add_23_2_g127(.A (in2[6]), .B (add_23_2_n_20), .Y (out1[6]));
  XOR2XL add_23_2_g128(.A (in2[5]), .B (add_23_2_n_21), .Y (out1[5]));
  NOR2BX1 add_23_2_g129(.AN (in2[6]), .B (add_23_2_n_20), .Y (out1[7]));
  OAI2BB1X1 add_23_2_g130(.A0N (add_23_2_n_1), .A1N (add_23_2_n_15),
       .B0 (add_23_2_n_6), .Y (add_23_2_n_21));
  AOI32X1 add_23_2_g131(.A0 (add_23_2_n_15), .A1 (in2[5]), .A2
       (add_23_2_n_1), .B0 (in2[5]), .B1 (add_23_2_n_5), .Y
       (add_23_2_n_20));
  XNOR2X1 add_23_2_g132(.A (add_23_2_n_8), .B (add_23_2_n_15), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g133(.A (add_23_2_n_7), .B (add_23_2_n_17), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g134(.A0N (add_23_2_n_0), .A1N (add_23_2_n_13),
       .B0 (add_23_2_n_4), .Y (add_23_2_n_17));
  XNOR2X1 add_23_2_g135(.A (add_23_2_n_9), .B (add_23_2_n_13), .Y
       (out1[2]));
  OAI211X1 add_23_2_g136(.A0 (add_23_2_n_4), .A1 (add_23_2_n_3), .B0
       (add_23_2_n_14), .C0 (add_23_2_n_2), .Y (add_23_2_n_15));
  NAND3BXL add_23_2_g137(.AN (add_23_2_n_3), .B (add_23_2_n_13), .C
       (add_23_2_n_0), .Y (add_23_2_n_14));
  ADDFX1 add_23_2_g138(.A (add_23_2_n_10), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_13), .S (out1[1]));
  ADDHX1 add_23_2_g139(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_10),
       .S (out1[0]));
  NAND2X1 add_23_2_g140(.A (add_23_2_n_4), .B (add_23_2_n_0), .Y
       (add_23_2_n_9));
  NAND2X1 add_23_2_g141(.A (add_23_2_n_6), .B (add_23_2_n_1), .Y
       (add_23_2_n_8));
  NAND2BX1 add_23_2_g142(.AN (add_23_2_n_3), .B (add_23_2_n_2), .Y
       (add_23_2_n_7));
  INVX1 add_23_2_g143(.A (add_23_2_n_6), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g144(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g145(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g146(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g147(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_2));
  OR2X1 add_23_2_g148(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_1));
  OR2X1 add_23_2_g149(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_0));
endmodule


