`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:20 CST (May 16 2023 12:52:20 UTC)

module dut_Sub_3S_35_4(in1, out1);
  input [2:0] in1;
  output [2:0] out1;
  wire [2:0] in1;
  wire [2:0] out1;
  wire dec_sub_21_2_1_n_0;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XOR2XL dec_sub_21_2_1_g22(.A (in1[2]), .B (dec_sub_21_2_1_n_0), .Y
       (out1[2]));
  XNOR2X1 dec_sub_21_2_1_g23(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NOR2X1 dec_sub_21_2_1_g24(.A (in1[1]), .B (in1[0]), .Y
       (dec_sub_21_2_1_n_0));
endmodule


