`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:42:04 CST (May 24 2023 11:42:04 UTC)

module dut_N_Mux_7_2_51_1(in2, ctrl1, out1);
  input [6:0] in2;
  input ctrl1;
  output [6:0] out1;
  wire [6:0] in2;
  wire ctrl1;
  wire [6:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  NOR2X4 g64(.A (ctrl1), .B (n_6), .Y (out1[6]));
  NOR2X4 g68(.A (ctrl1), .B (n_0), .Y (out1[4]));
  NOR2X4 g66(.A (ctrl1), .B (n_2), .Y (out1[3]));
  NOR2X4 g70(.A (ctrl1), .B (n_5), .Y (out1[0]));
  NOR2X4 g67(.A (ctrl1), .B (n_1), .Y (out1[1]));
  NOR2X4 g69(.A (ctrl1), .B (n_3), .Y (out1[2]));
  NOR2X4 g65(.A (ctrl1), .B (n_4), .Y (out1[5]));
  CLKINVX12 g71(.A (in2[6]), .Y (n_6));
  CLKINVX12 g75(.A (in2[0]), .Y (n_5));
  CLKINVX12 g73(.A (in2[5]), .Y (n_4));
  CLKINVX12 g74(.A (in2[2]), .Y (n_3));
  CLKINVX12 g72(.A (in2[3]), .Y (n_2));
  CLKINVX12 g76(.A (in2[1]), .Y (n_1));
  CLKINVX12 g77(.A (in2[4]), .Y (n_0));
endmodule


