`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:55 CST (May 24 2023 11:41:55 UTC)

module dut_Add_9Ux9U_10U_1(in2, in1, out1);
  input [8:0] in2, in1;
  output [9:0] out1;
  wire [8:0] in2, in1;
  wire [9:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_7, add_23_2_n_9,
       add_23_2_n_10, add_23_2_n_12, add_23_2_n_13, add_23_2_n_14;
  wire add_23_2_n_15, add_23_2_n_16, add_23_2_n_17, add_23_2_n_18,
       add_23_2_n_19, add_23_2_n_20, add_23_2_n_21, add_23_2_n_22;
  wire add_23_2_n_23, add_23_2_n_24, add_23_2_n_25, add_23_2_n_26,
       add_23_2_n_27, add_23_2_n_28, add_23_2_n_29, add_23_2_n_30;
  wire add_23_2_n_31, add_23_2_n_32, add_23_2_n_33, add_23_2_n_34,
       add_23_2_n_35, add_23_2_n_36, add_23_2_n_37, add_23_2_n_38;
  wire add_23_2_n_39, add_23_2_n_40, add_23_2_n_41, add_23_2_n_42,
       add_23_2_n_43, add_23_2_n_44, add_23_2_n_45, add_23_2_n_46;
  wire add_23_2_n_47, add_23_2_n_48, add_23_2_n_49, add_23_2_n_50,
       add_23_2_n_51, add_23_2_n_52, add_23_2_n_53, add_23_2_n_54;
  wire add_23_2_n_55, add_23_2_n_56, add_23_2_n_57, add_23_2_n_58,
       add_23_2_n_59, add_23_2_n_60, add_23_2_n_61, n_84;
  wire n_85, n_86, n_88, n_90, n_93, n_94, n_97, n_99;
  MXI2XL add_23_2_g183(.A (add_23_2_n_31), .B (add_23_2_n_32), .S0
       (add_23_2_n_59), .Y (out1[7]));
  MXI2XL add_23_2_g185(.A (add_23_2_n_40), .B (add_23_2_n_41), .S0
       (add_23_2_n_60), .Y (out1[5]));
  OAI21X1 add_23_2_g186(.A0 (add_23_2_n_18), .A1 (add_23_2_n_61), .B0
       (add_23_2_n_29), .Y (out1[9]));
  MXI2X1 add_23_2_g187(.A (add_23_2_n_33), .B (add_23_2_n_34), .S0
       (add_23_2_n_61), .Y (out1[8]));
  NOR2X1 add_23_2_g188(.A (add_23_2_n_50), .B (add_23_2_n_56), .Y
       (add_23_2_n_61));
  NOR2BX1 add_23_2_g190(.AN (add_23_2_n_14), .B (add_23_2_n_57), .Y
       (add_23_2_n_60));
  NOR2X1 add_23_2_g193(.A (add_23_2_n_51), .B (add_23_2_n_55), .Y
       (add_23_2_n_59));
  NOR2X2 add_23_2_g194(.A (n_93), .B (add_23_2_n_53), .Y
       (add_23_2_n_58));
  NOR2X1 add_23_2_g195(.A (add_23_2_n_24), .B (add_23_2_n_53), .Y
       (add_23_2_n_57));
  NOR2X1 add_23_2_g196(.A (add_23_2_n_46), .B (add_23_2_n_53), .Y
       (add_23_2_n_56));
  NOR2X1 add_23_2_g197(.A (add_23_2_n_47), .B (add_23_2_n_53), .Y
       (add_23_2_n_55));
  NOR2BX1 add_23_2_g198(.AN (add_23_2_n_25), .B (add_23_2_n_2), .Y
       (add_23_2_n_54));
  NOR2X4 add_23_2_g200(.A (add_23_2_n_45), .B (add_23_2_n_52), .Y
       (add_23_2_n_53));
  NOR2X2 add_23_2_g202(.A (add_23_2_n_1), .B (add_23_2_n_49), .Y
       (add_23_2_n_52));
  OAI21X1 add_23_2_g203(.A0 (add_23_2_n_13), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_16), .Y (add_23_2_n_51));
  OAI21X1 add_23_2_g204(.A0 (add_23_2_n_39), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_44), .Y (add_23_2_n_50));
  NOR2X2 add_23_2_g205(.A (add_23_2_n_19), .B (add_23_2_n_48), .Y
       (add_23_2_n_49));
  NOR2X2 add_23_2_g207(.A (add_23_2_n_17), .B (add_23_2_n_21), .Y
       (add_23_2_n_48));
  OR2XL add_23_2_g209(.A (add_23_2_n_13), .B (add_23_2_n_36), .Y
       (add_23_2_n_47));
  OR2XL add_23_2_g210(.A (add_23_2_n_39), .B (add_23_2_n_36), .Y
       (add_23_2_n_46));
  OAI21X2 add_23_2_g211(.A0 (add_23_2_n_25), .A1 (add_23_2_n_23), .B0
       (add_23_2_n_27), .Y (add_23_2_n_45));
  OA21X1 add_23_2_g212(.A0 (add_23_2_n_16), .A1 (add_23_2_n_22), .B0
       (add_23_2_n_28), .Y (add_23_2_n_44));
  AOI2BB1X1 add_23_2_g214(.A0N (add_23_2_n_14), .A1N (add_23_2_n_15),
       .B0 (add_23_2_n_20), .Y (add_23_2_n_43));
  INVX1 add_23_2_g216(.A (add_23_2_n_40), .Y (add_23_2_n_41));
  NAND2BX1 add_23_2_g219(.AN (add_23_2_n_24), .B (add_23_2_n_14), .Y
       (add_23_2_n_42));
  NOR2X1 add_23_2_g220(.A (add_23_2_n_20), .B (n_88), .Y
       (add_23_2_n_40));
  OR2XL add_23_2_g221(.A (add_23_2_n_22), .B (add_23_2_n_13), .Y
       (add_23_2_n_39));
  NOR2BX1 add_23_2_g222(.AN (add_23_2_n_27), .B (n_99), .Y
       (add_23_2_n_38));
  NAND2X1 add_23_2_g223(.A (add_23_2_n_25), .B (add_23_2_n_26), .Y
       (add_23_2_n_37));
  OR2X1 add_23_2_g224(.A (add_23_2_n_15), .B (add_23_2_n_24), .Y
       (add_23_2_n_36));
  INVX1 add_23_2_g226(.A (add_23_2_n_33), .Y (add_23_2_n_34));
  INVX1 add_23_2_g227(.A (add_23_2_n_31), .Y (add_23_2_n_32));
  NAND2BX1 add_23_2_g230(.AN (add_23_2_n_13), .B (add_23_2_n_16), .Y
       (add_23_2_n_35));
  NOR2BX1 add_23_2_g231(.AN (add_23_2_n_29), .B (add_23_2_n_18), .Y
       (add_23_2_n_33));
  NOR2BX1 add_23_2_g232(.AN (add_23_2_n_28), .B (n_97), .Y
       (add_23_2_n_31));
  NOR2X1 add_23_2_g233(.A (add_23_2_n_19), .B (add_23_2_n_21), .Y
       (add_23_2_n_30));
  NAND2X1 add_23_2_g236(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_29));
  NAND2X1 add_23_2_g237(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g238(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_27));
  NAND2X4 add_23_2_g239(.A (n_90), .B (add_23_2_n_10), .Y
       (add_23_2_n_26));
  NAND2X1 add_23_2_g240(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g241(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_24));
  NOR2X8 add_23_2_g242(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_23));
  NOR2X2 add_23_2_g243(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_22));
  NOR2X8 add_23_2_g244(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_21));
  AND2X1 add_23_2_g245(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_20));
  NOR2X2 add_23_2_g246(.A (add_23_2_n_12), .B (add_23_2_n_9), .Y
       (add_23_2_n_19));
  NOR2X1 add_23_2_g247(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_18));
  NAND2X4 add_23_2_g248(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_17));
  NAND2X1 add_23_2_g249(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_16));
  NOR2X2 add_23_2_g250(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g251(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_14));
  NOR2X1 add_23_2_g252(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_13));
  CLKINVX2 add_23_2_g253(.A (in2[1]), .Y (add_23_2_n_12));
  CLKINVX2 add_23_2_g255(.A (in1[2]), .Y (add_23_2_n_10));
  CLKINVX2 add_23_2_g256(.A (in1[1]), .Y (add_23_2_n_9));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_17), .B (add_23_2_n_30), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g258(.AN (add_23_2_n_43), .B (add_23_2_n_58), .Y
       (add_23_2_n_7));
  CLKXOR2X1 add_23_2_g259(.A (add_23_2_n_42), .B (n_94), .Y (out1[4]));
  XNOR2XL add_23_2_g260(.A (add_23_2_n_38), .B (add_23_2_n_54), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g261(.A (add_23_2_n_37), .B (n_84), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g262(.A (add_23_2_n_35), .B (add_23_2_n_7), .Y
       (out1[6]));
  NOR2BX1 add_23_2_g263(.AN (add_23_2_n_26), .B (n_85), .Y
       (add_23_2_n_2));
  NAND2BX1 add_23_2_g264(.AN (add_23_2_n_23), .B (add_23_2_n_26), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g265(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_86), .Y (n_84));
  INVXL fopt266(.A (n_86), .Y (n_85));
  INVXL fopt267(.A (add_23_2_n_49), .Y (n_86));
  BUFX2 fopt268(.A (add_23_2_n_15), .Y (n_88));
  CLKINVX3 fopt269(.A (in2[2]), .Y (n_90));
  BUFX3 fopt270(.A (add_23_2_n_36), .Y (n_93));
  BUFX2 fopt271(.A (add_23_2_n_53), .Y (n_94));
  BUFX2 fopt272(.A (add_23_2_n_22), .Y (n_97));
  BUFX2 fopt273(.A (add_23_2_n_23), .Y (n_99));
endmodule


