`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:34 CST (May 24 2023 11:41:34 UTC)

module dut_Add_9Ux9U_10U_4(in2, in1, out1);
  input [8:0] in2, in1;
  output [9:0] out1;
  wire [8:0] in2, in1;
  wire [9:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29,
       add_23_2_n_31, add_23_2_n_32, add_23_2_n_35, add_23_2_n_36;
  wire add_23_2_n_37, add_23_2_n_40;
  XNOR2X1 add_23_2_g171(.A (add_23_2_n_12), .B (add_23_2_n_40), .Y
       (out1[7]));
  ADDFX1 add_23_2_g172(.A (add_23_2_n_37), .B (in1[8]), .CI (in2[8]),
       .CO (out1[9]), .S (out1[8]));
  OAI21X1 add_23_2_g173(.A0 (add_23_2_n_6), .A1 (add_23_2_n_36), .B0
       (add_23_2_n_7), .Y (add_23_2_n_40));
  XNOR2X1 add_23_2_g174(.A (add_23_2_n_18), .B (add_23_2_n_36), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g175(.A (add_23_2_n_16), .B (add_23_2_n_35), .Y
       (out1[5]));
  NAND2BX1 add_23_2_g176(.AN (add_23_2_n_24), .B (add_23_2_n_32), .Y
       (add_23_2_n_37));
  AOI21X1 add_23_2_g177(.A0 (add_23_2_n_17), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_20), .Y (add_23_2_n_36));
  OAI21X1 add_23_2_g178(.A0 (add_23_2_n_9), .A1 (add_23_2_n_29), .B0
       (add_23_2_n_2), .Y (add_23_2_n_35));
  XNOR2X1 add_23_2_g179(.A (add_23_2_n_14), .B (add_23_2_n_29), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g180(.A (add_23_2_n_13), .B (add_23_2_n_31), .Y
       (out1[3]));
  NAND3X1 add_23_2_g181(.A (add_23_2_n_28), .B (add_23_2_n_15), .C
       (add_23_2_n_17), .Y (add_23_2_n_32));
  OAI2BB1X1 add_23_2_g182(.A0N (add_23_2_n_8), .A1N (add_23_2_n_26),
       .B0 (add_23_2_n_3), .Y (add_23_2_n_31));
  XNOR2X1 add_23_2_g183(.A (add_23_2_n_19), .B (add_23_2_n_26), .Y
       (out1[2]));
  INVX1 add_23_2_g184(.A (add_23_2_n_28), .Y (add_23_2_n_29));
  OAI211X1 add_23_2_g185(.A0 (add_23_2_n_3), .A1 (add_23_2_n_0), .B0
       (add_23_2_n_27), .C0 (add_23_2_n_4), .Y (add_23_2_n_28));
  NAND3BXL add_23_2_g186(.AN (add_23_2_n_0), .B (add_23_2_n_26), .C
       (add_23_2_n_8), .Y (add_23_2_n_27));
  ADDFX1 add_23_2_g187(.A (add_23_2_n_21), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_26), .S (out1[1]));
  OAI211X1 add_23_2_g188(.A0 (add_23_2_n_7), .A1 (add_23_2_n_10), .B0
       (add_23_2_n_23), .C0 (add_23_2_n_5), .Y (add_23_2_n_24));
  NAND2XL add_23_2_g189(.A (add_23_2_n_15), .B (add_23_2_n_20), .Y
       (add_23_2_n_23));
  ADDHX1 add_23_2_g190(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_21),
       .S (out1[0]));
  OAI21X1 add_23_2_g191(.A0 (add_23_2_n_2), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_11), .Y (add_23_2_n_20));
  NAND2X1 add_23_2_g192(.A (add_23_2_n_3), .B (add_23_2_n_8), .Y
       (add_23_2_n_19));
  NOR2BX1 add_23_2_g193(.AN (add_23_2_n_7), .B (add_23_2_n_6), .Y
       (add_23_2_n_18));
  NOR2X1 add_23_2_g194(.A (add_23_2_n_1), .B (add_23_2_n_9), .Y
       (add_23_2_n_17));
  NAND2BX1 add_23_2_g195(.AN (add_23_2_n_1), .B (add_23_2_n_11), .Y
       (add_23_2_n_16));
  NOR2X1 add_23_2_g196(.A (add_23_2_n_10), .B (add_23_2_n_6), .Y
       (add_23_2_n_15));
  NOR2BX1 add_23_2_g197(.AN (add_23_2_n_2), .B (add_23_2_n_9), .Y
       (add_23_2_n_14));
  NAND2BX1 add_23_2_g198(.AN (add_23_2_n_0), .B (add_23_2_n_4), .Y
       (add_23_2_n_13));
  NAND2BX1 add_23_2_g199(.AN (add_23_2_n_10), .B (add_23_2_n_5), .Y
       (add_23_2_n_12));
  NAND2X1 add_23_2_g200(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_11));
  NOR2X1 add_23_2_g201(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g202(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_9));
  OR2XL add_23_2_g203(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g204(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g205(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g206(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g207(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g208(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g209(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g210(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g211(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_0));
endmodule


