`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:30 CST (May 16 2023 12:52:30 UTC)

module dut_Equal_1U_62_4(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR4X1 g24(.A (in1[1]), .B (in1[0]), .C (n_0), .D (n_1), .Y (out1));
  OR2XL g25(.A (in1[3]), .B (in1[2]), .Y (n_1));
  NAND2X1 g26(.A (in1[5]), .B (in1[4]), .Y (n_0));
endmodule


