`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:12 CST (May 24 2023 09:40:12 UTC)

module dut_Add_4U_6_4(in1, out1);
  input [2:0] in1;
  output [3:0] out1;
  wire [2:0] in1;
  wire [3:0] out1;
  wire inc_add_21_2_1_n_0;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  ADDHX1 inc_add_21_2_1_g27(.A (in1[2]), .B (inc_add_21_2_1_n_0), .CO
       (out1[3]), .S (out1[2]));
  ADDHX1 inc_add_21_2_1_g28(.A (in1[1]), .B (in1[0]), .CO
       (inc_add_21_2_1_n_0), .S (out1[1]));
endmodule


