`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:31 CST (May 24 2023 11:41:31 UTC)

module dut_Add_7Ux1U_8U_4(in2, in1, out1);
  input [6:0] in2;
  input in1;
  output [7:0] out1;
  wire [6:0] in2;
  wire in1;
  wire [7:0] out1;
  wire inc_add_23_2_1_n_0, inc_add_23_2_1_n_2, inc_add_23_2_1_n_4,
       inc_add_23_2_1_n_5, inc_add_23_2_1_n_7, inc_add_23_2_1_n_8;
  XNOR2X1 inc_add_23_2_1_g65(.A (in2[5]), .B (inc_add_23_2_1_n_8), .Y
       (out1[5]));
  XNOR2X1 inc_add_23_2_1_g66(.A (in2[3]), .B (inc_add_23_2_1_n_5), .Y
       (out1[3]));
  XNOR2X1 inc_add_23_2_1_g67(.A (in2[6]), .B (inc_add_23_2_1_n_7), .Y
       (out1[6]));
  NOR2BX1 inc_add_23_2_1_g68(.AN (in2[6]), .B (inc_add_23_2_1_n_7), .Y
       (out1[7]));
  XNOR2X1 inc_add_23_2_1_g69(.A (in2[4]), .B (inc_add_23_2_1_n_4), .Y
       (out1[4]));
  NAND2BX1 inc_add_23_2_1_g70(.AN (inc_add_23_2_1_n_4), .B (in2[4]), .Y
       (inc_add_23_2_1_n_8));
  NAND3BXL inc_add_23_2_1_g71(.AN (inc_add_23_2_1_n_4), .B (in2[5]), .C
       (in2[4]), .Y (inc_add_23_2_1_n_7));
  XNOR2X1 inc_add_23_2_1_g72(.A (in2[2]), .B (inc_add_23_2_1_n_2), .Y
       (out1[2]));
  NAND2BX1 inc_add_23_2_1_g73(.AN (inc_add_23_2_1_n_2), .B (in2[2]), .Y
       (inc_add_23_2_1_n_5));
  NAND3BXL inc_add_23_2_1_g74(.AN (inc_add_23_2_1_n_2), .B (in2[3]), .C
       (in2[2]), .Y (inc_add_23_2_1_n_4));
  XNOR2X1 inc_add_23_2_1_g75(.A (in2[1]), .B (inc_add_23_2_1_n_0), .Y
       (out1[1]));
  NAND2BX1 inc_add_23_2_1_g76(.AN (inc_add_23_2_1_n_0), .B (in2[1]), .Y
       (inc_add_23_2_1_n_2));
  XOR2XL inc_add_23_2_1_g77(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2X1 inc_add_23_2_1_g78(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_0));
endmodule


