`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:53 CST (May 26 2023 07:18:53 UTC)

module dut_entirecomputation_alt14_1(in1, in2, in3, out1);
  input in1;
  input [7:0] in2, in3;
  output [8:0] out1;
  wire in1;
  wire [7:0] in2, in3;
  wire [8:0] out1;
  wire add_26_2_n_0, add_26_2_n_2, add_26_2_n_3, add_26_2_n_4,
       add_26_2_n_5, add_26_2_n_6, add_26_2_n_7, add_26_2_n_8;
  wire add_26_2_n_9, add_26_2_n_10, add_26_2_n_11, add_26_2_n_12,
       add_26_2_n_13, add_26_2_n_14, add_26_2_n_15, add_26_2_n_16;
  wire add_26_2_n_17, add_26_2_n_18, add_26_2_n_19, add_26_2_n_21,
       add_26_2_n_22, add_26_2_n_23, add_26_2_n_24, add_26_2_n_25;
  wire add_26_2_n_26, add_26_2_n_27, add_26_2_n_28, add_26_2_n_29,
       add_26_2_n_30, add_26_2_n_31, add_26_2_n_32, add_26_2_n_33;
  wire add_26_2_n_34, add_26_2_n_35, add_26_2_n_36, add_26_2_n_37,
       add_26_2_n_38, add_26_2_n_39, add_26_2_n_40, add_26_2_n_41;
  wire add_26_2_n_42, add_26_2_n_43, add_26_2_n_44, add_26_2_n_46,
       add_26_2_n_47, add_26_2_n_48, add_26_2_n_49, add_26_2_n_50;
  wire add_26_2_n_51, add_26_2_n_52, add_26_2_n_53, add_26_2_n_54,
       add_26_2_n_57, add_26_2_n_58, asc002_0_, asc002_1_;
  wire asc002_2_, asc002_3_, asc002_4_, asc002_5_, asc002_6_,
       asc002_7_, asc002_8_, n_0;
  wire n_1, n_79, n_80, n_81, n_84, n_86, n_87, n_88;
  NOR2BX1 g73(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g74(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g75(.AN (n_1), .B (n_0), .Y (out1[8]));
  NOR2BX1 g76(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g77(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g78(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g79(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g80(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g81(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  INVXL g82(.A (in1), .Y (n_1));
  INVX1 g83(.A (asc002_8_), .Y (n_0));
  MXI2XL add_26_2_g168(.A (add_26_2_n_24), .B (add_26_2_n_25), .S0
       (add_26_2_n_54), .Y (asc002_7_));
  MXI2XL add_26_2_g169(.A (add_26_2_n_35), .B (add_26_2_n_36), .S0
       (add_26_2_n_58), .Y (asc002_5_));
  MXI2XL add_26_2_g170(.A (add_26_2_n_23), .B (add_26_2_n_22), .S0
       (add_26_2_n_57), .Y (asc002_6_));
  OAI21X1 add_26_2_g171(.A0 (add_26_2_n_42), .A1 (n_79), .B0
       (add_26_2_n_47), .Y (asc002_8_));
  AOI2BB1XL add_26_2_g172(.A0N (add_26_2_n_5), .A1N (add_26_2_n_51),
       .B0 (add_26_2_n_8), .Y (add_26_2_n_58));
  AOI2BB1XL add_26_2_g173(.A0N (add_26_2_n_30), .A1N (add_26_2_n_51),
       .B0 (add_26_2_n_39), .Y (add_26_2_n_57));
  MXI2XL add_26_2_g174(.A (add_26_2_n_33), .B (add_26_2_n_34), .S0
       (n_80), .Y (asc002_4_));
  MXI2XL add_26_2_g175(.A (add_26_2_n_31), .B (add_26_2_n_32), .S0
       (add_26_2_n_52), .Y (asc002_3_));
  NOR2X1 add_26_2_g176(.A (add_26_2_n_48), .B (add_26_2_n_53), .Y
       (add_26_2_n_54));
  NOR2X1 add_26_2_g177(.A (add_26_2_n_41), .B (add_26_2_n_51), .Y
       (add_26_2_n_53));
  NOR2BX1 add_26_2_g178(.AN (add_26_2_n_14), .B (add_26_2_n_50), .Y
       (add_26_2_n_52));
  NOR2X2 add_26_2_g180(.A (add_26_2_n_37), .B (add_26_2_n_49), .Y
       (add_26_2_n_51));
  NOR2X1 add_26_2_g181(.A (add_26_2_n_10), .B (n_86), .Y
       (add_26_2_n_50));
  NOR2X2 add_26_2_g182(.A (add_26_2_n_27), .B (add_26_2_n_46), .Y
       (add_26_2_n_49));
  OAI21X1 add_26_2_g183(.A0 (add_26_2_n_3), .A1 (add_26_2_n_38), .B0
       (add_26_2_n_13), .Y (add_26_2_n_48));
  AOI21X1 add_26_2_g184(.A0 (add_26_2_n_26), .A1 (add_26_2_n_39), .B0
       (add_26_2_n_40), .Y (add_26_2_n_47));
  NOR2X2 add_26_2_g185(.A (add_26_2_n_0), .B (add_26_2_n_44), .Y
       (add_26_2_n_46));
  MXI2XL add_26_2_g186(.A (add_26_2_n_4), .B (add_26_2_n_43), .S0
       (add_26_2_n_19), .Y (asc002_1_));
  NOR2X2 add_26_2_g187(.A (add_26_2_n_4), .B (add_26_2_n_11), .Y
       (add_26_2_n_44));
  INVXL add_26_2_g188(.A (add_26_2_n_4), .Y (add_26_2_n_43));
  NAND2X1 add_26_2_g189(.A (add_26_2_n_26), .B (add_26_2_n_29), .Y
       (add_26_2_n_42));
  NAND2BX1 add_26_2_g190(.AN (add_26_2_n_3), .B (add_26_2_n_29), .Y
       (add_26_2_n_41));
  OAI21X1 add_26_2_g191(.A0 (add_26_2_n_13), .A1 (add_26_2_n_6), .B0
       (add_26_2_n_17), .Y (add_26_2_n_40));
  INVX1 add_26_2_g192(.A (add_26_2_n_38), .Y (add_26_2_n_39));
  NOR2X1 add_26_2_g193(.A (add_26_2_n_12), .B (add_26_2_n_28), .Y
       (add_26_2_n_38));
  OAI21X1 add_26_2_g194(.A0 (add_26_2_n_14), .A1 (add_26_2_n_15), .B0
       (add_26_2_n_18), .Y (add_26_2_n_37));
  INVX1 add_26_2_g195(.A (add_26_2_n_35), .Y (add_26_2_n_36));
  INVX1 add_26_2_g196(.A (add_26_2_n_33), .Y (add_26_2_n_34));
  INVX1 add_26_2_g197(.A (add_26_2_n_31), .Y (add_26_2_n_32));
  INVX1 add_26_2_g198(.A (add_26_2_n_29), .Y (add_26_2_n_30));
  NOR2X1 add_26_2_g199(.A (add_26_2_n_7), .B (add_26_2_n_16), .Y
       (add_26_2_n_28));
  OR2XL add_26_2_g200(.A (add_26_2_n_15), .B (add_26_2_n_10), .Y
       (add_26_2_n_27));
  NOR2X1 add_26_2_g201(.A (add_26_2_n_12), .B (add_26_2_n_16), .Y
       (add_26_2_n_35));
  NOR2X1 add_26_2_g202(.A (add_26_2_n_8), .B (add_26_2_n_5), .Y
       (add_26_2_n_33));
  NOR2BX1 add_26_2_g203(.AN (add_26_2_n_18), .B (n_84), .Y
       (add_26_2_n_31));
  NOR2X1 add_26_2_g204(.A (add_26_2_n_16), .B (add_26_2_n_5), .Y
       (add_26_2_n_29));
  INVX1 add_26_2_g205(.A (add_26_2_n_24), .Y (add_26_2_n_25));
  INVX1 add_26_2_g206(.A (add_26_2_n_22), .Y (add_26_2_n_23));
  MXI2XL add_26_2_g208(.A (add_26_2_n_2), .B (in2[0]), .S0 (in3[0]), .Y
       (asc002_0_));
  NOR2X1 add_26_2_g209(.A (add_26_2_n_6), .B (add_26_2_n_3), .Y
       (add_26_2_n_26));
  NOR2BX1 add_26_2_g210(.AN (add_26_2_n_17), .B (add_26_2_n_6), .Y
       (add_26_2_n_24));
  NAND2BX1 add_26_2_g211(.AN (add_26_2_n_3), .B (add_26_2_n_13), .Y
       (add_26_2_n_22));
  NOR2X1 add_26_2_g212(.A (add_26_2_n_0), .B (add_26_2_n_11), .Y
       (add_26_2_n_19));
  NAND2X1 add_26_2_g213(.A (add_26_2_n_14), .B (add_26_2_n_9), .Y
       (add_26_2_n_21));
  NAND2X1 add_26_2_g214(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_18));
  NAND2X1 add_26_2_g216(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_17));
  NOR2X2 add_26_2_g217(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_16));
  NOR2X8 add_26_2_g218(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_15));
  NAND2X1 add_26_2_g219(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_14));
  NAND2X1 add_26_2_g220(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_13));
  INVX1 add_26_2_g221(.A (add_26_2_n_10), .Y (add_26_2_n_9));
  INVX1 add_26_2_g222(.A (add_26_2_n_7), .Y (add_26_2_n_8));
  AND2XL add_26_2_g223(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_12));
  NOR2X4 add_26_2_g224(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_11));
  NOR2X2 add_26_2_g225(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_10));
  NAND2X1 add_26_2_g226(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_7));
  NOR2X1 add_26_2_g227(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_6));
  NOR2X1 add_26_2_g228(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_5));
  NAND2X4 add_26_2_g229(.A (in2[0]), .B (in3[0]), .Y (add_26_2_n_4));
  NOR2X1 add_26_2_g230(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_3));
  INVX1 add_26_2_g232(.A (in2[0]), .Y (add_26_2_n_2));
  XOR2XL add_26_2_g2(.A (add_26_2_n_21), .B (n_87), .Y (asc002_2_));
  CLKAND2X6 add_26_2_g234(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_0));
  INVXL fopt(.A (n_81), .Y (n_79));
  INVXL fopt235(.A (n_81), .Y (n_80));
  INVXL fopt236(.A (add_26_2_n_51), .Y (n_81));
  BUFX2 fopt237(.A (add_26_2_n_15), .Y (n_84));
  INVXL fopt238(.A (n_88), .Y (n_86));
  INVXL fopt239(.A (n_88), .Y (n_87));
  INVXL fopt240(.A (add_26_2_n_46), .Y (n_88));
endmodule


