`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:45 CST (May 24 2023 11:41:45 UTC)

module dut_N_Mux_1_2_45_4(in3, in2, ctrl1, out1);
  input in3, in2, ctrl1;
  output out1;
  wire in3, in2, ctrl1;
  wire out1;
  MX2XL g11(.A (in3), .B (in2), .S0 (ctrl1), .Y (out1));
endmodule


