`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:26 CST (May 24 2023 09:40:26 UTC)

module dut_Add_4U_27_4(in1, out1);
  input [3:0] in1;
  output [3:0] out1;
  wire [3:0] in1;
  wire [3:0] out1;
  wire inc_add_21_2_1_n_0, inc_add_21_2_1_n_2;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 inc_add_21_2_1_g30(.A (in1[3]), .B (inc_add_21_2_1_n_2), .Y
       (out1[3]));
  XNOR2X1 inc_add_21_2_1_g31(.A (in1[2]), .B (inc_add_21_2_1_n_0), .Y
       (out1[2]));
  NAND2BX1 inc_add_21_2_1_g32(.AN (inc_add_21_2_1_n_0), .B (in1[2]), .Y
       (inc_add_21_2_1_n_2));
  XOR2XL inc_add_21_2_1_g33(.A (in1[1]), .B (in1[0]), .Y (out1[1]));
  NAND2X1 inc_add_21_2_1_g34(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_1_n_0));
endmodule


