`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:09 CST (May 16 2023 12:52:09 UTC)

module dut_Sub_3Ux1U_3S_4(in2, in1, out1);
  input [2:0] in2;
  input in1;
  output [2:0] out1;
  wire [2:0] in2;
  wire in1;
  wire [2:0] out1;
  wire dec_sub_23_2_1_n_0, dec_sub_23_2_1_n_2;
  XOR2XL dec_sub_23_2_1_g31(.A (in2[2]), .B (dec_sub_23_2_1_n_2), .Y
       (out1[2]));
  AO21XL dec_sub_23_2_1_g32(.A0 (in2[1]), .A1 (dec_sub_23_2_1_n_0), .B0
       (dec_sub_23_2_1_n_2), .Y (out1[1]));
  NOR2X1 dec_sub_23_2_1_g33(.A (in2[1]), .B (dec_sub_23_2_1_n_0), .Y
       (dec_sub_23_2_1_n_2));
  XOR2XL dec_sub_23_2_1_g34(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2BX1 dec_sub_23_2_1_g35(.AN (in2[0]), .B (in1), .Y
       (dec_sub_23_2_1_n_0));
endmodule


