`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:36 CST (May 26 2023 07:18:36 UTC)

module dut_entirecomputation_alt19_4(in1, in2, in3, out1);
  input in1;
  input [12:0] in2, in3;
  output [13:0] out1;
  wire in1;
  wire [12:0] in2, in3;
  wire [13:0] out1;
  wire add_26_2_n_0, add_26_2_n_1, add_26_2_n_2, add_26_2_n_3,
       add_26_2_n_4, add_26_2_n_5, add_26_2_n_6, add_26_2_n_7;
  wire add_26_2_n_8, add_26_2_n_9, add_26_2_n_10, add_26_2_n_11,
       add_26_2_n_12, add_26_2_n_13, add_26_2_n_14, add_26_2_n_15;
  wire add_26_2_n_16, add_26_2_n_17, add_26_2_n_18, add_26_2_n_19,
       add_26_2_n_20, add_26_2_n_21, add_26_2_n_22, add_26_2_n_23;
  wire add_26_2_n_24, add_26_2_n_25, add_26_2_n_26, add_26_2_n_27,
       add_26_2_n_28, add_26_2_n_29, add_26_2_n_30, add_26_2_n_31;
  wire add_26_2_n_32, add_26_2_n_33, add_26_2_n_34, add_26_2_n_35,
       add_26_2_n_36, add_26_2_n_37, add_26_2_n_38, add_26_2_n_40;
  wire add_26_2_n_41, add_26_2_n_42, add_26_2_n_44, add_26_2_n_45,
       add_26_2_n_46, add_26_2_n_47, add_26_2_n_49, add_26_2_n_52;
  wire add_26_2_n_53, add_26_2_n_54, add_26_2_n_55, add_26_2_n_59,
       add_26_2_n_60, add_26_2_n_61, add_26_2_n_62, add_26_2_n_66;
  wire asc002_0_, asc002_1_, asc002_2_, asc002_3_, asc002_4_,
       asc002_5_, asc002_6_, asc002_7_;
  wire asc002_8_, asc002_9_, asc002_10_, asc002_11_, asc002_12_,
       asc002_13_;
  NOR2BX1 g113(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g114(.AN (asc002_12_), .B (in1), .Y (out1[12]));
  NOR2BX1 g115(.AN (asc002_10_), .B (in1), .Y (out1[10]));
  NOR2BX1 g116(.AN (asc002_6_), .B (in1), .Y (out1[6]));
  NOR2BX1 g117(.AN (asc002_5_), .B (in1), .Y (out1[5]));
  NOR2BX1 g118(.AN (asc002_9_), .B (in1), .Y (out1[9]));
  NOR2BX1 g119(.AN (asc002_13_), .B (in1), .Y (out1[13]));
  NOR2BX1 g120(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g121(.AN (asc002_11_), .B (in1), .Y (out1[11]));
  NOR2BX1 g122(.AN (asc002_8_), .B (in1), .Y (out1[8]));
  NOR2BX1 g123(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g124(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  NOR2BX1 g125(.AN (asc002_7_), .B (in1), .Y (out1[7]));
  NOR2BX1 g126(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  XNOR2X1 add_26_2_g261(.A (add_26_2_n_28), .B (add_26_2_n_66), .Y
       (asc002_11_));
  ADDFX1 add_26_2_g262(.A (add_26_2_n_62), .B (in3[12]), .CI (in2[12]),
       .CO (asc002_13_), .S (asc002_12_));
  OAI21X1 add_26_2_g263(.A0 (add_26_2_n_10), .A1 (add_26_2_n_61), .B0
       (add_26_2_n_7), .Y (add_26_2_n_66));
  XNOR2X1 add_26_2_g264(.A (add_26_2_n_29), .B (add_26_2_n_61), .Y
       (asc002_10_));
  XNOR2X1 add_26_2_g265(.A (add_26_2_n_23), .B (add_26_2_n_60), .Y
       (asc002_9_));
  XNOR2X1 add_26_2_g266(.A (add_26_2_n_21), .B (add_26_2_n_59), .Y
       (asc002_7_));
  OAI211X1 add_26_2_g267(.A0 (add_26_2_n_37), .A1 (add_26_2_n_55), .B0
       (add_26_2_n_36), .C0 (add_26_2_n_41), .Y (add_26_2_n_62));
  AOI21X1 add_26_2_g268(.A0 (add_26_2_n_32), .A1 (add_26_2_n_54), .B0
       (add_26_2_n_35), .Y (add_26_2_n_61));
  OAI21X1 add_26_2_g269(.A0 (add_26_2_n_6), .A1 (add_26_2_n_55), .B0
       (add_26_2_n_5), .Y (add_26_2_n_60));
  OAI21X1 add_26_2_g270(.A0 (add_26_2_n_12), .A1 (add_26_2_n_53), .B0
       (add_26_2_n_14), .Y (add_26_2_n_59));
  MXI2XL add_26_2_g271(.A (add_26_2_n_54), .B (add_26_2_n_55), .S0
       (add_26_2_n_22), .Y (asc002_8_));
  XNOR2X1 add_26_2_g272(.A (add_26_2_n_20), .B (add_26_2_n_53), .Y
       (asc002_6_));
  XNOR2X1 add_26_2_g273(.A (add_26_2_n_24), .B (add_26_2_n_52), .Y
       (asc002_5_));
  INVX1 add_26_2_g274(.A (add_26_2_n_55), .Y (add_26_2_n_54));
  AOI31X1 add_26_2_g275(.A0 (add_26_2_n_47), .A1 (add_26_2_n_25), .A2
       (add_26_2_n_26), .B0 (add_26_2_n_42), .Y (add_26_2_n_55));
  AOI21X1 add_26_2_g276(.A0 (add_26_2_n_26), .A1 (add_26_2_n_47), .B0
       (add_26_2_n_34), .Y (add_26_2_n_53));
  OAI21X1 add_26_2_g277(.A0 (add_26_2_n_16), .A1 (add_26_2_n_46), .B0
       (add_26_2_n_4), .Y (add_26_2_n_52));
  XNOR2X1 add_26_2_g278(.A (add_26_2_n_30), .B (add_26_2_n_49), .Y
       (asc002_3_));
  MXI2XL add_26_2_g279(.A (add_26_2_n_47), .B (add_26_2_n_46), .S0
       (add_26_2_n_27), .Y (asc002_4_));
  OAI2BB1X1 add_26_2_g280(.A0N (add_26_2_n_0), .A1N (add_26_2_n_44),
       .B0 (add_26_2_n_11), .Y (add_26_2_n_49));
  XNOR2X1 add_26_2_g281(.A (add_26_2_n_31), .B (add_26_2_n_44), .Y
       (asc002_2_));
  INVX1 add_26_2_g282(.A (add_26_2_n_47), .Y (add_26_2_n_46));
  OAI211X1 add_26_2_g283(.A0 (add_26_2_n_11), .A1 (add_26_2_n_13), .B0
       (add_26_2_n_45), .C0 (add_26_2_n_19), .Y (add_26_2_n_47));
  NAND3BXL add_26_2_g284(.AN (add_26_2_n_13), .B (add_26_2_n_44), .C
       (add_26_2_n_0), .Y (add_26_2_n_45));
  ADDFX1 add_26_2_g285(.A (add_26_2_n_38), .B (in3[1]), .CI (in2[1]),
       .CO (add_26_2_n_44), .S (asc002_1_));
  OAI211X1 add_26_2_g286(.A0 (add_26_2_n_14), .A1 (add_26_2_n_15), .B0
       (add_26_2_n_40), .C0 (add_26_2_n_17), .Y (add_26_2_n_42));
  NAND2XL add_26_2_g287(.A (add_26_2_n_33), .B (add_26_2_n_35), .Y
       (add_26_2_n_41));
  NAND2XL add_26_2_g288(.A (add_26_2_n_25), .B (add_26_2_n_34), .Y
       (add_26_2_n_40));
  ADDHX1 add_26_2_g289(.A (in2[0]), .B (in3[0]), .CO (add_26_2_n_38),
       .S (asc002_0_));
  NAND2XL add_26_2_g290(.A (add_26_2_n_33), .B (add_26_2_n_32), .Y
       (add_26_2_n_37));
  OA21X1 add_26_2_g291(.A0 (add_26_2_n_7), .A1 (add_26_2_n_3), .B0
       (add_26_2_n_9), .Y (add_26_2_n_36));
  OAI21X1 add_26_2_g292(.A0 (add_26_2_n_5), .A1 (add_26_2_n_2), .B0
       (add_26_2_n_8), .Y (add_26_2_n_35));
  OAI21X1 add_26_2_g293(.A0 (add_26_2_n_4), .A1 (add_26_2_n_1), .B0
       (add_26_2_n_18), .Y (add_26_2_n_34));
  NAND2X1 add_26_2_g294(.A (add_26_2_n_11), .B (add_26_2_n_0), .Y
       (add_26_2_n_31));
  NAND2BX1 add_26_2_g295(.AN (add_26_2_n_13), .B (add_26_2_n_19), .Y
       (add_26_2_n_30));
  NOR2BX1 add_26_2_g296(.AN (add_26_2_n_7), .B (add_26_2_n_10), .Y
       (add_26_2_n_29));
  NOR2X1 add_26_2_g297(.A (add_26_2_n_3), .B (add_26_2_n_10), .Y
       (add_26_2_n_33));
  NOR2X1 add_26_2_g298(.A (add_26_2_n_2), .B (add_26_2_n_6), .Y
       (add_26_2_n_32));
  NAND2BX1 add_26_2_g299(.AN (add_26_2_n_3), .B (add_26_2_n_9), .Y
       (add_26_2_n_28));
  NAND2BX1 add_26_2_g300(.AN (add_26_2_n_16), .B (add_26_2_n_4), .Y
       (add_26_2_n_27));
  NAND2BX1 add_26_2_g301(.AN (add_26_2_n_1), .B (add_26_2_n_18), .Y
       (add_26_2_n_24));
  NAND2BX1 add_26_2_g302(.AN (add_26_2_n_2), .B (add_26_2_n_8), .Y
       (add_26_2_n_23));
  NAND2BX1 add_26_2_g303(.AN (add_26_2_n_6), .B (add_26_2_n_5), .Y
       (add_26_2_n_22));
  NAND2BX1 add_26_2_g304(.AN (add_26_2_n_15), .B (add_26_2_n_17), .Y
       (add_26_2_n_21));
  NOR2X1 add_26_2_g305(.A (add_26_2_n_1), .B (add_26_2_n_16), .Y
       (add_26_2_n_26));
  NOR2BX1 add_26_2_g306(.AN (add_26_2_n_14), .B (add_26_2_n_12), .Y
       (add_26_2_n_20));
  NOR2X1 add_26_2_g307(.A (add_26_2_n_15), .B (add_26_2_n_12), .Y
       (add_26_2_n_25));
  NAND2X1 add_26_2_g308(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_19));
  NAND2X1 add_26_2_g309(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_18));
  NAND2X1 add_26_2_g310(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_17));
  NOR2X1 add_26_2_g311(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_16));
  NOR2X1 add_26_2_g312(.A (in2[7]), .B (in3[7]), .Y (add_26_2_n_15));
  NAND2X1 add_26_2_g313(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_14));
  NOR2X1 add_26_2_g314(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_13));
  NOR2X1 add_26_2_g315(.A (in2[6]), .B (in3[6]), .Y (add_26_2_n_12));
  NAND2X1 add_26_2_g316(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_11));
  NOR2X1 add_26_2_g317(.A (in2[10]), .B (in3[10]), .Y (add_26_2_n_10));
  NAND2X1 add_26_2_g318(.A (in2[11]), .B (in3[11]), .Y (add_26_2_n_9));
  NAND2X1 add_26_2_g319(.A (in2[9]), .B (in3[9]), .Y (add_26_2_n_8));
  NAND2X1 add_26_2_g320(.A (in2[10]), .B (in3[10]), .Y (add_26_2_n_7));
  NOR2X1 add_26_2_g321(.A (in2[8]), .B (in3[8]), .Y (add_26_2_n_6));
  NAND2X1 add_26_2_g322(.A (in2[8]), .B (in3[8]), .Y (add_26_2_n_5));
  NAND2X1 add_26_2_g323(.A (in2[4]), .B (in3[4]), .Y (add_26_2_n_4));
  NOR2X1 add_26_2_g324(.A (in2[11]), .B (in3[11]), .Y (add_26_2_n_3));
  NOR2X1 add_26_2_g325(.A (in2[9]), .B (in3[9]), .Y (add_26_2_n_2));
  NOR2X1 add_26_2_g326(.A (in2[5]), .B (in3[5]), .Y (add_26_2_n_1));
  OR2XL add_26_2_g327(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_0));
endmodule


