`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 21:03:47 CST (May 16 2023 13:03:47 UTC)

module dut_Equal_1U_6_1(in1, out1);
  input [2:0] in1;
  output out1;
  wire [2:0] in1;
  wire out1;
  wire n_0;
  NOR3X6 g14(.A (in1[1]), .B (in1[2]), .C (n_0), .Y (out1));
  CLKINVX4 g15(.A (in1[0]), .Y (n_0));
endmodule


