`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:43 CST (May 26 2023 07:18:43 UTC)

module dut_entirecomputation_alt9_4(in1, in2, in3, out1);
  input in1;
  input [2:0] in2, in3;
  output [3:0] out1;
  wire in1;
  wire [2:0] in2, in3;
  wire [3:0] out1;
  wire add_26_2_n_0, add_26_2_n_2, asc002_0_, asc002_1_, asc002_2_,
       asc002_3_;
  NOR2BX1 g33(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g34(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  NOR2BX1 g35(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g36(.AN (asc002_1_), .B (in1), .Y (out1[1]));
  ADDFX1 add_26_2_g42(.A (add_26_2_n_2), .B (in3[2]), .CI (in2[2]), .CO
       (asc002_3_), .S (asc002_2_));
  ADDFX1 add_26_2_g43(.A (add_26_2_n_0), .B (in3[1]), .CI (in2[1]), .CO
       (add_26_2_n_2), .S (asc002_1_));
  ADDHX1 add_26_2_g44(.A (in2[0]), .B (in3[0]), .CO (add_26_2_n_0), .S
       (asc002_0_));
endmodule


