`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:23 CST (May 24 2023 09:40:23 UTC)

module dut_Add_4U_6_1(in1, out1);
  input [2:0] in1;
  output [3:0] out1;
  wire [2:0] in1;
  wire [3:0] out1;
  wire inc_add_21_2_1_n_0, inc_add_21_2_1_n_1, inc_add_21_2_1_n_2;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  MXI2X1 inc_add_21_2_1_g27(.A (in1[2]), .B (inc_add_21_2_1_n_1), .S0
       (inc_add_21_2_1_n_2), .Y (out1[2]));
  NOR2X1 inc_add_21_2_1_g28(.A (inc_add_21_2_1_n_1), .B
       (inc_add_21_2_1_n_2), .Y (out1[3]));
  MXI2XL inc_add_21_2_1_g29(.A (inc_add_21_2_1_n_0), .B (in1[1]), .S0
       (in1[0]), .Y (out1[1]));
  NAND2X8 inc_add_21_2_1_g30(.A (in1[1]), .B (in1[0]), .Y
       (inc_add_21_2_1_n_2));
  INVX1 inc_add_21_2_1_g31(.A (in1[2]), .Y (inc_add_21_2_1_n_1));
  INVX1 inc_add_21_2_1_g32(.A (in1[1]), .Y (inc_add_21_2_1_n_0));
endmodule


