`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:15:37 CST (May 16 2023 12:15:37 UTC)

module dut_Xor_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  XOR2XL g10(.A (in2), .B (in1), .Y (out1));
endmodule


