`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:42:01 CST (May 24 2023 11:42:01 UTC)

module dut_Add_4Ux3U_5U_1(in2, in1, out1);
  input [3:0] in2;
  input [2:0] in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire [2:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_10, add_23_2_n_11, add_23_2_n_12,
       add_23_2_n_15, add_23_2_n_19, n_29, n_30;
  wire n_31;
  MXI2X1 add_23_2_g67(.A (add_23_2_n_3), .B (in2[3]), .S0
       (add_23_2_n_19), .Y (out1[3]));
  OAI21X2 add_23_2_g68(.A0 (add_23_2_n_5), .A1 (n_31), .B0
       (add_23_2_n_8), .Y (add_23_2_n_19));
  OAI21X1 add_23_2_g69(.A0 (add_23_2_n_12), .A1 (n_29), .B0
       (add_23_2_n_11), .Y (out1[4]));
  MXI2XL add_23_2_g70(.A (add_23_2_n_10), .B (add_23_2_n_1), .S0
       (n_30), .Y (out1[2]));
  OAI21X4 add_23_2_g72(.A0 (add_23_2_n_4), .A1 (add_23_2_n_7), .B0
       (add_23_2_n_6), .Y (add_23_2_n_15));
  OR2XL add_23_2_g75(.A (add_23_2_n_3), .B (add_23_2_n_5), .Y
       (add_23_2_n_12));
  OR2XL add_23_2_g76(.A (add_23_2_n_3), .B (add_23_2_n_8), .Y
       (add_23_2_n_11));
  INVX1 add_23_2_g78(.A (add_23_2_n_1), .Y (add_23_2_n_10));
  MXI2XL add_23_2_g80(.A (add_23_2_n_2), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NAND2X1 add_23_2_g82(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_8));
  NOR2X8 add_23_2_g83(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_7));
  NAND2X2 add_23_2_g85(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_6));
  NOR2X1 add_23_2_g86(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_5));
  NAND2X8 add_23_2_g87(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_4));
  INVX1 add_23_2_g88(.A (in2[3]), .Y (add_23_2_n_3));
  INVX1 add_23_2_g89(.A (in2[0]), .Y (add_23_2_n_2));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_8), .B (add_23_2_n_5), .Y
       (add_23_2_n_1));
  NOR2BX1 add_23_2_g90(.AN (add_23_2_n_6), .B (add_23_2_n_7), .Y
       (add_23_2_n_0));
  XNOR2X1 g2(.A (add_23_2_n_4), .B (add_23_2_n_0), .Y (out1[1]));
  CLKINVX1 fopt(.A (n_30), .Y (n_29));
  CLKINVX1 fopt91(.A (n_31), .Y (n_30));
  CLKINVX3 fopt92(.A (add_23_2_n_15), .Y (n_31));
endmodule


