`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:43 CST (May 16 2023 12:52:43 UTC)

module dut_N_Mux_16_2_86_1(in2, ctrl1, out1);
  input [15:0] in2;
  input ctrl1;
  output [15:0] out1;
  wire [15:0] in2;
  wire ctrl1;
  wire [15:0] out1;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_89, n_91, n_93;
  NOR2X2 g130(.A (n_76), .B (n_91), .Y (out1[11]));
  NOR2X2 g125(.A (n_73), .B (n_93), .Y (out1[14]));
  NOR2X2 g133(.A (n_74), .B (n_93), .Y (out1[13]));
  NOR2X2 g126(.A (n_75), .B (n_87), .Y (out1[12]));
  NOR2X2 g128(.A (n_72), .B (n_93), .Y (out1[15]));
  NOR2X2 g132(.A (n_84), .B (n_91), .Y (out1[3]));
  NOR2X2 g134(.A (n_77), .B (n_91), .Y (out1[10]));
  NOR2X2 g137(.A (n_78), .B (n_93), .Y (out1[9]));
  NOR2X2 g135(.A (n_83), .B (n_89), .Y (out1[4]));
  NOR2X2 g129(.A (n_80), .B (n_89), .Y (out1[7]));
  NOR2X2 g131(.A (n_81), .B (n_87), .Y (out1[6]));
  NOR2X2 g136(.A (n_82), .B (n_89), .Y (out1[5]));
  NOR2X2 g127(.A (n_79), .B (n_91), .Y (out1[8]));
  NOR2X2 g138(.A (n_85), .B (n_89), .Y (out1[2]));
  NOR2X2 g139(.A (n_86), .B (n_87), .Y (out1[1]));
  NAND2X2 g124(.A (ctrl1), .B (n_71), .Y (out1[0]));
  CLKINVX3 fopt(.A (in2[0]), .Y (n_71));
  CLKINVX16 fopt166(.A (in2[15]), .Y (n_72));
  CLKINVX16 fopt167(.A (in2[14]), .Y (n_73));
  CLKINVX16 fopt168(.A (in2[13]), .Y (n_74));
  CLKINVX16 fopt169(.A (in2[12]), .Y (n_75));
  CLKINVX16 fopt170(.A (in2[11]), .Y (n_76));
  CLKINVX16 fopt171(.A (in2[10]), .Y (n_77));
  CLKINVX16 fopt172(.A (in2[9]), .Y (n_78));
  CLKINVX16 fopt173(.A (in2[8]), .Y (n_79));
  CLKINVX16 fopt174(.A (in2[7]), .Y (n_80));
  CLKINVX16 fopt175(.A (in2[6]), .Y (n_81));
  CLKINVX16 fopt176(.A (in2[5]), .Y (n_82));
  CLKINVX16 fopt177(.A (in2[4]), .Y (n_83));
  CLKINVX16 fopt178(.A (in2[3]), .Y (n_84));
  CLKINVX16 fopt179(.A (in2[2]), .Y (n_85));
  CLKINVX16 fopt180(.A (in2[1]), .Y (n_86));
  CLKINVX6 fopt181(.A (ctrl1), .Y (n_87));
  CLKINVX6 fopt182(.A (ctrl1), .Y (n_89));
  CLKINVX6 fopt183(.A (ctrl1), .Y (n_91));
  CLKINVX6 fopt184(.A (ctrl1), .Y (n_93));
endmodule


