`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:23:15 CST (May 26 2023 07:23:15 UTC)

module dut_entirecomputation_alt10_0(in1, in2, in3, out1);
  input in1;
  input [3:0] in2, in3;
  output [4:0] out1;
  wire in1;
  wire [3:0] in2, in3;
  wire [4:0] out1;
  wire n_124, n_125, n_128, n_140, n_143, n_144, n_148, n_166;
  wire n_189, n_192, n_193, n_194, n_211, n_212, n_213, n_230;
  wire n_231, n_248, n_249, n_262, n_267, n_268, n_275, n_303;
  wire n_304, n_305, n_306, n_319, n_325, n_326, n_327, n_328;
  wire n_342, n_343, n_357, n_358, n_359, n_367, n_370, n_371;
  wire n_373, n_374, n_375, n_376, n_377, n_378, n_379;
  NAND2X1 g988(.A (n_125), .B (n_128), .Y (out1[4]));
  AOI21X1 g989(.A0 (n_306), .A1 (n_359), .B0 (n_124), .Y (n_125));
  NOR2X1 g991(.A (in1), .B (n_166), .Y (n_124));
  NAND2X1 g990(.A (n_304), .B (n_262), .Y (n_128));
  NAND2X1 g693(.A (n_148), .B (n_231), .Y (out1[2]));
  NAND2X1 g695(.A (n_143), .B (n_248), .Y (n_148));
  AOI21X1 g697(.A0 (n_140), .A1 (n_305), .B0 (in1), .Y (n_143));
  NAND2X2 g705(.A (in2[2]), .B (in3[2]), .Y (n_140));
  NOR2X1 g703(.A (in2[1]), .B (in3[1]), .Y (n_144));
  NAND2X2 g1350(.A (in3[3]), .B (in2[3]), .Y (n_166));
  NOR3X1 g452(.A (in1), .B (n_193), .C (n_194), .Y (out1[1]));
  NOR2BX1 g453(.AN (n_367), .B (n_192), .Y (n_193));
  NOR2X1 g455(.A (n_189), .B (n_319), .Y (n_192));
  NOR2X1 g459(.A (in2[1]), .B (in3[1]), .Y (n_189));
  NOR3XL g454(.A (n_189), .B (n_367), .C (n_319), .Y (n_194));
  MXI2X1 g1416(.A (n_211), .B (n_213), .S0 (n_357), .Y (out1[3]));
  NAND2BX1 g1420(.AN (in1), .B (n_343), .Y (n_211));
  OAI2BB1X1 g1421(.A0N (in3[3]), .A1N (in2[3]), .B0 (n_212), .Y
       (n_213));
  NOR2X1 g1428(.A (in1), .B (n_268), .Y (n_212));
  NAND2X1 g74(.A (n_249), .B (n_230), .Y (n_231));
  NOR2X1 g75(.A (n_342), .B (n_375), .Y (n_230));
  OAI21X1 g192(.A0 (n_367), .A1 (n_144), .B0 (n_374), .Y (n_248));
  OR2XL g195(.A (n_144), .B (n_367), .Y (n_249));
  OAI21X1 g2633(.A0 (n_367), .A1 (n_267), .B0 (n_275), .Y (n_262));
  NOR2X1 g145(.A (in2[1]), .B (in3[1]), .Y (n_267));
  NOR2X4 g93(.A (in3[3]), .B (in2[3]), .Y (n_268));
  NAND2X1 g91(.A (in3[1]), .B (in2[1]), .Y (n_275));
  NOR3X1 g2639(.A (in1), .B (n_268), .C (n_303), .Y (n_304));
  NOR2X4 g2640(.A (in3[2]), .B (in2[2]), .Y (n_303));
  INVX1 g2641(.A (n_303), .Y (n_305));
  NOR2XL g2642(.A (in1), .B (n_303), .Y (n_306));
  INVX1 g12(.A (n_374), .Y (n_319));
  NAND2X1 g55(.A (n_326), .B (n_328), .Y (out1[0]));
  NAND2X1 g57(.A (in3[0]), .B (n_325), .Y (n_326));
  NOR2X1 g59(.A (in2[0]), .B (in1), .Y (n_325));
  NAND2X1 g56(.A (in2[0]), .B (n_327), .Y (n_328));
  NOR2X1 g58(.A (in1), .B (in3[0]), .Y (n_327));
  NAND2BX1 g2(.AN (in1), .B (n_140), .Y (n_342));
  NAND2BX1 g2657(.AN (n_268), .B (n_166), .Y (n_343));
  NOR2X2 g255(.A (n_373), .B (n_379), .Y (n_357));
  NOR2X1 g257(.A (n_268), .B (n_358), .Y (n_359));
  NAND2X2 g259(.A (in2[2]), .B (in3[2]), .Y (n_358));
  NAND2X4 g137(.A (in3[0]), .B (in2[0]), .Y (n_367));
  AOI21X4 g66(.A0 (n_370), .A1 (n_371), .B0 (n_377), .Y (n_373));
  NAND2X8 g67(.A (in3[2]), .B (in2[2]), .Y (n_370));
  NAND2X4 g69(.A (in3[1]), .B (in2[1]), .Y (n_371));
  OAI21X1 g29(.A0 (in2[2]), .A1 (in3[2]), .B0 (n_374), .Y (n_375));
  NAND2X6 g30(.A (in2[1]), .B (in3[1]), .Y (n_374));
  NOR3X4 g101(.A (n_376), .B (n_377), .C (n_378), .Y (n_379));
  NOR2X8 g102(.A (in2[1]), .B (in3[1]), .Y (n_376));
  NOR2X6 g103(.A (in2[2]), .B (in3[2]), .Y (n_377));
  NAND2X4 g104(.A (in2[0]), .B (in3[0]), .Y (n_378));
endmodule


