`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:27 CST (May 24 2023 11:41:27 UTC)

module dut_N_Mux_14_2_58_4(in2, ctrl1, out1);
  input [13:0] in2;
  input ctrl1;
  output [13:0] out1;
  wire [13:0] in2;
  wire ctrl1;
  wire [13:0] out1;
  NOR2BX1 g136(.AN (in2[8]), .B (ctrl1), .Y (out1[8]));
  NOR2BX1 g128(.AN (in2[12]), .B (ctrl1), .Y (out1[12]));
  NOR2BX1 g135(.AN (in2[11]), .B (ctrl1), .Y (out1[11]));
  NOR2BX1 g129(.AN (in2[10]), .B (ctrl1), .Y (out1[10]));
  NOR2BX1 g137(.AN (in2[2]), .B (ctrl1), .Y (out1[2]));
  NOR2BX1 g132(.AN (in2[9]), .B (ctrl1), .Y (out1[9]));
  NOR2BX1 g133(.AN (in2[13]), .B (ctrl1), .Y (out1[13]));
  NOR2BX1 g134(.AN (in2[0]), .B (ctrl1), .Y (out1[0]));
  NOR2BX1 g130(.AN (in2[6]), .B (ctrl1), .Y (out1[6]));
  NOR2BX1 g131(.AN (in2[5]), .B (ctrl1), .Y (out1[5]));
  NOR2BX1 g127(.AN (in2[4]), .B (ctrl1), .Y (out1[4]));
  NOR2BX1 g140(.AN (in2[3]), .B (ctrl1), .Y (out1[3]));
  NOR2BX1 g138(.AN (in2[1]), .B (ctrl1), .Y (out1[1]));
  NOR2BX1 g139(.AN (in2[7]), .B (ctrl1), .Y (out1[7]));
endmodule


