`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:48 CST (May 24 2023 11:41:48 UTC)

module dut_Add_13Ux13U_14U_1(in2, in1, out1);
  input [12:0] in2, in1;
  output [13:0] out1;
  wire [12:0] in2, in1;
  wire [13:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_9, add_23_2_n_10,
       add_23_2_n_12, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_52,
       add_23_2_n_53, add_23_2_n_54, add_23_2_n_55, add_23_2_n_56;
  wire add_23_2_n_57, add_23_2_n_58, add_23_2_n_59, add_23_2_n_60,
       add_23_2_n_61, add_23_2_n_62, add_23_2_n_63, add_23_2_n_64;
  wire add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68,
       add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_72;
  wire add_23_2_n_73, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76,
       add_23_2_n_77, add_23_2_n_78, add_23_2_n_79, add_23_2_n_80;
  wire add_23_2_n_81, add_23_2_n_82, add_23_2_n_83, add_23_2_n_84,
       add_23_2_n_85, add_23_2_n_86, add_23_2_n_87, add_23_2_n_88;
  wire add_23_2_n_89, add_23_2_n_90, add_23_2_n_91, add_23_2_n_92,
       add_23_2_n_93, add_23_2_n_94, add_23_2_n_97, add_23_2_n_98;
  wire add_23_2_n_99, add_23_2_n_100, n_130, n_131, n_132, n_134,
       n_135, n_136;
  wire n_137, n_139, n_140, n_141;
  MXI2XL add_23_2_g295(.A (add_23_2_n_58), .B (add_23_2_n_59), .S0
       (add_23_2_n_100), .Y (out1[12]));
  MXI2XL add_23_2_g296(.A (add_23_2_n_51), .B (add_23_2_n_52), .S0
       (add_23_2_n_97), .Y (out1[11]));
  MXI2XL add_23_2_g298(.A (add_23_2_n_49), .B (add_23_2_n_50), .S0
       (add_23_2_n_98), .Y (out1[9]));
  NOR2X1 add_23_2_g299(.A (add_23_2_n_79), .B (add_23_2_n_94), .Y
       (add_23_2_n_100));
  NOR2X2 add_23_2_g300(.A (add_23_2_n_70), .B (add_23_2_n_10), .Y
       (add_23_2_n_99));
  NOR2BX1 add_23_2_g301(.AN (add_23_2_n_36), .B (add_23_2_n_93), .Y
       (add_23_2_n_98));
  NOR2X1 add_23_2_g302(.A (add_23_2_n_81), .B (add_23_2_n_92), .Y
       (add_23_2_n_97));
  OAI21X1 add_23_2_g303(.A0 (add_23_2_n_75), .A1 (add_23_2_n_91), .B0
       (add_23_2_n_83), .Y (out1[13]));
  MXI2XL add_23_2_g306(.A (add_23_2_n_63), .B (add_23_2_n_64), .S0
       (add_23_2_n_89), .Y (out1[7]));
  NOR2X1 add_23_2_g308(.A (add_23_2_n_74), .B (add_23_2_n_91), .Y
       (add_23_2_n_94));
  NOR2X1 add_23_2_g310(.A (add_23_2_n_33), .B (add_23_2_n_91), .Y
       (add_23_2_n_93));
  NOR2X1 add_23_2_g311(.A (add_23_2_n_73), .B (add_23_2_n_91), .Y
       (add_23_2_n_92));
  NOR2X4 add_23_2_g312(.A (add_23_2_n_78), .B (add_23_2_n_87), .Y
       (add_23_2_n_91));
  NOR2BX1 add_23_2_g313(.AN (add_23_2_n_34), .B (add_23_2_n_88), .Y
       (add_23_2_n_90));
  NOR2X1 add_23_2_g317(.A (add_23_2_n_80), .B (add_23_2_n_86), .Y
       (add_23_2_n_89));
  NOR2X1 add_23_2_g319(.A (add_23_2_n_23), .B (add_23_2_n_84), .Y
       (add_23_2_n_88));
  NOR2X6 add_23_2_g320(.A (add_23_2_n_72), .B (add_23_2_n_84), .Y
       (add_23_2_n_87));
  NOR2X1 add_23_2_g321(.A (add_23_2_n_71), .B (add_23_2_n_84), .Y
       (add_23_2_n_86));
  NOR2BX1 add_23_2_g322(.AN (add_23_2_n_20), .B (add_23_2_n_2), .Y
       (add_23_2_n_85));
  NOR2X6 add_23_2_g324(.A (add_23_2_n_66), .B (add_23_2_n_82), .Y
       (add_23_2_n_84));
  AOI21X1 add_23_2_g326(.A0 (add_23_2_n_32), .A1 (add_23_2_n_79), .B0
       (add_23_2_n_42), .Y (add_23_2_n_83));
  NOR2X4 add_23_2_g327(.A (add_23_2_n_55), .B (add_23_2_n_77), .Y
       (add_23_2_n_82));
  OAI2BB1X1 add_23_2_g328(.A0N (add_23_2_n_17), .A1N (add_23_2_n_70),
       .B0 (add_23_2_n_39), .Y (add_23_2_n_81));
  OAI21X1 add_23_2_g329(.A0 (n_134), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_21), .Y (add_23_2_n_80));
  OAI2BB1X1 add_23_2_g330(.A0N (add_23_2_n_62), .A1N (add_23_2_n_70),
       .B0 (add_23_2_n_68), .Y (add_23_2_n_79));
  OAI21X2 add_23_2_g331(.A0 (add_23_2_n_69), .A1 (add_23_2_n_61), .B0
       (add_23_2_n_67), .Y (add_23_2_n_78));
  NOR2X4 add_23_2_g332(.A (add_23_2_n_1), .B (add_23_2_n_76), .Y
       (add_23_2_n_77));
  NOR2X2 add_23_2_g334(.A (add_23_2_n_19), .B (add_23_2_n_29), .Y
       (add_23_2_n_76));
  NAND2BX1 add_23_2_g335(.AN (add_23_2_n_74), .B (add_23_2_n_32), .Y
       (add_23_2_n_75));
  NAND2X1 add_23_2_g337(.A (add_23_2_n_62), .B (add_23_2_n_57), .Y
       (add_23_2_n_74));
  NAND2X1 add_23_2_g338(.A (add_23_2_n_17), .B (add_23_2_n_57), .Y
       (add_23_2_n_73));
  NAND2X2 add_23_2_g339(.A (add_23_2_n_60), .B (add_23_2_n_56), .Y
       (add_23_2_n_72));
  NAND2BX1 add_23_2_g340(.AN (n_137), .B (add_23_2_n_56), .Y
       (add_23_2_n_71));
  OAI21X1 add_23_2_g341(.A0 (add_23_2_n_36), .A1 (add_23_2_n_38), .B0
       (add_23_2_n_27), .Y (add_23_2_n_70));
  NOR2X2 add_23_2_g343(.A (add_23_2_n_41), .B (add_23_2_n_43), .Y
       (add_23_2_n_69));
  OA21X1 add_23_2_g344(.A0 (add_23_2_n_39), .A1 (add_23_2_n_18), .B0
       (add_23_2_n_40), .Y (add_23_2_n_68));
  AOI2BB1X1 add_23_2_g345(.A0N (add_23_2_n_21), .A1N (add_23_2_n_35),
       .B0 (add_23_2_n_26), .Y (add_23_2_n_67));
  OAI21X2 add_23_2_g346(.A0 (add_23_2_n_20), .A1 (add_23_2_n_25), .B0
       (add_23_2_n_28), .Y (add_23_2_n_66));
  INVX1 add_23_2_g348(.A (add_23_2_n_63), .Y (add_23_2_n_64));
  INVX1 add_23_2_g349(.A (add_23_2_n_60), .Y (add_23_2_n_61));
  INVX1 add_23_2_g350(.A (add_23_2_n_58), .Y (add_23_2_n_59));
  NAND2X2 add_23_2_g353(.A (add_23_2_n_24), .B (add_23_2_n_22), .Y
       (add_23_2_n_55));
  NOR2BX1 add_23_2_g354(.AN (add_23_2_n_28), .B (add_23_2_n_25), .Y
       (add_23_2_n_65));
  NOR2X1 add_23_2_g355(.A (add_23_2_n_26), .B (add_23_2_n_35), .Y
       (add_23_2_n_63));
  NOR2X1 add_23_2_g356(.A (add_23_2_n_1), .B (add_23_2_n_29), .Y
       (add_23_2_n_54));
  NOR2X1 add_23_2_g357(.A (add_23_2_n_18), .B (add_23_2_n_16), .Y
       (add_23_2_n_62));
  NOR2X1 add_23_2_g358(.A (add_23_2_n_35), .B (add_23_2_n_30), .Y
       (add_23_2_n_60));
  NOR2X1 add_23_2_g359(.A (add_23_2_n_42), .B (add_23_2_n_31), .Y
       (add_23_2_n_58));
  NOR2X1 add_23_2_g360(.A (add_23_2_n_38), .B (add_23_2_n_33), .Y
       (add_23_2_n_57));
  NOR2X1 add_23_2_g361(.A (add_23_2_n_37), .B (add_23_2_n_23), .Y
       (add_23_2_n_56));
  INVX1 add_23_2_g363(.A (add_23_2_n_51), .Y (add_23_2_n_52));
  INVX1 add_23_2_g364(.A (add_23_2_n_49), .Y (add_23_2_n_50));
  NOR2X2 add_23_2_g370(.A (add_23_2_n_34), .B (add_23_2_n_37), .Y
       (add_23_2_n_43));
  NAND2X1 add_23_2_g372(.A (add_23_2_n_39), .B (add_23_2_n_17), .Y
       (add_23_2_n_53));
  NOR2BX1 add_23_2_g373(.AN (add_23_2_n_40), .B (add_23_2_n_18), .Y
       (add_23_2_n_51));
  NOR2BX1 add_23_2_g374(.AN (add_23_2_n_27), .B (add_23_2_n_38), .Y
       (add_23_2_n_49));
  NAND2BX1 add_23_2_g375(.AN (n_135), .B (add_23_2_n_21), .Y
       (add_23_2_n_48));
  NAND2X1 add_23_2_g376(.A (add_23_2_n_20), .B (n_139), .Y
       (add_23_2_n_47));
  NAND2BX1 add_23_2_g377(.AN (add_23_2_n_33), .B (add_23_2_n_36), .Y
       (add_23_2_n_46));
  NAND2BX1 add_23_2_g378(.AN (add_23_2_n_23), .B (add_23_2_n_34), .Y
       (add_23_2_n_45));
  NOR2X1 add_23_2_g379(.A (add_23_2_n_41), .B (add_23_2_n_37), .Y
       (add_23_2_n_44));
  INVX1 add_23_2_g380(.A (add_23_2_n_31), .Y (add_23_2_n_32));
  AND2XL add_23_2_g381(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_42));
  AND2X6 add_23_2_g382(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_41));
  NAND2X1 add_23_2_g383(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_40));
  NAND2X1 add_23_2_g384(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_39));
  NOR2X1 add_23_2_g385(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_38));
  NOR2X4 add_23_2_g386(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_37));
  NAND2X1 add_23_2_g387(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_36));
  NOR2X2 add_23_2_g388(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_35));
  NAND2X2 add_23_2_g389(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_34));
  NOR2X1 add_23_2_g390(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_33));
  NOR2X1 add_23_2_g391(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_31));
  NOR2X1 add_23_2_g392(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_30));
  INVX1 add_23_2_g393(.A (add_23_2_n_25), .Y (add_23_2_n_24));
  INVX1 add_23_2_g395(.A (add_23_2_n_16), .Y (add_23_2_n_17));
  NOR2X4 add_23_2_g396(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_29));
  NAND2X1 add_23_2_g397(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g398(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_27));
  AND2X1 add_23_2_g400(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_26));
  NOR2X4 add_23_2_g401(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g402(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_23));
  NAND2X2 add_23_2_g403(.A (add_23_2_n_14), .B (add_23_2_n_15), .Y
       (add_23_2_n_22));
  NAND2X1 add_23_2_g404(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_21));
  NAND2X2 add_23_2_g405(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_20));
  NAND2X6 add_23_2_g406(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g407(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_18));
  NOR2X1 add_23_2_g408(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_16));
  CLKINVX2 add_23_2_g409(.A (in1[2]), .Y (add_23_2_n_15));
  CLKINVX2 add_23_2_g413(.A (in2[2]), .Y (add_23_2_n_14));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_19), .B (add_23_2_n_54), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g414(.AN (add_23_2_n_69), .B (add_23_2_n_9), .Y
       (add_23_2_n_12));
  XNOR2X1 add_23_2_g415(.A (add_23_2_n_65), .B (add_23_2_n_85), .Y
       (out1[3]));
  NOR2BX2 add_23_2_g416(.AN (add_23_2_n_57), .B (add_23_2_n_91), .Y
       (add_23_2_n_10));
  NOR2BX1 add_23_2_g417(.AN (add_23_2_n_56), .B (add_23_2_n_84), .Y
       (add_23_2_n_9));
  CLKXOR2X1 add_23_2_g418(.A (add_23_2_n_53), .B (add_23_2_n_99), .Y
       (out1[10]));
  CLKXOR2X1 add_23_2_g419(.A (add_23_2_n_48), .B (add_23_2_n_12), .Y
       (out1[6]));
  CLKXOR2X1 add_23_2_g420(.A (add_23_2_n_47), .B (n_130), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g421(.A (add_23_2_n_46), .B (add_23_2_n_91), .Y
       (out1[8]));
  CLKXOR2X1 add_23_2_g422(.A (add_23_2_n_45), .B (add_23_2_n_84), .Y
       (out1[4]));
  XNOR2XL add_23_2_g423(.A (add_23_2_n_44), .B (add_23_2_n_90), .Y
       (out1[5]));
  NOR2BX1 add_23_2_g424(.AN (n_140), .B (n_131), .Y (add_23_2_n_2));
  CLKAND2X6 add_23_2_g425(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g426(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_132), .Y (n_130));
  INVXL fopt427(.A (n_132), .Y (n_131));
  INVXL fopt428(.A (add_23_2_n_77), .Y (n_132));
  INVXL fopt429(.A (n_136), .Y (n_134));
  INVXL fopt430(.A (n_136), .Y (n_135));
  INVXL fopt431(.A (n_137), .Y (n_136));
  BUFX2 fopt432(.A (add_23_2_n_30), .Y (n_137));
  INVXL fopt433(.A (n_141), .Y (n_139));
  INVXL fopt434(.A (n_141), .Y (n_140));
  INVXL fopt435(.A (add_23_2_n_22), .Y (n_141));
endmodule


