`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:18:55 CST (May 26 2023 07:18:55 UTC)

module dut_entirecomputation_alt10_1(in1, in2, in3, out1);
  input in1;
  input [3:0] in2, in3;
  output [4:0] out1;
  wire in1;
  wire [3:0] in2, in3;
  wire [4:0] out1;
  wire add_26_2_n_0, add_26_2_n_1, add_26_2_n_2, add_26_2_n_3,
       add_26_2_n_4, add_26_2_n_5, add_26_2_n_6, add_26_2_n_7;
  wire add_26_2_n_8, add_26_2_n_9, add_26_2_n_11, add_26_2_n_12,
       add_26_2_n_13, add_26_2_n_14, add_26_2_n_15, add_26_2_n_16;
  wire add_26_2_n_17, add_26_2_n_18, add_26_2_n_21, add_26_2_n_25,
       asc002_0_, asc002_2_, asc002_3_, asc002_4_;
  wire n_35, n_36;
  NOR2BX1 g41(.AN (asc002_4_), .B (in1), .Y (out1[4]));
  NOR2BX1 g42(.AN (asc002_3_), .B (in1), .Y (out1[3]));
  NOR2BX1 g43(.AN (n_35), .B (in1), .Y (out1[1]));
  NOR2BX1 g44(.AN (asc002_0_), .B (in1), .Y (out1[0]));
  NOR2BX1 g45(.AN (asc002_2_), .B (in1), .Y (out1[2]));
  MXI2XL add_26_2_g66(.A (add_26_2_n_15), .B (add_26_2_n_14), .S0
       (add_26_2_n_25), .Y (asc002_3_));
  AOI21X2 add_26_2_g67(.A0 (add_26_2_n_0), .A1 (add_26_2_n_21), .B0
       (add_26_2_n_4), .Y (add_26_2_n_25));
  MXI2XL add_26_2_g68(.A (add_26_2_n_11), .B (add_26_2_n_12), .S0
       (add_26_2_n_21), .Y (asc002_2_));
  OAI21X1 add_26_2_g69(.A0 (add_26_2_n_16), .A1 (n_36), .B0
       (add_26_2_n_18), .Y (asc002_4_));
  OAI21X2 add_26_2_g71(.A0 (add_26_2_n_2), .A1 (add_26_2_n_8), .B0
       (add_26_2_n_9), .Y (add_26_2_n_21));
  NOR2BX1 add_26_2_g74(.AN (add_26_2_n_5), .B (add_26_2_n_13), .Y
       (add_26_2_n_18));
  NOR2BX1 add_26_2_g75(.AN (add_26_2_n_9), .B (add_26_2_n_8), .Y
       (add_26_2_n_17));
  NAND2X1 add_26_2_g76(.A (add_26_2_n_7), .B (add_26_2_n_0), .Y
       (add_26_2_n_16));
  INVX1 add_26_2_g77(.A (add_26_2_n_14), .Y (add_26_2_n_15));
  NAND2X1 add_26_2_g78(.A (add_26_2_n_5), .B (add_26_2_n_7), .Y
       (add_26_2_n_14));
  NOR2X1 add_26_2_g79(.A (add_26_2_n_3), .B (add_26_2_n_6), .Y
       (add_26_2_n_13));
  INVX1 add_26_2_g80(.A (add_26_2_n_11), .Y (add_26_2_n_12));
  NAND2X1 add_26_2_g81(.A (add_26_2_n_3), .B (add_26_2_n_0), .Y
       (add_26_2_n_11));
  MXI2XL add_26_2_g82(.A (add_26_2_n_1), .B (in2[0]), .S0 (in3[0]), .Y
       (asc002_0_));
  NAND2X1 add_26_2_g83(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_9));
  NOR2X4 add_26_2_g84(.A (in2[1]), .B (in3[1]), .Y (add_26_2_n_8));
  INVX1 add_26_2_g85(.A (add_26_2_n_6), .Y (add_26_2_n_7));
  NOR2X1 add_26_2_g86(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_6));
  NAND2X1 add_26_2_g87(.A (in2[3]), .B (in3[3]), .Y (add_26_2_n_5));
  INVX1 add_26_2_g89(.A (add_26_2_n_3), .Y (add_26_2_n_4));
  NAND2X1 add_26_2_g90(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_3));
  NAND2X8 add_26_2_g91(.A (in2[0]), .B (in3[0]), .Y (add_26_2_n_2));
  INVX1 add_26_2_g92(.A (in2[0]), .Y (add_26_2_n_1));
  OR2X1 add_26_2_g2(.A (in2[2]), .B (in3[2]), .Y (add_26_2_n_0));
  XNOR2XL g2(.A (add_26_2_n_2), .B (add_26_2_n_17), .Y (n_35));
  INVXL fopt(.A (add_26_2_n_21), .Y (n_36));
endmodule


