`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:42:07 CST (May 24 2023 11:42:07 UTC)

module dut_N_Mux_2_2_46_1(in2, ctrl1, out1);
  input [1:0] in2;
  input ctrl1;
  output [1:0] out1;
  wire [1:0] in2;
  wire ctrl1;
  wire [1:0] out1;
  wire n_0, n_1;
  NOR2X4 g19(.A (ctrl1), .B (n_0), .Y (out1[1]));
  NOR2X4 g20(.A (ctrl1), .B (n_1), .Y (out1[0]));
  CLKINVX12 g21(.A (in2[0]), .Y (n_1));
  CLKINVX12 g22(.A (in2[1]), .Y (n_0));
endmodule


