`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:15:48 CST (May 16 2023 12:15:48 UTC)

module dut_Equal_14Ux7U_1U_4(in2, in1, out1);
  input [13:0] in2;
  input [6:0] in1;
  output out1;
  wire [13:0] in2;
  wire [6:0] in1;
  wire out1;
  wire eq_21_21_n_0, eq_21_21_n_1, eq_21_21_n_2, eq_21_21_n_3,
       eq_21_21_n_4, eq_21_21_n_5, eq_21_21_n_6, eq_21_21_n_7;
  wire eq_21_21_n_8, eq_21_21_n_9, eq_21_21_n_10;
  NOR4X1 eq_21_21_g61(.A (eq_21_21_n_10), .B (eq_21_21_n_9), .C
       (in2[7]), .D (eq_21_21_n_0), .Y (out1));
  NAND4XL eq_21_21_g62(.A (eq_21_21_n_8), .B (eq_21_21_n_6), .C
       (eq_21_21_n_2), .D (eq_21_21_n_1), .Y (eq_21_21_n_10));
  NAND4XL eq_21_21_g63(.A (eq_21_21_n_7), .B (eq_21_21_n_5), .C
       (eq_21_21_n_4), .D (eq_21_21_n_3), .Y (eq_21_21_n_9));
  XNOR2X1 eq_21_21_g64(.A (in1[6]), .B (in2[6]), .Y (eq_21_21_n_8));
  XNOR2X1 eq_21_21_g65(.A (in1[3]), .B (in2[3]), .Y (eq_21_21_n_7));
  XNOR2X1 eq_21_21_g66(.A (in1[4]), .B (in2[4]), .Y (eq_21_21_n_6));
  XNOR2X1 eq_21_21_g67(.A (in1[2]), .B (in2[2]), .Y (eq_21_21_n_5));
  XNOR2X1 eq_21_21_g68(.A (in1[1]), .B (in2[1]), .Y (eq_21_21_n_4));
  XNOR2X1 eq_21_21_g69(.A (in1[0]), .B (in2[0]), .Y (eq_21_21_n_3));
  XNOR2X1 eq_21_21_g70(.A (in1[5]), .B (in2[5]), .Y (eq_21_21_n_2));
  NOR4X1 eq_21_21_g71(.A (in2[13]), .B (in2[12]), .C (in2[11]), .D
       (in2[10]), .Y (eq_21_21_n_1));
  OR2XL eq_21_21_g72(.A (in2[9]), .B (in2[8]), .Y (eq_21_21_n_0));
endmodule


