`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:12 CST (May 24 2023 09:40:12 UTC)

module dut_GreaterThan_1U_15_4(in1, out1);
  input [4:0] in1;
  output out1;
  wire [4:0] in1;
  wire out1;
  wire gt_19_55_n_0, gt_19_55_n_1;
  NOR2X1 gt_19_55_g126(.A (in1[4]), .B (gt_19_55_n_1), .Y (out1));
  NOR4X1 gt_19_55_g127(.A (in1[4]), .B (in1[3]), .C (in1[0]), .D
       (gt_19_55_n_0), .Y (gt_19_55_n_1));
  OR2XL gt_19_55_g128(.A (in1[2]), .B (in1[1]), .Y (gt_19_55_n_0));
endmodule


