`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 17:40:23 CST (May 24 2023 09:40:23 UTC)

module dut_GreaterThan_1U_15_1(in1, out1);
  input [4:0] in1;
  output out1;
  wire [4:0] in1;
  wire out1;
  wire gt_19_55_n_0, gt_19_55_n_1;
  AOI21X2 gt_19_55_g131(.A0 (gt_19_55_n_0), .A1 (gt_19_55_n_1), .B0
       (in1[4]), .Y (out1));
  NOR3X6 gt_19_55_g132(.A (in1[0]), .B (in1[2]), .C (in1[1]), .Y
       (gt_19_55_n_1));
  NOR2X1 gt_19_55_g133(.A (in1[4]), .B (in1[3]), .Y (gt_19_55_n_0));
endmodule


