`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:53 CST (May 24 2023 11:41:53 UTC)

module dut_Add_11Ux11U_12U_1(in2, in1, out1);
  input [10:0] in2, in1;
  output [11:0] out1;
  wire [10:0] in2, in1;
  wire [11:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_3, add_23_2_n_10,
       add_23_2_n_12, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_52,
       add_23_2_n_53, add_23_2_n_54, add_23_2_n_55, add_23_2_n_56;
  wire add_23_2_n_57, add_23_2_n_58, add_23_2_n_59, add_23_2_n_60,
       add_23_2_n_61, add_23_2_n_62, add_23_2_n_63, add_23_2_n_64;
  wire add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68,
       add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_72;
  wire add_23_2_n_73, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76,
       add_23_2_n_78, add_23_2_n_79, n_104, n_105;
  wire n_106, n_108;
  MXI2X1 add_23_2_g234(.A (add_23_2_n_51), .B (add_23_2_n_52), .S0
       (add_23_2_n_79), .Y (out1[10]));
  MXI2X1 add_23_2_g235(.A (add_23_2_n_46), .B (add_23_2_n_47), .S0
       (add_23_2_n_78), .Y (out1[9]));
  NOR2X1 add_23_2_g236(.A (add_23_2_n_57), .B (add_23_2_n_76), .Y
       (add_23_2_n_79));
  NOR2BX1 add_23_2_g237(.AN (add_23_2_n_22), .B (add_23_2_n_75), .Y
       (add_23_2_n_78));
  OAI21X1 add_23_2_g238(.A0 (add_23_2_n_60), .A1 (add_23_2_n_74), .B0
       (add_23_2_n_65), .Y (out1[11]));
  NOR2BX1 add_23_2_g243(.AN (add_23_2_n_48), .B (add_23_2_n_74), .Y
       (add_23_2_n_76));
  NOR2X1 add_23_2_g244(.A (add_23_2_n_31), .B (add_23_2_n_74), .Y
       (add_23_2_n_75));
  NOR2X2 add_23_2_g245(.A (add_23_2_n_63), .B (add_23_2_n_70), .Y
       (add_23_2_n_74));
  NOR2BX1 add_23_2_g247(.AN (add_23_2_n_30), .B (add_23_2_n_71), .Y
       (add_23_2_n_73));
  NOR2X1 add_23_2_g250(.A (add_23_2_n_64), .B (add_23_2_n_69), .Y
       (add_23_2_n_72));
  NOR2X1 add_23_2_g252(.A (add_23_2_n_19), .B (add_23_2_n_67), .Y
       (add_23_2_n_71));
  NOR2X2 add_23_2_g253(.A (add_23_2_n_59), .B (add_23_2_n_67), .Y
       (add_23_2_n_70));
  NOR2X1 add_23_2_g254(.A (add_23_2_n_58), .B (add_23_2_n_67), .Y
       (add_23_2_n_69));
  NOR2BX1 add_23_2_g255(.AN (add_23_2_n_18), .B (add_23_2_n_2), .Y
       (add_23_2_n_68));
  NOR2X4 add_23_2_g257(.A (add_23_2_n_54), .B (add_23_2_n_66), .Y
       (add_23_2_n_67));
  NOR2X4 add_23_2_g259(.A (add_23_2_n_3), .B (add_23_2_n_62), .Y
       (add_23_2_n_66));
  AOI21X1 add_23_2_g260(.A0 (add_23_2_n_21), .A1 (add_23_2_n_57), .B0
       (add_23_2_n_23), .Y (add_23_2_n_65));
  OAI21X1 add_23_2_g261(.A0 (add_23_2_n_28), .A1 (add_23_2_n_56), .B0
       (add_23_2_n_34), .Y (add_23_2_n_64));
  OAI21X2 add_23_2_g262(.A0 (add_23_2_n_50), .A1 (add_23_2_n_56), .B0
       (add_23_2_n_55), .Y (add_23_2_n_63));
  NOR2X2 add_23_2_g263(.A (add_23_2_n_61), .B (add_23_2_n_1), .Y
       (add_23_2_n_62));
  NOR2X2 add_23_2_g265(.A (add_23_2_n_16), .B (add_23_2_n_36), .Y
       (add_23_2_n_61));
  NAND2X1 add_23_2_g267(.A (add_23_2_n_21), .B (add_23_2_n_48), .Y
       (add_23_2_n_60));
  NAND2X1 add_23_2_g268(.A (add_23_2_n_49), .B (add_23_2_n_45), .Y
       (add_23_2_n_59));
  NAND2BX1 add_23_2_g269(.AN (add_23_2_n_28), .B (add_23_2_n_45), .Y
       (add_23_2_n_58));
  OAI21X1 add_23_2_g270(.A0 (add_23_2_n_22), .A1 (add_23_2_n_33), .B0
       (add_23_2_n_25), .Y (add_23_2_n_57));
  NOR2X1 add_23_2_g272(.A (add_23_2_n_24), .B (add_23_2_n_44), .Y
       (add_23_2_n_56));
  AOI2BB1X1 add_23_2_g273(.A0N (add_23_2_n_34), .A1N (add_23_2_n_29),
       .B0 (add_23_2_n_26), .Y (add_23_2_n_55));
  OAI21X2 add_23_2_g274(.A0 (add_23_2_n_18), .A1 (add_23_2_n_35), .B0
       (add_23_2_n_27), .Y (add_23_2_n_54));
  INVX1 add_23_2_g276(.A (add_23_2_n_51), .Y (add_23_2_n_52));
  INVX1 add_23_2_g277(.A (add_23_2_n_49), .Y (add_23_2_n_50));
  INVX1 add_23_2_g278(.A (add_23_2_n_46), .Y (add_23_2_n_47));
  NOR2X1 add_23_2_g280(.A (add_23_2_n_30), .B (add_23_2_n_17), .Y
       (add_23_2_n_44));
  NAND2X1 add_23_2_g281(.A (add_23_2_n_18), .B (add_23_2_n_32), .Y
       (add_23_2_n_53));
  NOR2X1 add_23_2_g282(.A (add_23_2_n_1), .B (add_23_2_n_36), .Y
       (add_23_2_n_43));
  NOR2X1 add_23_2_g283(.A (add_23_2_n_23), .B (add_23_2_n_20), .Y
       (add_23_2_n_51));
  NOR2X1 add_23_2_g284(.A (add_23_2_n_29), .B (add_23_2_n_28), .Y
       (add_23_2_n_49));
  NOR2X1 add_23_2_g285(.A (add_23_2_n_33), .B (add_23_2_n_31), .Y
       (add_23_2_n_48));
  NOR2BX1 add_23_2_g286(.AN (add_23_2_n_25), .B (add_23_2_n_33), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g287(.A (add_23_2_n_17), .B (add_23_2_n_19), .Y
       (add_23_2_n_45));
  NOR2X1 add_23_2_g296(.A (add_23_2_n_26), .B (add_23_2_n_29), .Y
       (add_23_2_n_42));
  NOR2X1 add_23_2_g297(.A (add_23_2_n_24), .B (add_23_2_n_17), .Y
       (add_23_2_n_41));
  NAND2BX1 add_23_2_g298(.AN (add_23_2_n_19), .B (add_23_2_n_30), .Y
       (add_23_2_n_40));
  NOR2BX1 add_23_2_g299(.AN (add_23_2_n_27), .B (n_108), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g300(.AN (add_23_2_n_28), .B (add_23_2_n_34), .Y
       (add_23_2_n_38));
  NAND2BX1 add_23_2_g301(.AN (add_23_2_n_31), .B (add_23_2_n_22), .Y
       (add_23_2_n_37));
  NOR2X6 add_23_2_g305(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_36));
  NOR2X6 add_23_2_g306(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_35));
  NAND2X1 add_23_2_g307(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_34));
  NOR2X1 add_23_2_g308(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_33));
  NAND2X4 add_23_2_g309(.A (add_23_2_n_14), .B (add_23_2_n_15), .Y
       (add_23_2_n_32));
  NOR2X1 add_23_2_g310(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_31));
  NAND2X1 add_23_2_g311(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_30));
  NOR2X1 add_23_2_g312(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_29));
  NOR2X1 add_23_2_g313(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_28));
  INVX1 add_23_2_g314(.A (add_23_2_n_20), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g315(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_27));
  AND2X1 add_23_2_g316(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_26));
  NAND2X1 add_23_2_g317(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_25));
  AND2X1 add_23_2_g318(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_24));
  AND2XL add_23_2_g319(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_23));
  NAND2X1 add_23_2_g320(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_22));
  NOR2X1 add_23_2_g321(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_20));
  NOR2X1 add_23_2_g322(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_19));
  NAND2X2 add_23_2_g323(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_18));
  NOR2X2 add_23_2_g324(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_17));
  NAND2X8 add_23_2_g325(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_16));
  INVX1 add_23_2_g327(.A (in1[2]), .Y (add_23_2_n_15));
  INVX2 add_23_2_g328(.A (in2[2]), .Y (add_23_2_n_14));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_16), .B (add_23_2_n_43), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g331(.AN (add_23_2_n_56), .B (add_23_2_n_10), .Y
       (add_23_2_n_12));
  CLKXOR2X1 add_23_2_g332(.A (add_23_2_n_53), .B (n_104), .Y (out1[2]));
  NOR2BX1 add_23_2_g333(.AN (add_23_2_n_45), .B (add_23_2_n_67), .Y
       (add_23_2_n_10));
  XNOR2XL add_23_2_g334(.A (add_23_2_n_42), .B (add_23_2_n_72), .Y
       (out1[7]));
  XNOR2XL add_23_2_g335(.A (add_23_2_n_41), .B (add_23_2_n_73), .Y
       (out1[5]));
  CLKXOR2X1 add_23_2_g336(.A (add_23_2_n_40), .B (add_23_2_n_67), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g337(.A (add_23_2_n_39), .B (add_23_2_n_68), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g338(.A (add_23_2_n_38), .B (add_23_2_n_12), .Y
       (out1[6]));
  CLKXOR2X1 add_23_2_g339(.A (add_23_2_n_37), .B (add_23_2_n_74), .Y
       (out1[8]));
  NAND2BX4 add_23_2_g340(.AN (add_23_2_n_35), .B (add_23_2_n_32), .Y
       (add_23_2_n_3));
  NOR2BX1 add_23_2_g341(.AN (add_23_2_n_32), .B (n_105), .Y
       (add_23_2_n_2));
  CLKAND2X6 add_23_2_g342(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g343(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_106), .Y (n_104));
  INVXL fopt344(.A (n_106), .Y (n_105));
  INVXL fopt345(.A (add_23_2_n_62), .Y (n_106));
  BUFX2 fopt346(.A (add_23_2_n_35), .Y (n_108));
endmodule


