`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:36 CST (May 24 2023 11:41:36 UTC)

module dut_Add_6Ux6U_7U_4(in2, in1, out1);
  input [5:0] in2, in1;
  output [6:0] out1;
  wire [5:0] in2, in1;
  wire [6:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_15, add_23_2_n_16, add_23_2_n_17;
  wire add_23_2_n_19, add_23_2_n_20, add_23_2_n_24;
  XNOR2X1 add_23_2_g105(.A (add_23_2_n_11), .B (add_23_2_n_24), .Y
       (out1[5]));
  OAI2BB1X1 add_23_2_g106(.A0N (add_23_2_n_5), .A1N (add_23_2_n_17),
       .B0 (add_23_2_n_4), .Y (add_23_2_n_24));
  XNOR2X1 add_23_2_g107(.A (add_23_2_n_9), .B (add_23_2_n_17), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g108(.A (add_23_2_n_8), .B (add_23_2_n_19), .Y
       (out1[3]));
  OAI211X1 add_23_2_g109(.A0 (add_23_2_n_4), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_20), .C0 (add_23_2_n_0), .Y (out1[6]));
  NAND3BXL add_23_2_g110(.AN (add_23_2_n_1), .B (add_23_2_n_17), .C
       (add_23_2_n_5), .Y (add_23_2_n_20));
  OAI2BB1X1 add_23_2_g111(.A0N (add_23_2_n_3), .A1N (add_23_2_n_15),
       .B0 (add_23_2_n_2), .Y (add_23_2_n_19));
  XNOR2X1 add_23_2_g112(.A (add_23_2_n_10), .B (add_23_2_n_15), .Y
       (out1[2]));
  OAI211X1 add_23_2_g113(.A0 (add_23_2_n_2), .A1 (add_23_2_n_7), .B0
       (add_23_2_n_16), .C0 (add_23_2_n_6), .Y (add_23_2_n_17));
  NAND3BXL add_23_2_g114(.AN (add_23_2_n_7), .B (add_23_2_n_15), .C
       (add_23_2_n_3), .Y (add_23_2_n_16));
  ADDFX1 add_23_2_g115(.A (add_23_2_n_12), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_15), .S (out1[1]));
  ADDHX1 add_23_2_g116(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_12),
       .S (out1[0]));
  NAND2BX1 add_23_2_g117(.AN (add_23_2_n_1), .B (add_23_2_n_0), .Y
       (add_23_2_n_11));
  NAND2X1 add_23_2_g118(.A (add_23_2_n_2), .B (add_23_2_n_3), .Y
       (add_23_2_n_10));
  NAND2X1 add_23_2_g119(.A (add_23_2_n_4), .B (add_23_2_n_5), .Y
       (add_23_2_n_9));
  NAND2BX1 add_23_2_g120(.AN (add_23_2_n_7), .B (add_23_2_n_6), .Y
       (add_23_2_n_8));
  NOR2X1 add_23_2_g121(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g122(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_6));
  OR2XL add_23_2_g123(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g124(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_4));
  OR2XL add_23_2_g125(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g126(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g127(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g128(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_0));
endmodule


