`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:23:42 CST (May 26 2023 07:23:42 UTC)

module dut_entirecomputation_alt4_0(in1, in2, in3, out1);
  input in1, in2;
  input [2:0] in3;
  output [3:0] out1;
  wire in1, in2;
  wire [2:0] in3;
  wire [3:0] out1;
  wire n_5, n_7, n_42, n_43, n_44, n_45, n_46, n_58;
  wire n_64, n_68, n_69, n_76, n_78, n_79, n_80, n_81;
  wire n_83, n_84;
  NOR2X1 g1226(.A (in3[0]), .B (n_58), .Y (n_7));
  NOR2X1 g1224(.A (in2), .B (n_42), .Y (n_5));
  INVX1 g244(.A (in3[0]), .Y (n_42));
  INVX1 g104(.A (n_43), .Y (n_44));
  NOR2X1 g105(.A (in1), .B (in3[1]), .Y (n_43));
  NAND2X1 g107(.A (in3[1]), .B (n_45), .Y (n_46));
  INVX2 g216(.A (in2), .Y (n_58));
  NAND2X1 g222(.A (in3[0]), .B (in3[1]), .Y (n_64));
  NAND2X1 g223(.A (in3[2]), .B (n_45), .Y (n_68));
  CLKINVX4 g225(.A (in1), .Y (n_45));
  INVX2 g224(.A (in2), .Y (n_69));
  MXI2X1 g30(.A (n_44), .B (n_46), .S0 (n_76), .Y (out1[1]));
  NAND2X2 g31(.A (in3[0]), .B (in2), .Y (n_76));
  NOR2X4 g16(.A (n_69), .B (n_78), .Y (n_79));
  NAND2X8 g17(.A (in3[1]), .B (in3[0]), .Y (n_78));
  OAI22X2 g1235(.A0 (n_64), .A1 (n_81), .B0 (n_68), .B1 (n_79), .Y
       (out1[2]));
  NAND2X4 g1236(.A (in2), .B (n_80), .Y (n_81));
  NOR2X6 g1237(.A (in1), .B (in3[2]), .Y (n_80));
  NOR3BX1 g41(.AN (in3[0]), .B (n_83), .C (n_84), .Y (out1[3]));
  NAND2X2 g1238(.A (in2), .B (in3[1]), .Y (n_83));
  NAND2X1 g42(.A (in3[2]), .B (n_45), .Y (n_84));
  AOI2BB1XL g24(.A0N (n_7), .A1N (n_5), .B0 (in1), .Y (out1[0]));
endmodule


