`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 18 2023 16:38:07 CST (May 18 2023 08:38:07 UTC)

module dut_Add2Cati0Subi1u3u6_4(in2, in1, out1);
  input [5:0] in2;
  input [2:0] in1;
  output [5:0] out1;
  wire [5:0] in2;
  wire [2:0] in1;
  wire [5:0] out1;
  wire add_31_2_n_1, add_31_2_n_2, add_31_2_n_4, asc004_1_, asc004_2_,
       n_0, n_1;
  assign out1[0] = in2[0];
  assign out1[1] = in2[1];
  assign out1[2] = in2[2];
  INVX1 g45(.A (in1[0]), .Y (n_1));
  XOR2XL g60(.A (in1[2]), .B (n_0), .Y (asc004_2_));
  AO21XL g61(.A0 (in1[1]), .A1 (in1[0]), .B0 (n_0), .Y (asc004_1_));
  NOR2X1 g62(.A (in1[1]), .B (in1[0]), .Y (n_0));
  XNOR2X1 add_31_2_g83(.A (add_31_2_n_2), .B (add_31_2_n_4), .Y
       (out1[5]));
  ADDFX1 add_31_2_g84(.A (add_31_2_n_1), .B (in2[4]), .CI (asc004_1_),
       .CO (add_31_2_n_4), .S (out1[4]));
  AOI2BB1X1 add_31_2_g85(.A0N (in2[3]), .A1N (n_1), .B0 (add_31_2_n_1),
       .Y (out1[3]));
  XNOR2X1 add_31_2_g86(.A (in2[5]), .B (asc004_2_), .Y (add_31_2_n_2));
  AND2XL add_31_2_g87(.A (in2[3]), .B (n_1), .Y (add_31_2_n_1));
endmodule


