`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:53:07 CST (May 16 2023 12:53:07 UTC)

module dut_Equal_1U_24_1(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  NOR2BX1 g43(.AN (n_4), .B (n_7), .Y (out1));
  NAND2X1 g44(.A (n_5), .B (n_6), .Y (n_7));
  NOR2X2 g45(.A (n_1), .B (n_2), .Y (n_6));
  NOR2X4 g47(.A (n_3), .B (n_0), .Y (n_5));
  NOR2X1 g46(.A (in1[5]), .B (in1[4]), .Y (n_4));
  CLKINVX12 g49(.A (in1[3]), .Y (n_3));
  CLKINVX2 g50(.A (in1[0]), .Y (n_2));
  CLKINVX4 g51(.A (in1[1]), .Y (n_1));
  CLKINVX4 g48(.A (in1[2]), .Y (n_0));
endmodule


