`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:29 CST (May 16 2023 12:52:29 UTC)

module dut_Equal_1U_60_4(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1;
  NOR4BX1 g21(.AN (in1[5]), .B (n_1), .C (n_0), .D (in1[4]), .Y (out1));
  NAND2X1 g22(.A (in1[1]), .B (in1[0]), .Y (n_1));
  NAND2X1 g23(.A (in1[3]), .B (in1[2]), .Y (n_0));
endmodule


