`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 18 2023 16:38:12 CST (May 18 2023 08:38:12 UTC)

module dut_AnyAdd2u6Cati0u3_1(in2, in1, out1);
  input [2:0] in2;
  input [5:0] in1;
  output out1;
  wire [2:0] in2;
  wire [5:0] in1;
  wire out1;
  wire add_27_2_n_0, add_27_2_n_3, add_27_2_n_4, add_27_2_n_5,
       add_27_2_n_6, add_27_2_n_7, add_27_2_n_9, add_27_2_n_11;
  wire asc002_3_, asc002_4_, n_0, n_1, n_2, n_22;
  NAND2X1 g9(.A (n_0), .B (n_2), .Y (out1));
  NOR3X2 g10(.A (n_1), .B (asc002_4_), .C (n_22), .Y (n_2));
  OR2XL g11(.A (in1[2]), .B (asc002_3_), .Y (n_1));
  NOR2X1 g12(.A (in1[1]), .B (in1[0]), .Y (n_0));
  OAI21X1 add_27_2_g81(.A0 (add_27_2_n_6), .A1 (add_27_2_n_4), .B0
       (add_27_2_n_5), .Y (add_27_2_n_11));
  XNOR2X1 add_27_2_g82(.A (add_27_2_n_4), .B (add_27_2_n_9), .Y
       (asc002_4_));
  NOR2BX1 add_27_2_g83(.AN (add_27_2_n_5), .B (add_27_2_n_6), .Y
       (add_27_2_n_9));
  NOR2X1 add_27_2_g86(.A (add_27_2_n_3), .B (add_27_2_n_0), .Y
       (add_27_2_n_7));
  NOR2X1 add_27_2_g87(.A (in2[1]), .B (in1[4]), .Y (add_27_2_n_6));
  NAND2X2 add_27_2_g89(.A (in2[1]), .B (in1[4]), .Y (add_27_2_n_5));
  NAND2X4 add_27_2_g91(.A (in2[0]), .B (in1[3]), .Y (add_27_2_n_4));
  NOR2X1 add_27_2_g92(.A (in2[2]), .B (in1[5]), .Y (add_27_2_n_3));
  OA21X1 add_27_2_g2(.A0 (in2[0]), .A1 (in1[3]), .B0 (add_27_2_n_4), .Y
       (asc002_3_));
  AND2XL add_27_2_g95(.A (in2[2]), .B (in1[5]), .Y (add_27_2_n_0));
  XOR2XL g2(.A (add_27_2_n_7), .B (add_27_2_n_11), .Y (n_22));
endmodule


