`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:52:09 CST (May 16 2023 12:52:09 UTC)

module dut_Add_6Ux6U_6U_4(in2, in1, out1);
  input [5:0] in2, in1;
  output [5:0] out1;
  wire [5:0] in2, in1;
  wire [5:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_10, add_23_2_n_11, add_23_2_n_12, add_23_2_n_14,
       add_23_2_n_16;
  XNOR2X1 add_23_2_g98(.A (add_23_2_n_4), .B (add_23_2_n_16), .Y
       (out1[5]));
  ADDFX1 add_23_2_g99(.A (add_23_2_n_12), .B (in1[4]), .CI (in2[4]),
       .CO (add_23_2_n_16), .S (out1[4]));
  XNOR2X1 add_23_2_g100(.A (add_23_2_n_6), .B (add_23_2_n_14), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g101(.A0N (add_23_2_n_2), .A1N (add_23_2_n_10),
       .B0 (add_23_2_n_1), .Y (add_23_2_n_14));
  XNOR2X1 add_23_2_g102(.A (add_23_2_n_5), .B (add_23_2_n_10), .Y
       (out1[2]));
  OAI211X1 add_23_2_g103(.A0 (add_23_2_n_1), .A1 (add_23_2_n_0), .B0
       (add_23_2_n_11), .C0 (add_23_2_n_3), .Y (add_23_2_n_12));
  NAND3BXL add_23_2_g104(.AN (add_23_2_n_0), .B (add_23_2_n_10), .C
       (add_23_2_n_2), .Y (add_23_2_n_11));
  ADDFX1 add_23_2_g105(.A (add_23_2_n_7), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_10), .S (out1[1]));
  ADDHX1 add_23_2_g106(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_7), .S
       (out1[0]));
  NAND2BX1 add_23_2_g107(.AN (add_23_2_n_0), .B (add_23_2_n_3), .Y
       (add_23_2_n_6));
  NAND2X1 add_23_2_g108(.A (add_23_2_n_1), .B (add_23_2_n_2), .Y
       (add_23_2_n_5));
  XNOR2X1 add_23_2_g109(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g110(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_3));
  OR2XL add_23_2_g111(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  NAND2X1 add_23_2_g112(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_1));
  NOR2X1 add_23_2_g113(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_0));
endmodule


