`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:23:46 CST (May 26 2023 07:23:46 UTC)

module dut_entirecomputation_alt2_0(in1, in2, in3, out1);
  input in1, in2, in3;
  output [1:0] out1;
  wire in1, in2, in3;
  wire [1:0] out1;
  wire n_28, n_29, n_45, n_46, n_47;
  NOR3X2 g17(.A (in1), .B (n_28), .C (n_29), .Y (out1[1]));
  CLKINVX4 g19(.A (in3), .Y (n_28));
  OAI21X2 g56(.A0 (in1), .A1 (n_45), .B0 (n_47), .Y (out1[0]));
  NAND2X4 g58(.A (in3), .B (n_29), .Y (n_45));
  CLKINVX6 g60(.A (in2), .Y (n_29));
  NAND2X4 g57(.A (in2), .B (n_46), .Y (n_47));
  NOR2X8 g59(.A (in1), .B (in3), .Y (n_46));
endmodule


