`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 24 2023 19:41:55 CST (May 24 2023 11:41:55 UTC)

module dut_N_Mux_9_2_53_1(in2, ctrl1, out1);
  input [8:0] in2;
  input ctrl1;
  output [8:0] out1;
  wire [8:0] in2;
  wire ctrl1;
  wire [8:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  NOR2X4 g86(.A (ctrl1), .B (n_5), .Y (out1[6]));
  NOR2X4 g83(.A (ctrl1), .B (n_6), .Y (out1[7]));
  NOR2X4 g84(.A (ctrl1), .B (n_7), .Y (out1[8]));
  NOR2X4 g82(.A (ctrl1), .B (n_8), .Y (out1[5]));
  NOR2X4 g90(.A (ctrl1), .B (n_4), .Y (out1[2]));
  NOR2X4 g89(.A (ctrl1), .B (n_1), .Y (out1[3]));
  NOR2X4 g87(.A (ctrl1), .B (n_3), .Y (out1[4]));
  NOR2X4 g85(.A (ctrl1), .B (n_2), .Y (out1[1]));
  NOR2X4 g88(.A (ctrl1), .B (n_0), .Y (out1[0]));
  CLKINVX12 g95(.A (in2[5]), .Y (n_8));
  CLKINVX12 g99(.A (in2[8]), .Y (n_7));
  CLKINVX12 g91(.A (in2[7]), .Y (n_6));
  CLKINVX12 g93(.A (in2[6]), .Y (n_5));
  CLKINVX12 g97(.A (in2[2]), .Y (n_4));
  CLKINVX12 g92(.A (in2[4]), .Y (n_3));
  CLKINVX12 g96(.A (in2[1]), .Y (n_2));
  CLKINVX12 g98(.A (in2[3]), .Y (n_1));
  CLKINVX12 g94(.A (in2[0]), .Y (n_0));
endmodule


