`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:53:23 CST (May 16 2023 12:53:23 UTC)

module dut_Equal_1U_66_1(in1, out1);
  input [5:0] in1;
  output out1;
  wire [5:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4;
  NOR3X2 g49(.A (n_2), .B (n_3), .C (n_4), .Y (out1));
  NAND2X2 g50(.A (n_1), .B (n_0), .Y (n_4));
  NAND2X4 g52(.A (in1[1]), .B (in1[0]), .Y (n_3));
  NAND2X8 g51(.A (in1[5]), .B (in1[4]), .Y (n_2));
  CLKINVX3 g54(.A (in1[3]), .Y (n_1));
  INVX2 g53(.A (in1[2]), .Y (n_0));
endmodule


