`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 16 2023 20:15:45 CST (May 16 2023 12:15:45 UTC)

module dut_Equal_14Ux2U_1U_4(in2, in1, out1);
  input [13:0] in2;
  input [1:0] in1;
  output out1;
  wire [13:0] in2;
  wire [1:0] in1;
  wire out1;
  wire eq_21_21_n_0, eq_21_21_n_1, eq_21_21_n_2, eq_21_21_n_3,
       eq_21_21_n_4, eq_21_21_n_5;
  NOR4X1 eq_21_21_g31(.A (eq_21_21_n_5), .B (eq_21_21_n_0), .C
       (in2[3]), .D (in2[2]), .Y (out1));
  NAND4XL eq_21_21_g32(.A (eq_21_21_n_4), .B (eq_21_21_n_2), .C
       (eq_21_21_n_3), .D (eq_21_21_n_1), .Y (eq_21_21_n_5));
  XNOR2X1 eq_21_21_g33(.A (in1[1]), .B (in2[1]), .Y (eq_21_21_n_4));
  XNOR2X1 eq_21_21_g34(.A (in1[0]), .B (in2[0]), .Y (eq_21_21_n_3));
  NOR4X1 eq_21_21_g35(.A (in2[13]), .B (in2[12]), .C (in2[11]), .D
       (in2[10]), .Y (eq_21_21_n_2));
  NOR4X1 eq_21_21_g36(.A (in2[9]), .B (in2[8]), .C (in2[7]), .D
       (in2[6]), .Y (eq_21_21_n_1));
  OR2XL eq_21_21_g37(.A (in2[5]), .B (in2[4]), .Y (eq_21_21_n_0));
endmodule


