`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 15:20:19 CST (May 26 2023 07:20:19 UTC)

module dut_entirecomputation_alt8_0(in1, in2, in3, out1);
  input in1, in2;
  input [6:0] in3;
  output [7:0] out1;
  wire in1, in2;
  wire [6:0] in3;
  wire [7:0] out1;
  wire n_71, n_239, n_240, n_244, n_309, n_310, n_311, n_422;
  wire n_423, n_439, n_442, n_446, n_454, n_459, n_467, n_479;
  wire n_481, n_485, n_486, n_514, n_515, n_516, n_517, n_527;
  wire n_529, n_537, n_538, n_544, n_546, n_549, n_550, n_551;
  wire n_552, n_553, n_554, n_555, n_556, n_557, n_566, n_567;
  wire n_573, n_574, n_580, n_582, n_583, n_603, n_616, n_617;
  wire n_618, n_619, n_625, n_627, n_628, n_629, n_630, n_631;
  wire n_633, n_634, n_649, n_651, n_656, n_661, n_662;
  CLKINVX4 g3464(.A (in3[3]), .Y (n_71));
  NOR3X1 g3486(.A (n_239), .B (n_240), .C (n_454), .Y (out1[7]));
  NAND2X1 g3487(.A (in3[3]), .B (in3[2]), .Y (n_239));
  NAND3X1 g3488(.A (in2), .B (in3[0]), .C (in3[1]), .Y (n_240));
  INVX1 g3492(.A (n_309), .Y (n_244));
  NAND2X4 g24(.A (in3[5]), .B (in3[4]), .Y (n_309));
  INVX1 g25(.A (n_310), .Y (n_311));
  NOR2X2 g26(.A (in1), .B (in3[6]), .Y (n_310));
  NAND2X2 g702(.A (in3[1]), .B (in3[3]), .Y (n_422));
  NAND2X1 g700(.A (in3[2]), .B (in2), .Y (n_423));
  NAND2X2 g207(.A (in3[1]), .B (in3[5]), .Y (n_439));
  NOR2X2 g209(.A (n_309), .B (n_311), .Y (n_442));
  NAND3X8 g105(.A (in3[4]), .B (in3[2]), .C (in2), .Y (n_446));
  NAND2X1 g117(.A (n_583), .B (n_244), .Y (n_454));
  INVX2 g101(.A (in3[5]), .Y (n_459));
  NAND2X4 g3561(.A (in3[0]), .B (in3[3]), .Y (n_467));
  NAND2X4 g3565(.A (in3[0]), .B (in2), .Y (n_479));
  NAND2BX1 g83(.AN (in3[1]), .B (n_479), .Y (n_481));
  NOR3X4 g113(.A (n_467), .B (n_439), .C (n_446), .Y (n_485));
  NAND2X2 g114(.A (n_442), .B (n_517), .Y (n_486));
  NOR3X4 g43(.A (n_514), .B (n_515), .C (n_516), .Y (n_517));
  CLKINVX6 g46(.A (in3[0]), .Y (n_514));
  NAND2X6 g44(.A (in2), .B (in3[1]), .Y (n_515));
  NAND2X2 g45(.A (in3[3]), .B (in3[2]), .Y (n_516));
  NAND2X2 g336(.A (in2), .B (in3[0]), .Y (n_527));
  NOR2X1 g335(.A (in3[3]), .B (in1), .Y (n_529));
  OAI21X1 g453(.A0 (n_538), .A1 (n_544), .B0 (n_546), .Y (out1[4]));
  NOR2X1 g457(.A (in3[4]), .B (n_537), .Y (n_538));
  NOR2X1 g463(.A (n_422), .B (n_423), .Y (n_537));
  NAND2XL g454(.A (n_567), .B (n_574), .Y (n_544));
  NAND2X1 g455(.A (n_567), .B (n_651), .Y (n_546));
  OAI31X1 g490(.A0 (in1), .A1 (n_459), .A2 (n_552), .B0 (n_557), .Y
       (out1[5]));
  NOR3X2 g491(.A (n_549), .B (n_550), .C (n_551), .Y (n_552));
  NAND2X4 g497(.A (in3[1]), .B (in3[4]), .Y (n_549));
  NAND2X2 g499(.A (in3[3]), .B (in3[2]), .Y (n_550));
  NAND2X2 g498(.A (in2), .B (in3[0]), .Y (n_551));
  NAND2X1 g492(.A (n_554), .B (n_556), .Y (n_557));
  NOR3X2 g494(.A (in1), .B (n_71), .C (n_553), .Y (n_554));
  NAND2X4 g496(.A (in3[2]), .B (in3[1]), .Y (n_553));
  NOR2X1 g493(.A (n_551), .B (n_555), .Y (n_556));
  NAND2X1 g495(.A (in3[4]), .B (n_459), .Y (n_555));
  NOR2X2 g3573(.A (in1), .B (n_566), .Y (n_567));
  NOR2X4 g3574(.A (in3[4]), .B (in3[0]), .Y (n_566));
  NAND2X1 g27(.A (n_627), .B (n_573), .Y (n_574));
  NOR2X2 g29(.A (n_514), .B (n_71), .Y (n_573));
  OAI21X2 g2(.A0 (n_580), .A1 (n_485), .B0 (n_486), .Y (out1[6]));
  NAND2BX1 g3(.AN (in1), .B (in3[6]), .Y (n_580));
  NOR2X1 g3580(.A (in1), .B (n_582), .Y (n_583));
  INVX2 g3581(.A (in3[6]), .Y (n_582));
  NOR3X1 g41(.A (in1), .B (n_649), .C (n_603), .Y (out1[1]));
  INVX1 g3586(.A (n_481), .Y (n_603));
  NAND2X2 g3596(.A (in3[2]), .B (in3[1]), .Y (n_616));
  NAND2X2 g3597(.A (in2), .B (in3[0]), .Y (n_617));
  NAND2X1 g3598(.A (n_619), .B (n_634), .Y (out1[3]));
  OAI21X1 g3599(.A0 (n_617), .A1 (n_616), .B0 (n_618), .Y (n_619));
  NOR2X1 g3600(.A (in1), .B (n_71), .Y (n_618));
  NOR2X2 g12(.A (n_625), .B (n_656), .Y (n_627));
  CLKINVX6 g13(.A (in3[1]), .Y (n_625));
  NAND2X1 g55(.A (n_629), .B (n_631), .Y (out1[0]));
  NAND2X1 g57(.A (in3[0]), .B (n_628), .Y (n_629));
  NOR2X1 g59(.A (in2), .B (in1), .Y (n_628));
  NAND2X1 g56(.A (in2), .B (n_630), .Y (n_631));
  NOR2X1 g3601(.A (in1), .B (in3[0]), .Y (n_630));
  NAND2X1 g15(.A (n_529), .B (n_633), .Y (n_634));
  NOR2X1 g16(.A (n_527), .B (n_616), .Y (n_633));
  NOR2BX1 g3612(.AN (in3[1]), .B (n_479), .Y (n_649));
  AOI21X1 g3614(.A0 (in2), .A1 (in3[2]), .B0 (n_656), .Y (n_651));
  AOI2BB1X1 g3615(.A0N (in3[2]), .A1N (n_649), .B0 (n_662), .Y
       (out1[2]));
  INVX3 fopt3619(.A (in3[4]), .Y (n_656));
  OAI21X1 g3620(.A0 (n_553), .A1 (n_617), .B0 (n_661), .Y (n_662));
  INVXL g3621(.A (in1), .Y (n_661));
endmodule


